### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:3000

### ISSUE THREAD

**Issue by sateesh2020** [ONLYOFFICE/DocumentServer#1014]
**Bug**

**What is the current behavior?**
Unable to edit documents getting below error 

![image](https://user-images.githubusercontent.com/5172059/95077571-540f1a80-0731-11eb-94f8-bbed10f50bbc.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Ran docker development server image on port 80
* Used the nodejs example web application
* Updated the `default.json` with `siteUrl`
* Ran the application and went to editor url. 
 
**What is the expected behavior?**
* Should be able to edit the document. 

**Did this work in previous versions of DocumentServer?**
* Not checked 

**DocumentServer version:**
* Latest Docker Image from hub

**Operating System:**
* Windows 10 with Docker Desktop. 

**Browser version:**

* Chrome v85

Docker logs:

```log
==> /var/log/onlyoffice/documentserver/docservice/out.log <==

[2020-10-05T11:52:22.939] [ERROR] nodeJS - postData error: docId = __ffff_127.0.0.1http___127.0.0.1_3000_files___ffff_127.0.0.1_new.docx1601894467335;url = http://127.0.0.1:3000/track?filename=new.docx&useraddress=__ffff_127.0.0.1;data = {"key":"__ffff_127.0.0.1http___127.0.0.1_3000_files___ffff_127.0.0.1_new.docx1601894467335","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}]}

Error: connect ECONNREFUSED 127.0.0.1:3000

at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)


==> /var/log/onlyoffice/documentserver/converter/out.log <==

[2020-10-05T11:52:22.948] [ERROR] nodeJS - error downloadFile:url=http://127.0.0.1:3000/files/__ffff_127.0.0.1/new.docx;attempt=1;code:ECONNREFUSED;connect:null;(id=__ffff_127.0.0.1http___127.0.0.1_3000_files___ffff_127.0.0.1_new.docx1601894467335)

Error: connect ECONNREFUSED 127.0.0.1:3000

at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

[2020-10-05T11:52:23.951] [ERROR] nodeJS - error downloadFile:url=http://127.0.0.1:3000/files/__ffff_127.0.0.1/new.docx;attempt=2;code:ECONNREFUSED;connect:null;(id=__ffff_127.0.0.1http___127.0.0.1_3000_files___ffff_127.0.0.1_new.docx1601894467335)

Error: connect ECONNREFUSED 127.0.0.1:3000

at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)

[2020-10-05T11:52:24.957] [ERROR] nodeJS - error downloadFile:url=http://127.0.0.1:3000/files/__ffff_127.0.0.1/new.docx;attempt=3;code:ECONNREFUSED;connect:null;(id=__ffff_127.0.0.1http___127.0.0.1_3000_files___ffff_127.0.0.1_new.docx1601894467335)

Error: connect ECONNREFUSED 127.0.0.1:3000

at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)


==> /var/log/onlyoffice/documentserver/metrics/out.log <==
```

**Comment by ShockwaveNN** [comment]
Hi, could you check for Firewall? Same error happens on Ubuntu if firewall is blocking this port, not sure what happens on windows.

**Comment by sateesh2020** [comment]
@ShockwaveNN Can you provide few more details like what should I be checking on Firewall. 
Any other post on how you solved it on ubuntu also helps. 
Thanks.

**Comment by sateesh2020** [comment]
@ShockwaveNN 
I feel this is related to https://github.com/ONLYOFFICE/document-server-integration/issues/58. 
Could you let me know what should be the value of `exampleUrl` ?

**Comment by ShockwaveNN** [comment]
As mention at [here](https://github.com/ONLYOFFICE/document-server-integration/issues/58#issuecomment-475514665)

You should use not 127.0.0.1 to open test example, but your real local (like 192.168.3.105) or external IP (public, if you using some kind of cloud), since container with DocumentServer has it's own network by 127.0.0.1

**Comment by sateesh2020** [comment]
@ShockwaveNN Thanks that worked. 
Posting the configuration here to help other's having same issue.

```json
server": {
    "port": 3005,
    "siteUrl": "http://localhost/",
    "commandUrl": "coauthoring/CommandService.ashx",
    "converterUrl": "ConvertService.ashx",
    "tempStorageUrl": "ResourceService.ashx",
    "apiUrl": "web-apps/apps/api/documents/api.js",
    "preloaderUrl": "web-apps/apps/api/documents/cache-scripts.html",
    "exampleUrl": "http://192.168.43.193:3005",  // Your IPv4 Address from ifconfig / ipconfig. 
    "viewedDocs": [
      ".pdf",
      ".djvu",
      ".xps"
    ],
 ...... rest
```
