### ISSUE TITLE
Unable to edit .doc file.

### ISSUE THREAD

**Issue by jrjena136** [ONLYOFFICE/DocumentServer#1058]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
The document is not getting saved

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Unable to save document after editing. document is of  type `.doc`. This behaviour is not for all `.doc` documents. Getting below error.

```
[2020-11-04T07:46:01.128] [ERROR] nodeJS - error spawnAsync(id=41b302cd1)
Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGABRT
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:51:23)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js:0:0)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-11-04T07:46:01.128] [ERROR] nodeJS - stdout (id=41b302cd1_4385):
[2020-11-04T07:46:01.128] [ERROR] nodeJS - stderr (id=41b302cd1_4385):terminate called without an active exception
Received signal 6
==== C stack trace ===============================
 [0x7f7e59da0d82]
 [0x7f7e591f68a0]
 [0x7f7e58a93f47]
 [0x7f7e58a958b1]
 [0x7f7e5bf04a75]
 [0x7f7e5bee2bc6]
 [0x7f7e5bee2bf3]
 [0x7f7e5bee28c6]
 [0x0000018e1e0b]
 [0x000001739c0a]
 [0x00000173a48d]
 [0x0000009f9728]
 [0x0000009ffe8d]
 [0x000000a012f4]
 [0x0000016bac75]
 [0x0000016baeb2]
 [0x0000016e216d]
 [0x00000151e492]
 [0x00000072d24d]
 [0x000000734c45]
 [0x0000007380b6]
 [0x00000053cbbf]
 [0x7f7e58a76b97]
 [0x000000713ca3]
[end of stack trace]
[2020-11-04T07:46:01.128] [ERROR] nodeJS - ExitCode (code=0;signal=SIGABRT;error:-80;id=41b302cd1_4385)
```
As per the comment here https://github.com/ONLYOFFICE/DocumentServer/issues/989#issuecomment-695202201. It should work with latest image.
But after updating the onlyoffice image to `onlyoffice/documentserver:latest` I am getting below error

```
==> /var/log/onlyoffice/documentserver/converter/out.log <==
[2020-11-04T11:05:37.989] [ERROR] nodeJS - stdout (id=41b302cd1_4443):
[2020-11-04T11:05:37.990] [ERROR] nodeJS - stderr (id=41b302cd1_4443):change_code: a)+1]=d};Tb.prototype.ZI=function(){this.Na&&(this.Na.gA.pue(),this.Na.ud.Lgb(Ff))};Tb.prototype.Mm=function(c){if(this.Na){for(var a=0;a<this.aa.length&&(!this.aa[a].xb||this.aa[a].xb()!==c);++a);if(a<this.aa.length)return this.Na.Mm(this.xb())}return!1};Tb.prototype.J0=function(){return this.Mm(void 0)};Tb.prototype.Sq=function(){this.Na&&this.Na.Ba&&this.Na.Ba.pxb&&this.Na.Ba.lr.Fvb(this.Na)};Tb.prototype.rFa=function(){return!0};Tb.prototype.Pv=function(){};Tb.prototype.Jnb=function(){this.Na&&
change: Uncaught TypeError: Cannot read property 'pue' of undefined
DoctRenderer:<result><error index="8" /></result>

Can anyone from the team help on this.
@ShockwaveNN could you please let us know what could be the issue here?
```
**What is the expected behavior?**
The document after edited should be saved correctly

**Did this work in previous versions of DocumentServer?**
no

**DocumentServer version:**
using latest onlyoffice image `onlyoffice/documentserver:latest

**Operating System:**
Ubuntu 18

*Note: I can not share the document, it is confidential.

**Comment by ShockwaveNN** [comment]
Hi, to be clear `SIGABRT` is for older version and this problem should be fixed

Current error is 
```
change: Uncaught TypeError: Cannot read property 'pue' of undefined
DoctRenderer:<result><error index="8" /></result>
```

I've never see those error before, so I'm afraid I'll need file to do something with it

>*Note: I can not share the document, it is confidential.

Maybe you can remove or replace confidential data from this file to some random text?

**Comment by jrjena136** [comment]
Thanks for your reply.
I will check once with the latest tag on my cluster.

**Comment by jrjena136** [comment]
@ShockwaveNN It is working. I am closing this ticket

**Comment by ShockwaveNN** [comment]
Could you clarify what fixed `Cannot read property 'pue' of undefined` error? Updating to latest stable version?

**Comment by jrjena136** [comment]
I used to use to the compiled version of contents over the latest only office image. so there was some compatibility issue with the lastest onlyoffice image and the compiled contents. So again I compiled from the latest source code and it worked.

Thanks

**Comment by ShockwaveNN** [comment]
Yeah, this is pretty complicated scenario with usage of compiled version, please note it in future if you got any issues
