### ISSUE TITLE
Can't open a document with a chart

### ISSUE THREAD

**Issue by jlemangarin** [ONLYOFFICE/DocumentServer#1212]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Can't open the document in OnlyOffice

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open the document

**Error log** : 
```
[2021-04-07T17:15:34.958] [ERROR] nodeJS - changesError: docId = c3c07e8f-80b0-4dd6-92a7-6ae28316b859_k9y3g8lvwp7iqubxtalh Error: Uncaught TypeError: Cannot read property 'cc' of null Script: https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js Line: 3754:479 userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 platform: Linux x86_64 isLoadFullApi: true isDocumentLoadComplete: true StackTrace: TypeError: Cannot read property 'cc' of null
    at Nb.HId (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:3754:479)
    at Nb.ZYf (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:3774:148)
    at Nb.<anonymous> (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:6649:471)
    at Object.pb [as Oh] (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:3092:295)
    at Nb.im.ah (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:6648:115)
    at od.ehg (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:6665:15)
    at rf.epb (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:8431:249)
    at rf.ZPb (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:8434:321)
    at rf.LAb (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:8602:347)
    at rf.epb (https://gofast-comm.ceo-vision.com/6.1.0-83/sdkjs/word/sdk-all.js:8429:181)
```
**Screenshot** : 
![Capture d’écran de 2021-04-07 17-18-06](https://user-images.githubusercontent.com/22454938/113891312-3fd1d600-97c5-11eb-8a4d-6bd58c809f98.png)

**What is the expected behavior?**
Document opens

**Did this work in previous versions of DocumentServer?**
I don't know

**DocumentServer version:**
6.1.0

**Operating System:**
CentOS 7

**Browser version:**
All

File is linked, thanks in advance !

[Onlyoffice_Chart_Issue.docx](https://github.com/ONLYOFFICE/DocumentServer/files/6272685/Onlyoffice_Chart_Issue.docx)

**Comment by ShockwaveNN** [comment]
Hi there

I can confirm this is a bug, this problem is reproduces even on latest v6.2.1

But I checked your file on v6.3.0 that currently in development and problem is fixed there
As usual I cannot guarantee any time frame for this release, but I hope in will be somewhere in a month

**Comment by cpot** [comment]
> 
> 
> Hi there
> 
> I can confirm this is a bug, this problem is reproduces even on latest v6.2.1
> 
> But I checked your file on v6.3.0 that currently in development and problem is fixed there
> As usual I cannot guarantee any time frame for this release, but I hope in will be somewhere in a month

Having the possibility to add OO6.3 in GoFAST 3.10 (due end April) would be great

**Comment by ShockwaveNN** [comment]
DocumentServer v6.3.0 is released. This problem should be fixed
