### ISSUE TITLE
cannot open xls or ppt 

### ISSUE THREAD

**Issue by vincentchen** [ONLYOFFICE/DocumentServer#1226]
report a *bug*
always "loading spreadsheet" or "loading presentation"
docker logs show "
[2021-04-15T03:20:45.635] [ERROR] nodeJS - changesError: docId = 172.17.0.1http___localhost_example_files_172.17.0.1_new.pptx1618394539570 Error: Uncaught TypeError: se.uUb is not a function Script: http://localhost/6.2.1-24/sdkjs/common/libfont/wasm/fonts.js Line: 38:226 userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36 Edg/89.0.774.68 platform: Win32 isLoadFullApi: false isDocumentLoadComplete: false StackTrace: TypeError: se.uUb is not a function

at http://localhost/6.2.1-24/sdkjs/common/libfont/wasm/fonts.js:38:226

at http://localhost/6.2.1-24/sdkjs/common/libfont/wasm/fonts.js:38:233
"

**Comment by ShockwaveNN** [comment]
1. libfont/wasm error are known error while loading document via test example, so those errors are not the reason
I think there should be another errors in other log files, mayb in `/var/log/onlyoffice/documentserver/converter`
2. I think we'll need those files which failing or those error on any xls and ppt file?

**Comment by vincentchen** [comment]
1，nothing err log at /var/log/onlyoffice/documentserver/converter
2、Even new create xls or ppt from test  example will reproduce the problem

**Comment by ShockwaveNN** [comment]
> Even new create xls or ppt from test example will reproduce the problem

test example do not create xls or ppt, it's only creates docx, xlsx or pptx

Could you show me your full `docker run` command - seems maybe some extra volume mapping or something like this broke some important service

**Comment by vincentchen** [comment]
docker run -i -t -d -p 80:80 onlyoffice/documentserver.Mount non volume.
Works on mac but not on my windows10.and just xlsx or pptx have the problem. word works fine.

**Comment by ShockwaveNN** [comment]
> Works on mac but not on my windows10.and just xlsx or pptx have the problem. word works fine.

If you using same server on different pcs and one works and other not - try to clear browser cache on non-working client or use another broswer

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
