### ISSUE TITLE
OpenOffice  download fail（join token）

### ISSUE THREAD

**Issue by verydemo** [ONLYOFFICE/DocumentServer#1230]
When I use jwt token, the download fails,

url: Encrypted links generated by Minio；(i try short URL is no problem)

version:6.2

token: header  

 log:

` [ERROR] nodeJS - error downloadFile:url=http://39.106.7.234:9000/declaration/702cd99e-ad06-4887-8060-2636ebb2c69f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20210416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210416T015828Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=91327e5f74e29bda9c9c8b0bedfda6c7c02f7342d7f0effbff2922261c2b5155;attempt=1;code:null;connect:null;(id=702cd99e-ad06-4887-8060-2636ebb2c69f_1)
Error: Error response: statusCode:400 ;body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Invalid Request</Message><Resource>/declaration/702cd99e-ad06-4887-8060-2636ebb2c69f</Resource><RequestId></RequestId><HostId>cb366d90-8bef-41ce-8917-002140815071</HostId></Error>
    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

![image](https://user-images.githubusercontent.com/29354679/114974687-712d5e80-9eb5-11eb-9ecb-11ba03d9799e.png)

wget susscess

![image](https://user-images.githubusercontent.com/29354679/114975075-30821500-9eb6-11eb-8e99-35ee46c2e438.png)

**Comment by ShockwaveNN** [comment]
Hi

I have no idea what is Minio and I don't think we're officially supporting it

But I don't like this message in wget log - "The name is too long, 295 chars total"
I've never seen message like this so maybe this maybe a reason

But if it's not I need some way to reproduce your problem locally, since I've have no time to invest in learning Minio (as far as I understand it's some kind of extension for k8s)

**Comment by verydemo** [comment]
I used a short link.
