### ISSUE TITLE
Error: bind EADDRINUSE null:8080

### ISSUE THREAD

**Issue by alfabeto2019** [ONLYOFFICE/DocumentServer#1258]
**Do you want to request a *feature* or report a *bug*?bug
**Operating System:ubuntu20
when i ran server/run-develop.py in ubuntu,i got Error: bind EADDRINUSE null:8080.I did some configs in server/Common/config/development-linux.json,but nothing worked.
here is the log:
Install: SpellChecker
------------------------------------------
up to date in 0.586s
root@ubuntu:/home/jenkin/office/onlyofficefdd/server# [2021-05-10T19:05:00.051] [WARN] nodeJS - start cluster with 1 workers
[2021-05-10T19:05:00.107] [WARN] nodeJS - worker 37175 started.
[2021-05-10T19:05:00.122] [WARN] nodeJS - update cluster with 1 workers
[2021-05-10T19:05:00.154] [WARN] nodeJS - worker 37186 started.
[2021-05-10T19:05:00.155] [WARN] nodeJS - update cluster with 1 workers
[2021-05-10T19:05:00.965] [WARN] nodeJS - Express server starting...
[2021-05-10T19:05:00.969] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2021-05-10T19:05:00.973] [INFO] nodeJS - SockJS v0.3.19 bound to "/doc/[0-9-.a-zA-Z_=]*/c"
[2021-05-10T19:05:00.993] [INFO] nodeJS - End updateLicense
[2021-05-10T19:05:01.001] [INFO] nodeJS - End updateLicense
[2021-05-10T19:05:01.012] [WARN] nodeJS - Express server starting...
[2021-05-10T19:05:01.019] [INFO] nodeJS - SockJS v0.3.19 bound to "/doc/[0-9-.a-zA-Z_=]*/c"
[2021-05-10T19:05:01.075] [ERROR] nodeJS - Tue, 11 May 2021 02:05:01 GMT uncaughtException: bind EADDRINUSE null:8080
[2021-05-10T19:05:01.075] [ERROR] nodeJS - Error: bind EADDRINUSE null:8080
    at listenOnMasterHandle (net.js:1347:16)
    at rr (internal/cluster/child.js:126:12)
    at Worker.send (internal/cluster/child.js:93:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:203:15)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2021-05-10T19:05:01.080] [WARN] nodeJS - worker 37175 died (code = 1; signal = null). restart...
[2021-05-10T19:05:01.081] [INFO] nodeJS - endCheckHealth
[2021-05-10T19:05:01.397] [WARN] nodeJS - Express server starting...
[2021-05-10T19:05:01.400] [INFO] nodeJS - SockJS v0.3.19 bound to "/doc/[0-9-.a-zA-Z_=]*/c"
[2021-05-10T19:05:01.442] [ERROR] nodeJS - Tue, 11 May 2021 02:05:01 GMT uncaughtException: bind EADDRINUSE null:8080
[2021-05-10T19:05:01.442] [ERROR] nodeJS - Error: bind EADDRINUSE null:8080
    at listenOnMasterHandle (net.js:1347:16)
    at rr (internal/cluster/child.js:126:12)
    at Worker.send (internal/cluster/child.js:93:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:203:15)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Maybe there is something wrong with development-linux.json about spellchecker part,but how?

**Comment by ShockwaveNN** [comment]
1. I don't think `server/run-develop.py` is ready for usage, it's tools for our internal process, but if found it in some documentation please point me out
2. Maybe there is some other process on 8080 port on your system?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
