### ISSUE TITLE
Command Service--Internal Server Error

### ISSUE THREAD

**Issue by lisiyu55** [ONLYOFFICE/DocumentServer#1400]
Hi,

We are trying to manually trigger a save on a moment of our choosing, and have implemented an API call to the CommandService to achieve this.

It sends the following JSON: { "c":"forcesave","key":"thedocumentkey" }.

However sending this command results in an error with code 3; {key=commandFromServer, error=3}  this is an internal server error in the document server but

a) it does not mention what the problem is
b) there is nothing in the server's error.log or out.log to indicate a problem

What are we doing wrong?

**Comment by lisiyu55** [comment]
> Moved this do main repo. since I think this problem is actual not only in Docker version
> 
> > b) there is nothing in the server's error.log or out.log to indicate a problem
> 
> Are you sure, do you look for all file in `/var/log/onlyoffice/documentserver/`?

Oh，there is error info in /var/log/onlyoffice/documentserver/:
[ERROR] nodeJS - Error commandFromServer: docId = commandFromServer
SyntaxError: Unexpected token < in JSON at position 0.
Does this mean the  server do not  need the token?

**Comment by lisiyu55** [comment]
> Moved this do main repo. since I think this problem is actual not only in Docker version
> 
> > b) there is nothing in the server's error.log or out.log to indicate a problem
> 
> Are you sure, do you look for all file in `/var/log/onlyoffice/documentserver/`?

We found that error log:
[ERROR] nodeJS - Error commandFromServer: docId = commandFromServer
SyntaxError: Unexpected token < in JSON at position 0

We found that  the key in the response is 'commandFromServer' not the key we give it.  {key=commandFromServer, error=3}
What are we doing wrong?

**Comment by ShockwaveNN** [comment]
> SyntaxError: Unexpected token < in JSON at position 0

I think it's usually mean that server expect somewhere a JSON file and receive not a json file

I think I need some more detailed example of commands to reproduce this error, because for now I have no idea that happened

**Comment by lisiyu55** [comment]
Hi,

Thank you for your reply.  The version of onlyoffice we use is 6.3.1. Since we did not make https-related ports, when requesting the onlyoffice command service, the request url was http://ip:port(our document server)/coauthoring/CommandService.ashx.  

1. OS on the server where Docs is installed: Debian GNU/Linux 9
2. The product's installation type: Docker
3. Document Server version: 6.3.1
4. We haven't enabled JWT.

The entire error log is:

request url：http://ip:port(our document server)/coauthoring/CommandService.ashx
request method: post
request body: {c=forcesave, key=2bb73127f37146789c2284042d1f510e-1630380873000}
response: {key=commandFromServer, error=3}
log:
[2021-08-31T03:21:14.511] [ERROR] nodeJS - Error commandFromServer: docId = commandFromServer
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at getRequestParams (/snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0)
    at /snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/DocService/node_modules/co/index.js:65:19)
    at /snapshot/server/build/server/DocService/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/snapshot/server/build/server/DocService/node_modules/co/index.js:50:10)
    at exports.commandFromServer (/snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0)
    at Layer.handle [as handle_request] (/snapshot/server/build/server/DocService/node_modules/express/lib/router/layer.js:95:5)
    at next (/snapshot/server/build/server/DocService/node_modules/express/lib/router/route.js:137:13)
    at /snapshot/server/build/server/DocService/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/snapshot/server/build/server/DocService/node_modules/raw-body/index.js:224:16)
    at done (/snapshot/server/build/server/DocService/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/snapshot/server/build/server/DocService/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:203:15)
[2021-08-31T03:21:14.512] [DEBUG] nodeJS - End commandFromServer: docId = commandFromServer {"key":"commandFromServer","error":3}

**Comment by ShockwaveNN** [comment]
Sorry, I do not fully understand you

Could you show post command using `curl`? I think it's missing some keys like format options
