### ISSUE TITLE
Unable to callback to save Word

### ISSUE THREAD

**Issue by 1205469665** [ONLYOFFICE/DocumentServer#1408]
[36m[2021-09-03T03:05:34.626] [DEBUG] nodeJS -[39m postProcess (id=fdd9a965f92f4)
[36m[2021-09-03T03:05:34.626] [DEBUG] nodeJS -[39m deleteFolderRecursive (id=fdd9a965f92f4)
[36m[2021-09-03T03:06:10.277] [DEBUG] nodeJS -[39m Start Task(id=fdd9a965f92f4_6012)
[36m[2021-09-03T03:06:10.278] [DEBUG] nodeJS -[39m downloadFileFromStorage list fdd9a965f92f4/Editor.bin (id=fdd9a965f92f4)
[36m[2021-09-03T03:06:10.278] [DEBUG] nodeJS -[39m downloadFileFromStorage complete(id=fdd9a965f92f4_6012)
[36m[2021-09-03T03:06:10.279] [DEBUG] nodeJS -[39m downloadFileFromStorage list  (id=fdd9a965f92f4_6012)
[91m[2021-09-03T03:06:10.542] [ERROR] nodeJS -[39m error spawnAsync(id=fdd9a965f92f4)
Error: ../FileConverter/bin/x2t exited with signal: SIGSEGV
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:51:23)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js:0:0)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[91m[2021-09-03T03:06:10.543] [ERROR] nodeJS -[39m stdout (id=fdd9a965f92f4_6012):
[91m[2021-09-03T03:06:10.543] [ERROR] nodeJS -[39m stderr (id=fdd9a965f92f4_6012):Received signal 11 SEGV_MAPERR 00000000000f

==== C stack trace ===============================

 [0xfffef7b16a88]
 [0xfffef94407c0]
 [0xfffef7688920]
 [0xfffef74e1e60]
 [0xfffef74ef9d8]
 [0xfffef74f62e0]
 [0xfffef74f6744]
 [0xfffef74f769c]
 [0xfffef76d2124]
 [0xfffef7577028]
 [0xfffef76db228]
 [0xfffef7322c30]
 [0xfffef72e8e9c]
 [0xfffef72b1494]
 [0xfffef72ab090]
 [0x000000982bc8]
 [0x00000099d4a0]
 [0x0000009a50dc]
 [0x0000009a7d68]
 [0x00000076bb58]
 [0xfffef6edf8e0]
[end of stack trace]

[91m[2021-09-03T03:06:10.543] [ERROR] nodeJS -[39m ExitCode (code=0;signal=SIGSEGV;error:-80;id=fdd9a965f92f4_6012)
[36m[2021-09-03T03:06:10.543] [DEBUG] nodeJS -[39m output (data={"cmd":{"externalChangeInfo":{"user_id":"uid-16306383329471","user_id_original":"uid-1630638332947","user_name":"匿名","change_date":1630638340000},"c":"sfcm","id":"fdd9a965f92f4","userid":"uid-1630638332947","userindex":1,"data":null,"title":"output.","outputformat":2055,"outputpath":"output.","codepage":46,"delimiter":4,"embeddedfonts":false,"status_info":-80,"savekey":"fdd9a965f92f4_6012","forcesave":{"type":0,"time":1630638340000,"index":2},"nobase64":true}};id=fdd9a965f92f4_6012)
[36m[2021-09-03T03:06:10.543] [DEBUG] nodeJS -[39m postProcess (id=fdd9a965f92f4_6012)
[36m[2021-09-03T03:06:10.544] [DEBUG] nodeJS -[39m deleteFolderRecursive (id=fdd9a965f92f4_6012)

**Comment by ShockwaveNN** [comment]
Hi. Please describe your environment - host os, DocumentServer version
