### ISSUE TITLE
Can't insert specific image in document

### ISSUE THREAD

**Issue by ImaCrea** [ONLYOFFICE/DocumentServer#1442]
Hi, here's a weird bug happening sometimes when I work on documents and I try to insert an image.

**What is the current behavior?**
I drag and drop an image into a document, the loader then takes ages till it expires and show a message "Image URL is not correct". Finally the image can't be inserted. Same if going through the image menu > insert from local.

**What is the expected behavior?**
Image should be inserted fine like any other

**Context**
I notice this behavior from time to time with specific image. Most of images get inserted very fine thanks. 

This one case is particularly weird because when I duplicated the image on my local and then tried to upload the exact same copy... then it worked (?!) (I tried before to rename the file and then insert it again but didn't work).

If I retry then with the original picture, it's still buggy and can't be inserted.
I also created a new document and tried again to insert the original image, still buggy.

Browser log is not showing anything particular on my side.

Here are the two images in case you manage to reproduce it (but from this behavior, I have the intuition it's coming from somewhere in the backend)

original
<img width="408" alt="capture jitsi modération original" src="https://user-images.githubusercontent.com/764332/135254118-86539e77-ef48-4e37-a833-e8c806cf61dd.png">

copy
<img width="408" alt="capture jitsi modération copy" src="https://user-images.githubusercontent.com/764332/135254108-e8e9588a-218c-4c83-8e9a-636dc6f67458.png">

**DocumentServer version:**
6.3.1.32

**Operating System:**
OS X 10.14.16

**Browser version:**
FF 92

Thanks for your dear help :)

**Comment by ShockwaveNN** [comment]
> Browser log is not showing anything particular on my side.

I think there is can be some log in back-end log. At `/var/log/onlyoffice/`

**Comment by ImaCrea** [comment]
> > Browser log is not showing anything particular on my side.
> 
> I think there is can be some log in back-end log. At `/var/log/onlyoffice/`

ok we'll try to check on that side

**Comment by pierreozoux** [comment]
Hi,

I got this log on the server /var/log/onlyoffice/documentserver/docservice/out.log-20210926 (with some data redacted)
(Not sure it is the good log as my user is mentionned):
```
[2021-09-29T08:32:25.552] [ERROR] nodeJS - sendServerRequest error: docId = 3970417256;url = https://nuage.liiib.re/apps/onlyoffice/track?doc=redacted;data = {"key":"redacted","status":2,"url":"https://oo-liiib-re.k.liiib.re/cache/files/redacted/output.docx/output.docx?md5=Z-redacted&expires=1632905246&disposition=attachment&filename=output.docx","changesurl":"https://oo-liiib-re.k.liiib.re/cache/files/redacted/changes.zip/changes.zip?md5=redacted&expires=1632905246&disposition=attachment&filename=changes.zip","history":{"serverVersion":"6.3.1","changes":[{"created":"2021-09-29 08:28:06","user":{"id":"pierreok","name":"pierreok"}}]},"users":["pierreok"],"actions":[{"type":0,"userid":"pierreok"}],"lastsave":"2021-09-29T08:28:06.000Z","notmodified":false}
Error: Error response: statusCode:404; headers:{"date":"Wed, 29 Sep 2021 08:32:25 GMT","content-type":"application/json; charset=utf-8","content-length":"29","connection":"keep-alive","x-powered-by":"PHP/7.4.23","expires":"Thu, 19 Nov 1981 08:52:00 GMT","pragma":"no-cache","set-cookie":["oc_sessionPassphrase=redacted; path=/; secure; HttpOnly; SameSite=Lax","redacted; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict"],"cache-control":"no-cache, no-store, must-revalidate","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","x-robots-tag":"none, none","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"1; mode=block","strict-transport-security":"max-age=15724800; includeSubDomains"}; body:
{"message":"Files not found"}
    at Request._callback (/snapshot/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[2021-09-29T08:32:25.554] [WARN] nodeJS - storeForgotten: docId = 3970417256
```
It is the only relevant error I could find in the folder you mentionned.
And didn't find errors in Nextcloud.

Ok, but this issue reminds me of this issue: https://github.com/nextcloud/server/issues/25946

We do use ceph rados gateway as an object store and 2 php workers.
So I coul

**Comment by pierreozoux** [comment]
Ok, I also found these logs at the level of the webserver in front of ONLYOFFICE:
```
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:26:40 +0000] "POST /6.3.1-32/upload/4183578403/3UphOYdp5Q0l_imacrea/8 HTTP/2.0" 408 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:27:43 +0000] "POST /6.3.1-32/upload/4183578403/3UphOYdp5Q0l_imacrea/8 HTTP/2.0" 499 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:28:41 +0000] "POST /6.3.1-32/upload/4183578403/3UphOYdp5Q0l_imacrea/8 HTTP/2.0" 499 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:29:25 +0000] "POST /6.3.1-32/upload/4183578403/3UphOYdp5Q0l_imacrea/8 HTTP/2.0" 499 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:29:56 +0000] "POST /6.3.1-32/upload/4183578403/3UphOYdp5Q0l_imacrea/8 HTTP/2.0" 499 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:32:38 +0000] "POST /6.3.1-32/upload/4153579589/3UphOYdp5Q0l_imacrea/6 HTTP/2.0" 499 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:33:34 +0000] "POST /6.3.1-32/upload/4153579589/3UphOYdp5Q0l_imacrea/6 HTTP/2.0" 499 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:35:05 +0000] "POST /6.3.1-32/upload/4153579589/3UphOYdp5Q0l_imacrea/7 HTTP/2.0" 408 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:43:20 +0000] "POST /6.3.1-32/upload/4153579589/3UphOYdp5Q0l_imacrea/7 HTTP/2.0" 499 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:44:59 +0000] "POST /6.3.1-32/upload/1771002445/3UphOYdp5Q0l_imacrea/1 HTTP/2.0" 408 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:46:10 +0000] "POST /6.3.1-32/upload/1947373729/3UphOYdp5Q0l_imacrea/2 HTTP/2.0" 499 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"
```

**Comment by ShockwaveNN** [comment]
I think those logs

```
[2021-09-29T08:32:25.552] [ERROR] nodeJS - sendServerRequest error: docId = 3970417256;url = https://nuage.liiib.re/apps/onlyoffice/track?doc=redacted;data = {"key":"redacted","status":2,"url":"https://oo-liiib-re.k.liiib.re/cache/files/redacted/output.docx/output.docx?md5=Z-redacted&expires=1632905246&disposition=attachment&filename=output.docx","changesurl":"https://oo-liiib-re.k.liiib.re/cache/files/redacted/changes.zip/changes.zip?md5=redacted&expires=1632905246&disposition=attachment&filename=changes.zip","history":{"serverVersion":"6.3.1","changes":[{"created":"2021-09-29 08:28:06","user":{"id":"pierreok","name":"pierreok"}}]},"users":["pierreok"],"actions":[{"type":0,"userid":"pierreok"}],"lastsave":"2021-09-29T08:28:06.000Z","notmodified":false}
Error: Error response: statusCode:404; headers:{"date":"Wed, 29 Sep 2021 08:32:25 GMT","content-type":"application/json; charset=utf-8","content-length":"29","connection":"keep-alive","x-powered-by":"PHP/7.4.23","expires":"Thu, 19 Nov 1981 08:52:00 GMT","pragma":"no-cache","set-cookie":["oc_sessionPassphrase=redacted; path=/; secure; HttpOnly; SameSite=Lax","redacted; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict"],"cache-control":"no-cache, no-store, must-revalidate","content-security-policy":"default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'","feature-policy":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'","x-robots-tag":"none, none","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-download-options":"noopen","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-xss-protection":"1; mode=block","strict-transport-security":"max-age=15724800; includeSubDomains"}; body:
{"message":"Files not found"}
```
Is not related to this problem. I think its problem with DMS, some file is missing on nextcloud level, have nothing to do with image


---

> nginx-proxy    | oo-liiib-re.k.liiib.re 193.32.126.234 - - [29/Sep/2021:10:27:43 +0000] "POST /6.3.1-32/upload/4183578403/3UphOYdp5Q0l_imacrea/8 HTTP/2.0" 499 0 "https://oo-liiib-re.k.liiib.re/6.3.1-32/web-apps/apps/documenteditor/main/index_loader.html?_dc=6.3.1-32&lang=fr&customer=ONLYOFFICE&frameEditorId=iframeEditor&compact=true&parentOrigin=https://nuage.liiib.re" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:92.0) Gecko/20100101 Firefox/92.0"


This maybe more about this problem, But it's just plain 499 error without any additional information. Not sure if we can do something out it.
Only way I can diagnose this problem - check if this occurs with your specific setup of proxy, because this lost image problem - is first time I've ever heard of this, so this may be related to nginx configure


--- 

And my third advice - I see this problem is rather complicated, so I think if you got active license - it's better to contact support and\or maybe with access to servers this problem can be localized. Because as I'm always say - github it's not a support forum, it's place to report exact errors with clear repdocucable steps

**Comment by pierreozoux** [comment]
Thanks for your insight, as I said, we'll collect more datapoints next time it happens.

 > Because as I'm always say - github it's not a support forum, it's place to report exact errors with clear repdocucable steps
 
 I understand where you're coming from. I totally get it. There are various reasons why we can't take supports, but here is probably not the place to discuss this. The way I see it is that we (The Free and Open Source community) help you identify early bugs in your product for your paying customers. (I'd love to contribute more than bug report, but I'm more a sysadmin than a dev, actually we could help [here](https://github.com/ONLYOFFICE/Kubernetes-Docs) :) )
 
 I propose we close this issue, and keep an eye on it, and if it re happens, we reopen it.
 
 I also really like to document bugs, the way we discover them, and the way we find the solution, because it usually helps me a lot to see other people reports to fix my own bugs or misconfiguration.

**Comment by ShockwaveNN** [comment]
Thank you for your understanding

> I propose we close this issue, and keep an eye on it, and if it re happens, we reopen it.

I think we can leave this issue open for a month and if there is no feedback from you - I'll close it manually

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
