### ISSUE TITLE
Missing item in `[Content_Types].xml` for `customXml/itemProps2.xml` after editing file

### ISSUE THREAD

**Issue by vblz** [ONLYOFFICE/DocumentServer#1443]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
After editing a docx file in OnlyOffice DocumentServer the file becomes invalid.
In the file there is missing item in `[Content_Types].xml` for `customXml/itemProps2.xml` what violates OOXML standard.

There is the official SDK for OpenXML. Trying open a corrupted doc using this SDK leads to the error:
```
Unhandled exception. DocumentFormat.OpenXml.Packaging.OpenXmlPackageException: The document cannot be opened because there is an invalid part with an unexpected content type. 
[Part Uri=/customXml/itemProps2.xml], 
[Content Type=application/xml], 
[Expected Content Type=application/vnd.openxmlformats-officedocument.customXmlProperties+xml].
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load(Package _package)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage..ctor(PackageLoader& loader, OpenSettings settings)
   at DocumentFormat.OpenXml.Packaging.WordprocessingDocument..ctor(PackageLoader& loader, OpenSettings settings)
   at DocumentFormat.OpenXml.Packaging.WordprocessingDocument.Open(String path, Boolean isEditable, OpenSettings openSettings)
   at DocumentFormat.OpenXml.Packaging.WordprocessingDocument.Open(String path, Boolean isEditable)
   at docx.Program.Main(String[] args) in Program.cs:line 12
```

Example file: [OO_example_file.docx](https://github.com/ONLYOFFICE/DocumentServer/files/7251288/OO_example_file.docx)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
No certain way to reproduce, we just keep getting broken documents after editing in OnlyOffice.

**What is the expected behavior?**
No violations of OOXML standard

**Did this work in previous versions of DocumentServer?**
We hadn't met that issue before updated to 6.3.2 from 6.2

**DocumentServer version:**
6.3.2

**Operating System:**
Docker installation of OnlyOffice DocumentServer

**Browser version:**
Firefox 90.0 (64-bit)

**Comment by ShockwaveNN** [comment]
Could you try to update to v6.4.1 and see if problem actual

As far as I remember we change a lot of code for `customXml/itemProps.xml` in v6.4.0

Possibly related
https://github.com/ONLYOFFICE/DocumentServer/issues/1318

**Comment by vblz** [comment]
We will try. Let me get it straight: updating to 6.4.0 should fix files after re-saving them in the new version of Document Server? 
But also let me focus that the problem is only with `itemProps2.xml` file, we have never met this issue with `itemProps1.xml`.

**Comment by ShockwaveNN** [comment]
>  updating to 6.4.0 should fix files after re-saving them in the new version of Document Server

Only if the original, correct file is saved. If file is broken - it will not recover it I think

> we have never met this issue with itemProps1.xml.

As far as I remember there was problem in index order, but I'm not sure as I'm not sure that your problem is same is issue I mention. But upgrading may improve you situation and help us figure out if your bug is currently actual

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by amaigaki** [comment]
Okay, will check and let you know.
