### ISSUE TITLE
High CPU usage bec of Error: Configuration property "services.CoAuthoring.server.assemblyFormatAsOrigin" is not defined

### ISSUE THREAD

**Issue by jcn50** [ONLYOFFICE/DocumentServer#1472]
**I am having a High CPU usage with many process like those:**
`15654 ds        20   0  559368  45932  24020 R   6.6   2.2   0:00.20 /var/www/onlyoffice/documentserver/server/FileConverter/converter  /snapshot/server/build/server/FileConverter/sources/convertermaster.js`
`1132 ds        20   0  593420  46936  24256 S   0.3   2.3   0:09.79 /var/www/onlyoffice/documentserver/server/FileConverter/converter`
`1127 ds        20   0  579536  34196  24160 S   0.0   1.7   0:00.16 /var/www/onlyoffice/documentserver/server/Metrics/metrics ./config/config.js`

**And the first process comes back with another ID again & again forever.**

**After digging I have many errors like those:**

`cat /var/log/onlyoffice/documentserver/converter/err.log`
`Error: Configuration property "services.CoAuthoring.server.assemblyFormatAsOrigin" is not defined`
`    at Config.get (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:203:11)`
`    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/canvasservice.js:0:0)`
`    at Module._compile (pkg/prelude/bootstrap.js:1320:22)`
`    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)`
`    at Module.load (internal/modules/cjs/loader.js:651:32)`
`    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)`
`    at Function.Module._load (internal/modules/cjs/loader.js:583:3)`
`    at Module.require (internal/modules/cjs/loader.js:690:17)`
`    at Module.require (pkg/prelude/bootstrap.js:1225:31)`
`    at require (internal/modules/cjs/helpers.js:25:18)`
`    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/wopiClient.js:0:0)`
`    at Module._compile (pkg/prelude/bootstrap.js:1320:22)`           
`    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)`
`    at Module.load (internal/modules/cjs/loader.js:651:32)`                                                                    
`    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)`
`    at Function.Module._load (internal/modules/cjs/loader.js:583:3)`
`pkg/prelude/bootstrap.js:1244`
`      throw error;`                                                                                        
`      ^`

**Finally: I have never edited any configuration file, and running the latest version.**

**Comment by jcn50** [comment]
> Are you run upgrade of DocumentServer recently?

I upgrade the server using YunoHost each time there is an update.

> `/etc/onlyoffice/documentserver/default.json` is missing this line (and probably some others) 
You are correct, it was also missing the entire `wopi` definitions, however I can see some private/public keys in the sample you have sent me. I have no idea on how to generate those?
Is there a way to regenerate `/etc/onlyoffice/documentserver/default.json` with my current installation?

**Comment by ShockwaveNN** [comment]
> I upgrade the server using YunoHost each time there is an update.

I never heard about that, so I don't think I can comment something about this hosting system

> Is there a way to regenerate /etc/onlyoffice/documentserver/default.json with my current installation?

I think you should just replace file (making backup of your broken file just in case) from github - and that's good to go, since `default.json` is not meant to be changed - all changes and personal configuration placed in `local.json` file in same dir

**Comment by jcn50** [comment]
Thanks for the tip! Issue is closed/

**Comment by nahoj** [comment]
Thank you for the error report and fix. I had a similar issue with a different property and fixed it in a similar way, see https://github.com/ONLYOFFICE/DocumentServer/issues/2082#issuecomment-1564622445.

**Comment by jcn50** [comment]
Thanks nahoj, the problem was the same again today so I had to run the following command to fix the issue
```
\cp /etc/onlyoffice/documentserver/default.json.dpkg-dist /etc/onlyoffice/documentserver/default.json && supervisorctl restart all
```
