### ISSUE TITLE
Unable to callback to save Word,I guess it's fileConvert error

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#1561]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
```
[36m[2021-12-17T09:21:46.799] [DEBUG] nodeJS -[39m Start Task(id=766103333478464-V1)
[36m[2021-12-17T09:21:46.839] [DEBUG] nodeJS -[39m downloadFile complete filesize=11093 (id=766103333478464-V1)
[36m[2021-12-17T09:21:46.884] [DEBUG] nodeJS -[39m stdout (id=766103333478464-V1):
[36m[2021-12-17T09:21:46.884] [DEBUG] nodeJS -[39m stderr (id=766103333478464-V1):
[36m[2021-12-17T09:21:46.885] [DEBUG] nodeJS -[39m ExitCode (code=0;signal=null;error:0;id=766103333478464-V1)
[36m[2021-12-17T09:21:46.886] [DEBUG] nodeJS -[39m processUploadToStorage complete(id=766103333478464-V1)
[36m[2021-12-17T09:21:46.886] [DEBUG] nodeJS -[39m output (data={"cmd":{"withAuthorization":true,"wopiParams":null,"c":"open","id":"766103333478464-V1","userid":"fengzg","format":"docx","url":"http://122.228.13.23:8081/files/secure/20211217/8bee33a09c7058c40725a2114e669f1a/%E6%B5%8B%E8%AF%95.docx","title":"测试.docx","outputformat":8192,"outputpath":"Editor.bin","embeddedfonts":false,"status_info":0,"lcid":2052,"nobase64":true}};id=766103333478464-V1)
[36m[2021-12-17T09:21:46.886] [DEBUG] nodeJS -[39m postProcess (id=766103333478464-V1)
[36m[2021-12-17T09:21:46.887] [DEBUG] nodeJS -[39m deleteFolderRecursive (id=766103333478464-V1)
[36m[2021-12-17T09:22:15.590] [DEBUG] nodeJS -[39m Start Task(id=764567885742144-V1)
[36m[2021-12-17T09:22:15.632] [DEBUG] nodeJS -[39m downloadFile complete filesize=125163 (id=764567885742144-V1)
[36m[2021-12-17T09:22:15.702] [DEBUG] nodeJS -[39m stdout (id=764567885742144-V1):
[36m[2021-12-17T09:22:15.703] [DEBUG] nodeJS -[39m stderr (id=764567885742144-V1):
[36m[2021-12-17T09:22:15.703] [DEBUG] nodeJS -[39m ExitCode (code=0;signal=null;error:0;id=764567885742144-V1)
[36m[2021-12-17T09:22:15.705] [DEBUG] nodeJS -[39m processUploadToStorage complete(id=764567885742144-V1)
[36m[2021-12-17T09:22:15.705] [DEBUG] nodeJS -[39m output (data={"cmd":{"withAuthorization":true,"wopiParams":null,"c":"open","id":"764567885742144-V1","userid":"fengzg","format":"docx","url":"http://122.228.13.23:8081/files/export/20211215/b61708d0bc2046b2f12d0135db980ef8/%E6%B8%A9%E5%B7%9E%E5%B8%82%E6%B4%9E%E5%A4%B4%E5%8C%BA%E7%8E%AF%E5%A2%83%E7%9B%91%E6%B5%8B%E7%AB%992021%E5%B9%B411%E6%9C%88%E5%9C%B0%E8%A1%A8%E6%B0%B4%E9%80%81%E6%A0%B7%E6%A3%80%E6%B5%8B%EF%BC%88%E6%B5%AE%E6%B8%B8%E6%A4%8D%E7%89%A9%EF%BC%89(WS21016).docx","title":"温州市洞头区环境监测站2021年11月地表水送样检测（浮游植物）(WS21016).docx","outputformat":8192,"outputpath":"Editor.bin","embeddedfonts":false,"status_info":0,"lcid":2052,"nobase64":true}};id=764567885742144-V1)
[36m[2021-12-17T09:22:15.706] [DEBUG] nodeJS -[39m postProcess (id=764567885742144-V1)
[36m[2021-12-17T09:22:15.707] [DEBUG] nodeJS -[39m deleteFolderRecursive (id=764567885742144-V1)
[36m[2021-12-17T09:22:36.248] [DEBUG] nodeJS -[39m Start Task(id=766103333478464-V1_1053)
[36m[2021-12-17T09:22:36.249] [DEBUG] nodeJS -[39m downloadFileFromStorage list 766103333478464-V1/Editor.bin (id=766103333478464-V1)
[36m[2021-12-17T09:22:36.250] [DEBUG] nodeJS -[39m downloadFileFromStorage complete(id=766103333478464-V1_1053)
[36m[2021-12-17T09:22:36.250] [DEBUG] nodeJS -[39m downloadFileFromStorage list  (id=766103333478464-V1_1053)
[91m[2021-12-17T09:22:36.606] [ERROR] nodeJS -[39m error spawnAsync(id=766103333478464-V1)
Error: ../FileConverter/bin/x2t exited with signal: SIGSEGV
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:51:23)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js:0:0)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[91m[2021-12-17T09:22:36.607] [ERROR] nodeJS -[39m stdout (id=766103333478464-V1_1053):
[91m[2021-12-17T09:22:36.607] [ERROR] nodeJS -[39m stderr (id=766103333478464-V1_1053):Received signal 11 SEGV_MAPERR 00000000000f

==== C stack trace ===============================

 [0xfffc7ce95040]
 [0xfffc7e8a07c0]
 [0xfffc7caacf64]
 [0xfffc7c90b3ac]
 [0xfffc7c908fdc]
 [0xfffc7c907960]
 [0xfffc7c906eb0]
 [0xfffc7c908d20]
 [0xfffc7cae4d24]
 [0xfffc7c995524]
 [0xfffc7caec6d0]
 [0xfffc7c74e844]
 [0xfffc7c707d68]
 [0xfffc7c6db208]
 [0xfffc7c6d3aec]
 [0xaaaace3193e0]
 [0xaaaace3381a0]
 [0xaaaace340798]
 [0xaaaace343a00]
 [0xaaaace0fd950]
 [0xfffc7c384090]
 [0xaaaace3171b8]
[end of stack trace]
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Start editing word documents
2. Modify the content of the word document
3. Click the save button or ctrl + S to trigger the logic of the forced save callback

**What is the expected behavior?**
The logic of the callback interface is normal

Can you give a solution and troubleshooting direction based on the log output of the fileConvert service, or it would be great if you know the problem?

**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
The ARM version compiled based on the code of version 6.4.2, got two executable services, docservice and fileConvert, and then based on the writing method of Dockerfile (https://github.com/ONLYOFFICE/Docker-DocumentServer) to create an ARM architecture that supports Running docker image
**Operating System:**
win10
**Browser version:**

**Comment by ShockwaveNN** [comment]
> The ARM version compiled based on the code of version 6.4.2

We do not support ARM in any way sorry and I thinks it's same problem we [noticed several years ago](
https://github.com/ONLYOFFICE/DocumentServer/issues/152#issuecomment-322387775) while trying to debug ARM version and since those times our dev team still never figure out the reason

So I don't think that we can do anything until time we officially support ARM

**Comment by nobt854** [comment]
So can you give a troubleshooting suggestion from the perspective of these JS errors and other errors? I am really anxious because of this problem, thank you very much

**Comment by ShockwaveNN** [comment]
> perspective of these JS errors

Those are not JS errors, but error in `x2t` which is written in C++ and not portable, so there may be any troubles on ARM

>  am really anxious because of this problem

My advice - do not use system we do not support. We cannot provide full help if we do not support it, it's the definition of `support`. I'm sorry but it's better to use x86 until we officially fix all problems with arm

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
