### ISSUE TITLE
OnlyOffice Docs not Opening

### ISSUE THREAD

**Issue by SushantRathore-Admin** [ONLYOFFICE/DocumentServer#1670]

**Comment by ShockwaveNN** [comment]
Hi, describe in more details that is 
> docs are not opening.

Is there any error in interface and what are errors in `/var/log/onlyoffice`

Usually enabling SELinux cause trouble, not disabling it

**Comment by SushantRathore-Admin** [comment]
Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.0.0.132)

> Hi, describe in more details that is
> 
> > docs are not opening.
> 
> Is there any error in interface and what are errors in `/var/log/onlyoffice`
> 
> Usually enabling SELinux cause trouble, not disabling it

Hi,

Thanks for reply , Now i m trying to connect onlyoffice with nextcloud facing this issues.


Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.0.0.132)
tail -f /var/log/onlyoffice/documentserver/converter/out.log
Here are logs 👍 
[2022-03-05T03:44:59.661] [ERROR] nodeJS - error downloadFile:url=https://office.exadime.com/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.NDLWYzgkeldFUGRG7ez_vV3cZpIzXR0CqIOJWHNYWQU;attempt=3;code:null;connect:null;(id=conv_check_1613955113_docx)
Error: Error response: statusCode:404; headers:{"server":"nginx","date":"Sat, 05 Mar 2022 08:44:59 GMT","content-type":"text/html; charset=utf-8","transfer-encoding":"chunked","connection":"keep-alive","vary":"Accept-Encoding","x-powered-by":"Express","content-security-policy":"default-src 'none'","x-content-type-options":"nosniff","content-encoding":"gzip"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:204:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)


Thanks

**Comment by ShockwaveNN** [comment]
Do you use some kind proxy between DocumentServer and Nextcloud?

I think this error mean something wrong in connection between those services

Could you try DocumentServer integrated example (instruction how to turn on located at http://docserverurl/welcome) and see if DocumentServer works fine by itself and if so - problem in network layer somewhere

**Comment by SushantRathore-Admin** [comment]
> example

Thanks for you quick response, 

I tried   as you suggested 

**When i m using https://office.exadime.com/welcome getting error 404 as given in below.**

Error when trying to connect (Client error: `GET https://office.exadime.com/welcome/healthcheck` resulted in a `404 Not Found` response:

404 Not Found

404 Not Found
nginx

**When i m trying https://office.exadime.com/example getting healthcheck` resulted in a `404 Not Found as given in below.**

Error when trying to connect (Client error: `GET https://office.exadime.com/example/healthcheck` resulted in a `404 Not Found` response:

**Comment by ShockwaveNN** [comment]
If you get 404 on `welcome` seems that Nginx is not correctly setup

Do you not forget the last step of [this instruction](https://helpcenter.onlyoffice.com/installation/docs-enterprise-install-centos.aspx)

> bash documentserver-configure.sh

If not - you didn't answer is there any proxy? And if there is - I think this is a problem

Alternatively you can try to use docker version - it's much easier to setup

**Comment by SushantRathore-Admin** [comment]
> If you get 404 on `welcome` seems that Nginx is not correctly setup
> 
> Do you not forget the last step of [this instruction](https://helpcenter.onlyoffice.com/installation/docs-enterprise-install-centos.aspx)
> 
> > bash documentserver-configure.sh
> 
> If not - you didn't answer is there any proxy? And if there is - I think this is a problem
> 
> Alternatively you can try to use docker version - it's much easier to setup

I used bash documentserver-configure.sh command.

If not - you didn't answer is there any proxy? And if there is - I think this is a problem  --> **I not sure about it but mainly i used installations doc [https://helpcenter.onlyoffice.com/installation/docs-enterprise-install-centos.aspx](url) as they mentions i did all these steps one by one., ever onlyoffice server working fine but facing issues while connecting from nextcloud.**

**Comment by ShockwaveNN** [comment]
I do not understand

You mention that server is working fine but you get 404 on welcome

This is not right

> When i m using https://office.exadime.com/welcome get error 404 as given in below.
> Error when trying to connect (Client error: GET https://office.exadime.com/welcome/healthcheck resulted in a 404 Not Found response:

Why is there `welcome/healcheck` in URL?
It should be https://office.exadime.com/healthcheck

And same for `https://office.exadime.com/example/healthcheck`

Also please try to format your responses correctly, it is very hard to read then it is just a combination of your and my words

**Comment by SushantRathore-Admin** [comment]
> https://office.exadime.com/healthcheck

If i m trying to hit https://office.exadime.com/healthcheck getting output  true so its working fine.

But when i m trying to hit [(https://office.exadime.com/](url) its redirecting to [(https://office.exadime.com/welcome](url) then onlyofffice welcome pages are opening.

**Comment by ShockwaveNN** [comment]
> But when i m trying to hit [(https://office.exadime.com/](https://github.com/ONLYOFFICE/DocumentServer/issues/url) its redirecting to [(https://office.exadime.com/welcome](https://github.com/ONLYOFFICE/DocumentServer/issues/url) then onlyofffice welcome pages are opening.

Yes this is right behavior

**Comment by SushantRathore-Admin** [comment]
> > But when i m trying to hit [(https://office.exadime.com/](https://github.com/ONLYOFFICE/DocumentServer/issues/url) its redirecting to [(https://office.exadime.com/welcome](https://github.com/ONLYOFFICE/DocumentServer/issues/url) then onlyofffice welcome pages are opening.
> 
> Yes this is right behavior

Ok if this is right behaver then what i need to do for connecting it from nextcloud. 
**Because when i m hitting my domain from nextcloud its searching  healthcheck file  inside  domain-name/welcome/healthcheck.** 

**Please check Nginx logs here -** 

2022/03/05 03:43:05 [error] 1221#1221: *121 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.1.226, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://[::1]:8000/favicon.ico", host: "office.exadime.com", referrer: "https://office.exadime.com/example/editor?fileName=new.docx"
2022/03/05 03:43:08 [error] 1221#1221: *121 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.1.226, server: , request: "GET /example/ HTTP/1.1", upstream: "http://[::1]:3000/", host: "office.exadime.com", referrer: "https://office.exadime.com/welcome/"
2022/03/05 03:43:08 [error] 1221#1221: *121 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.1.226, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://[::1]:8000/favicon.ico", host: "office.exadime.com", referrer: "https://office.exadime.com/example/"
2022/03/05 03:43:17 [error] 1221#1221: *121 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.1.226, server: , request: "GET /example/ HTTP/1.1", upstream: "http://[::1]:3000/", host: "office.exadime.com", referrer: "https://office.exadime.com/welcome/"
2022/03/05 03:43:17 [error] 1221#1221: *121 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.1.226, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://[::1]:8000/favicon.ico", host: "office.exadime.com", referrer: "https://office.exadime.com/example/"
2022/03/05 07:21:21 [error] 1221#1221: *502 open() "/var/www/onlyoffice/documentserver-example/welcome/healthcheck" failed (2: No such file or directory), client: 10.0.0.40, server: , request: "GET /welcome/healthcheck HTTP/1.1", host: "office.exadime.com"

**Comment by ShockwaveNN** [comment]
Could you show nextcloud connector settings page?

**Comment by SushantRathore-Admin** [comment]
> Could you show nextcloud connector settings page?
Nextcloud connector settings page, is this one or anything else ? 
![Screenshot 2022-03-05 at 19-28-34 Settings - Nextcloud](https://user-images.githubusercontent.com/64971519/156886743-886a1416-db3d-4c8f-8e71-15e32571f30d.png)

**Comment by ShockwaveNN** [comment]
I'm not very good at nextcloud, but seems right for 

One last question from me

When you've opening `https://office.exadime.com/example/` URL - opening documents and saving them via integrated example is fine?
And only troubles you get - with nextcloud integration

Am I right?

**Comment by SushantRathore-Admin** [comment]
> I'm not very good at nextcloud, but seems right for
> 
> One last question from me
> 
> When you've opening `https://office.exadime.com/example/` URL - opening documents and saving them via integrated example is fine? And only troubles you get - with nextcloud integration
> 
> Am I right?

yes You are right, only facing issues while doing integration with nextcloud. if i will open https://office.exadime.com/example/ that is working file can edit doc write as well.

**Comment by ShockwaveNN** [comment]
In that case I'll redirect this issue to people who work with nextcloud
