### ISSUE TITLE
Converter Segfault (SIGSEGV) when opening some documents 

### ISSUE THREAD

**Issue by MiningPickaxe** [ONLYOFFICE/DocumentServer#1687]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When opening specific documents it loads for a while, after that it exits with the error message that the document couldn't be opened.
In the converter out.log I see the following:
```
[2022-03-16T15:24:12.204] [ERROR] nodeJS - error spawnAsync(id=589293822)
Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGSEGV
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2022-03-16T15:24:12.209] [ERROR] nodeJS - stdout (id=589293822):
[2022-03-16T15:24:12.209] [ERROR] nodeJS - stderr (id=589293822):
[2022-03-16T15:24:12.209] [ERROR] nodeJS - ExitCode (code=0;signal=SIGSEGV;error:-80;id=589293822)
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[13 bErgänzung Alles richtig--edited (2021_03_14 20_29_12 UTC).docx](https://github.com/ONLYOFFICE/Docker-DocumentServer/files/8264777/13.bErganzung.Alles.richtig--edited.2021_03_14.20_29_12.UTC.docx)
Attached a file where this happens. I'm using the integration into nextcloud, but this also crashes my local install of the desktop editors. Seems like an issue with the converter.

**What is the expected behavior?**
The document should be opened

**Did this work in previous versions of DocumentServer?**
Didn't work in 7.0 either, cannot comment on earlier versions as I didn't have the files I want to access now back then.
**DocumentServer Docker tag:** latest (7.0.1.37) after I upgraded from 7.0

**Host Operating System:** Debian 11 on Intel Skylake

**Comment by dreua** [comment]
> Hi @dreua
> 
> Thank you for your issue I can confirm - this is a bug. Issue 56098 in our private issue tracker.

Thats not my issue, I merely commented that the file also crashed with my Libreoffice, which may suggest that the file is borken or using some features that Libreoffice / Onlyoffice can't deal with.

**Comment by l8556** [comment]
Sorry, I got confused.

MS Office opens the file correctly, so the file is probably correct, but we don't know for sure yet.

**Comment by solracsf** [comment]
Same issue here with latest `onlyoffice/documentserver` container:

```
[2023-02-02T14:29:31.929] [ERROR] [localhost] [1041508599] [oc6xz1h8l8n2_username] nodeJS - error spawnAsync Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGSEGV
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:40:23)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnProcess (/snapshot/server/build/server/FileConverter/sources/converter.js)
    at spawnProcess.next (<anonymous>)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2023-02-02T14:29:31.931] [ERROR] [localhost] [1041508599] [oc6xz1h8l8n2_username] nodeJS - stdout:
[2023-02-02T14:29:31.931] [ERROR] [localhost] [1041508599] [oc6xz1h8l8n2_username] nodeJS - stderr:
[2023-02-02T14:29:31.931] [ERROR] [localhost] [1041508599] [oc6xz1h8l8n2_username] nodeJS - ExitCode (code=0;signal=SIGSEGV;error:-80)
```

**Comment by askonev** [comment]
@solracsf hi
I can ask for a document to verify it. Unless, of course, it contains confidential information
