### ISSUE TITLE
Linked Documents do not open

### ISSUE THREAD

**Issue by cablesky** [ONLYOFFICE/DocumentServer#1760]
When documents are shared f.e. via nextcloud talk or in collectives, clicking on them causes a frame to appear on screen but the document does not load.

Happens when:

sharing files/links via nextcloud talk

Error in Chrome-Developer Tool:

> Viewer.vue:443 TypeError: Cannot read properties of undefined (reading 'theme')
>     at Viewer.vue:386:1
>     at c (dist.js:1:80785)
>     at Generator._invoke (dist.js:1:80573)
>     at Generator.next (dist.js:1:81214)
>     at Wa (Download.vue?b226:19:33)
>     at a (Download.vue?b226:19:33)

**Comment by ShockwaveNN** [comment]
This may be, but error is coming from nextcloud(? or some other) code, so I'll move this issue into proper repo, since this error is not from DocumentServer
