### ISSUE TITLE
Real time updates of collaborative editing broken since 7.1.0

### ISSUE THREAD

**Issue by JMoVS** [ONLYOFFICE/DocumentServer#1774]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Eversince 7.1 in my nextcloud, real time updates don't work - I only see a red coloured "someone is making changes here" (and yes, I was in quick mode in Onlyoffice word document

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Have the same document open by two users

**What is the expected behavior?**
similar to 7.0.1 just working

**Did this work in previous versions of DocumentServer?**
yes

**DocumentServer version:**
7.1.0

**Operating System:**
DocumentServer Docker base image

**Browser version:**

**Comment by ShockwaveNN** [comment]
Hi

> I only see a red coloured "someone is making changes here"

Not sure that happened, maybe someone really in that document, maybe you in same or another browser? Is there any active users shown in control of current user or in chat?

If not - is there any strange errors in server logs?

I think I see those issue for the first time ever, so not sure that may be the reason

**Comment by JMoVS** [comment]
the problem is that it looks like that fast collaboration doesn't work anymore and instead only "formal" works.

I do see some strange errors in the log that I can't make much sense of:

```
document-server | 2022-06-19T11:17:16.183537104Z ==> /var/log/onlyoffice/documentserver/converter/err.log <==
document-server | 2022-06-19T11:17:16.183596066Z pkg/prelude/bootstrap.js:1876
document-server | 2022-06-19T11:17:16.183610683Z       throw error;
document-server | 2022-06-19T11:17:16.183620151Z       ^
document-server | 2022-06-19T11:17:16.183629098Z 
document-server | 2022-06-19T11:17:16.183640028Z Error: Cannot find module './DocsCoServer'
document-server | 2022-06-19T11:17:16.183652812Z 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
document-server | 2022-06-19T11:17:16.183664895Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:634:15)
document-server | 2022-06-19T11:17:16.183674864Z     at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
document-server | 2022-06-19T11:17:16.183685363Z     at Function.Module._load (internal/modules/cjs/loader.js:560:25)
document-server | 2022-06-19T11:17:16.183696304Z     at Module.require (internal/modules/cjs/loader.js:690:17)
document-server | 2022-06-19T11:17:16.183706333Z     at Module.require (pkg/prelude/bootstrap.js:1855:31)
document-server | 2022-06-19T11:17:16.183717624Z     at require (internal/modules/cjs/helpers.js:25:18)
document-server | 2022-06-19T11:17:16.183727863Z     at Object.<anonymous> (/snapshot/server/DocService/sources/canvasservice.js:0:0)
document-server | 2022-06-19T11:17:16.183739314Z     at Module._compile (pkg/prelude/bootstrap.js:1930:22)
document-server | 2022-06-19T11:17:16.183748962Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
document-server | 2022-06-19T11:17:16.183759162Z     at Module.load (internal/modules/cjs/loader.js:651:32)
document-server | 2022-06-19T11:17:16.190653961Z 
document-server | 2022-06-19T11:17:16.190756012Z ==> /var/log/onlyoffice/documentserver/converter/out.log <==
document-server | 2022-06-19T11:17:16.190767033Z [2022-06-19T11:17:16.189] [WARN] nodeJS - worker 19739 died (code = 1; signal = null).
document-server | 2022-06-19T11:17:16.194583670Z [2022-06-19T11:17:16.194] [WARN] nodeJS - worker 19745 started.
```

**Comment by ShockwaveNN** [comment]
Hm, this is strange

Do you compile it manually? Because I can't find any reason how this error can happen if you using our official

> DocumentServer Docker base image

as you mention in original post

**Comment by JMoVS** [comment]
yes, I'm compiling manually - previously compiling myself worked (up to 7.0.1), now it throws this error - I could provide the Dockerfile if that helps
