### ISSUE TITLE
Error while converting pptx File to PDF over Conversion API

### ISSUE THREAD

**Issue by albanhasa** [ONLYOFFICE/DocumentServer#1818]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I want to convert a pptx file with size around 15MB ( uncompressed ~ 26MB) over the convertion api. I get error response with error code -2.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

One of the slides contains a .emf file, and from tmp../results folder looks like the convert process is hanging there:

```
root@76234ca28616:/tmp# ls -lhrt /tmp/ASC_CONVERT12267-skynyf.so1y/result/ascRfavxm/pptt_unpacked/media/
total 9.1M
-rw-r--r-- 1 ds ds 1.9M Jul  7 13:22 image7.jpg
-rw-r--r-- 1 ds ds  41K Jul  7 13:22 image6.png
-rw-r--r-- 1 ds ds 4.1K Jul  7 13:22 image5.jpg
-rw-r--r-- 1 ds ds  34K Jul  7 13:22 image4.jpg
-rw-r--r-- 1 ds ds 8.1K Jul  7 13:22 image3.png
-rw-r--r-- 1 ds ds  20K Jul  7 13:22 image2.jpg
-rw-r--r-- 1 ds ds 5.1K Jul  7 13:22 image1.jpg
-rw-r--r-- 1 ds ds 7.1M Jul  7 13:22 display2image8.emf
```

Error from docker container:
```
[2022-07-07T09:48:35.288] [ERROR] nodeJS - error spawnAsync(id=conv_4bd1c7a7-3f33-418b-a3a7-ecf549bbf7dapdf_pdf)
Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGTERM
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2022-07-07T09:48:35.288] [ERROR] nodeJS - stdout (id=conv_4bd1c7a7-3f33-418b-a3a7-ecf549bbf7dapdf_pdf):
[2022-07-07T09:48:35.288] [ERROR] nodeJS - stderr (id=conv_4bd1c7a7-3f33-418b-a3a7-ecf549bbf7dapdf_pdf):
[2022-07-07T09:48:35.288] [ERROR] nodeJS - ExitCode (code=0;signal=SIGTERM;error:-80;id=conv_4bd1c7a7-3f33-418b-a3a7-ecf549bbf7dapdf_pdf)
```

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**

**Operating System:**
Issue happens in WSL2 on Windows 10 and Centos8 Stream (using docker image onlyoffice/documentserver)
**Browser version:**

**Comment by ShockwaveNN** [comment]
Ok, I'll wait for file because without it I cannot file a bug

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
