### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Vn')

### ISSUE THREAD

**Issue by bipana50** [ONLYOFFICE/DocumentServer#1838]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I try to load the version history, error occurs and it keeps showing loading changes loader
In my docker logs
```==> /var/log/onlyoffice/documentserver/docservice/out.log <==
[2022-07-27T05:22:41.921] [ERROR] nodeJS - changesError: docId = 62e0a7538a2d58510a81e525 Error: Uncaught TypeError: Cannot read properties of undefined (reading 'Vn') Script: http://localhost/7.0.1-37/sdkjs/word/sdk-all.js Line: 7440:339 userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 platform: Linux x86_64 isLoadFullApi: true isDocumentLoadComplete: false StackTrace: TypeError: Cannot read properties of undefined (reading 'Vn')
    at dv.Eh (http://localhost/7.0.1-37/sdkjs/word/sdk-all.js:7440:339)
    at yd.Jxe (http://localhost/7.0.1-37/sdkjs/word/sdk-all-min.js:827:306)
    at LK.ee.njd (http://localhost/7.0.1-37/sdkjs/word/sdk-all-min.js:830:315)
    at LK.ee.L_b (http://localhost/7.0.1-37/sdkjs/word/sdk-all-min.js:830:17)
    at Nb.K0b (http://localhost/7.0.1-37/sdkjs/word/sdk-all-min.js:1193:50)
    at Nb.V7d (http://localhost/7.0.1-37/sdkjs/word/sdk-all-min.js:1191:406)
    at Object.EFa (http://localhost/7.0.1-37/sdkjs/word/sdk-all.js:4601:229)
    at Nb.QCe (http://localhost/7.0.1-37/sdkjs/word/sdk-all-min.js:1188:432)
    at e.PQb (http://localhost/7.0.1-37/sdkjs/word/sdk-all.js:4596:297)
    at e.PQb (http://localhost/7.0.1-37/sdkjs/word/sdk-all.js:4597:140)
[2022-07-27T05:22:44.085] [WARN] nodeJS - sendServerRequest returned an error: docId = 62e0c99f051f644ca3cf673f; data = {"error":1}
[2022-07-27T05:22:44.091] [WARN] nodeJS - storeForgotten: docId = 62e0c99f051f644ca3cf673f
```
Here, localhost is onlyoffice documentserver

behavior in my app, [screenshot](https://ibb.co/dKVckCS)

**What is the expected behavior?**
document version file should load without error

**DocumentServer version:**
Document Editor version 7.0.1

**Operating System:**
Linux/Ubuntu 20.04

**Comment by ShockwaveNN** [comment]
Hi, sorry to hear you got error, I got several ideas:

1. Update to the latest stable DocumentServer v7.1.1. This problem may be fixed
2. Seems you're used your own DMS for integration - could you check that you can reproduce this error using integrated example (enabled via `http://docserverurl/welcome`) and if so - I need exact scenario how to reproduce that, because I cannot say anything jus by error

**Comment by bipana50** [comment]
@ShockwaveNN Hi, I am feeling hopeless about this

- I have updated to v7.1.1, but still the same error
- Also I tried reproducing in the nodeJS example, but this is working fine
- I refactored all my code, all the code is basically the same as the example now, and I am using the same DMS that the example is using, still I am getting another SDK error

```Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'io')```

Can you give me some pointers on why could this be happening? I really don't know how to move forward now.

**Comment by bipana50** [comment]
Could it be because of some data missing in the config? Also, I have removed the authentication `cfgSignatureEnable` blocks. But nothing seems related to this SDK issue

**Comment by ShockwaveNN** [comment]
Sorry, I don't think I know how to help you since I got literally zero info about your system you've trying to ingregrate

If you can provide some code samples, preferable in Dockerfile/docker-compose format with this error reporducable - we can try to check it out

But without it - your only chance compare test example and see how it's different with your code

**Comment by bipana50** [comment]
It's solved, the "document.key" config was the issue. Updating the key on every edit and save fixed the problem.
