### ISSUE TITLE
Download and print fails with custom fonts used

### ISSUE THREAD

**Issue by pipodzneli** [ONLYOFFICE/DocumentServer#1856]
Bug.

Hello. I have added Georgian fonts to my nextcloud/onlyoffice instance. So far everything works, fonts show up in selection menu and text is readable as expected, but when i press print button or try to download document in pdf format for example i get error:

![nextcloud-print-error](https://user-images.githubusercontent.com/80679491/183685727-7b56a90f-4cf7-48be-b3e1-a3dcba0381c1.png)

And here is error from converters out.log:

[2022-08-09T15:00:41.174] [ERROR] nodeJS - error spawnAsync(id=4170815598)
Error: /var/www/onlyoffice/documentserver/server/FileConverter/bin/x2t exited with signal: SIGSEGV
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:8:21)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)

You can follow documented steps to add custom font. In this case you can download https://fonts.ge/ka/download/font/16/LitNusx this font to try reproduce similar behavior. Also i have many different Georgian fonts from which some works as expected, but most of them gives error shown above. 
Here you can download another Georgian font which works well if needed for comparison:
https://fonts.ge/ka/download/font/281/Geo-GrigoliaPolygraph

DocumentServer version: 7.1.1

Operating System: Ubuntu 22.04

Browser version: Firefox 103.0+build1-0ubuntu0.20.04.1

I have tried same setup with docker install and with deb package installation result is same in both case.

**Comment by ShockwaveNN** [comment]
Hi, could you check that same error happens via integrated DocumentServer example (enabled at `http://docserver_url/welcome`) and if not - this may be some proxying issue (if proxy present)

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
