### ISSUE TITLE
onlyoffice-documentserver 7.2.0-204 fails to open/save office documents in Nextcloud Hub II (23.0.9)

### ISSUE THREAD

**Issue by caniwi** [ONLYOFFICE/DocumentServer#1916]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
After upgrading onlyoffice-documentserver from 7.1.1-23 => 7.2.0-204 on Ubuntu 20.04 with  Nextcloud Hub II (23.0.9) it fails to open Office documents (docx, xlsx).  Onlyoffice loads correctly but says download failed, press ok to to return to document list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Upgrade from onlyoffice-documentserver using apt.  Go into Nextcloud and try to edit an Office document.  IT worked fine for a file with an .md extension.

**What is the expected behavior?**
It should load the offfice document, allow you to edit it and then save it.

**Did this work in previous versions of DocumentServer?**
yes it was working fine in onlyoffice-documentserver 7.1.1-23 with onlyoffice Nextcloud app 7.4.4.

**DocumentServer version:**
7.2.0-204 

**Operating System:**
Ubuntu 20.04.5 LTS

**Browser version:**
Firefox 104
Chromium 105.0.5195.125

the documentsever out.log has the following in it:
/var/log/onlyoffice/documentserver/docservice# cat out.log
[2022-09-29T00:00:16.282] [WARN] nodeJS - Express server starting...
[2022-09-29T00:00:16.284] [WARN] nodeJS - Set services.CoAuthoring.token.enable.browser, services.CoAuthoring.token.enable.request.inbox, services.CoAuthoring.token.enable.request.outbox in the Document Server config to prevent an unauthorized access to your documents and the substitution of important parameters in ONLYOFFICE Document Server requests.
[2022-09-29T00:00:16.286] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-09-29T00:00:16.397] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.1.1. Build: 23
[2022-09-29T08:03:51.107] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
[2022-09-29T08:03:51.109] [WARN] [localhost] [docId] [userId] nodeJS - Set services.CoAuthoring.token.enable.browser, services.CoAuthoring.token.enable.request.inbox, services.CoAuthoring.token.enable.request.outbox in the Document Server config to prevent an unauthorized access to your documents and the substitution of important parameters in ONLYOFFICE Document Server requests.
[2022-09-29T08:03:51.111] [WARN] [localhost] [docId] [userId] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-09-29T08:03:51.328] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.2.0. Build: 204
[2022-09-29T08:09:06.443] [WARN] [localhost] [docId] [userId] nodeJS - Express server starting...
[2022-09-29T08:09:06.445] [WARN] [localhost] [docId] [userId] nodeJS - Set services.CoAuthoring.token.enable.browser, services.CoAuthoring.token.enable.request.inbox, services.CoAuthoring.token.enable.request.outbox in the Document Server config to prevent an unauthorized access to your documents and the substitution of important parameters in ONLYOFFICE Document Server requests.
[2022-09-29T08:09:06.452] [WARN] [localhost] [docId] [userId] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availability
[2022-09-29T08:09:06.487] [ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-09-29T08:09:07.491] [ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-09-29T08:09:08.493] [ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-09-29T08:09:09.495] [ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-09-29T08:09:10.498] [ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
[2022-09-29T08:09:13.475] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 7.2.0. Build: 204

**Comment by caniwi** [comment]
Re-installing the previous version of onlyoffice-documentserver (7.1.1-23) and office document editing is fine again.

apt install onlyoffice-documentserver=7.1.1-23

**Comment by stepjacky** [comment]
> Error: connect ECONNREFUSED 127.0.0.1:5672
note above log info 
did your rabbitmq listening on localhost 5672?

**Comment by Toka69** [comment]
Hello, I have a Docker + Traefik + Nextcloud + OnlyOffice Server stack and I confirm that during a new installation today, I had to delete the latest and specify 7.1 for everything to work. I had an Invalid Token error.

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 comes with JWT enabled by default with random key values
Check `http://docserverurl/welcome` for details how to get JWT secret value

**Comment by hoegerl** [comment]
Hi,

i use Nextcloud 24.0.6 & OnlyOffice 7.1 (docker). After upgrading to OnlyOffice 7.2.0.204 (docker) the editor doesn't work anymore.
I got the default jwt-secret of the docker container as explained -> http://docserverurl
When i try to configure the OnlyOffice jwt-secret in the Nextcloud OnlyOffice integration app, i get an error "error while downloading the document file to be converted".
Configuring the jwt-secret and jwt-header in the Nextcloud "config.php" doesn't work either.
Config:
  'onlyoffice' =>
  array (
    'verify_peer_off' => true,
    'jwt_header' => 'Authorization',
    'jwt_secret' => '<jwt-secret-here>',
  ),

My nextcloud protocol shows:
Exception: Im Dokumentenservice ist ein Fehler aufgetreten: Error while downloading the document file to be converted.		Oktober 14, 2022 21:04:36
Download empty without jwt		Oktober 14, 2022 21:04:34
Download empty without jwt		Oktober 14, 2022 21:04:33

Reverting to OnlyOffice 7.1 (docker) give a functional editor again.

**Comment by ant0nwax** [comment]
I can configrm for CentOS 8 Stream
I was running into an issue with 
```
[2022-12-20T17:40:25.004] [ERROR] [localhost] [docId] [userId] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
```
first i completely deactivated ipv6 in grub and with sysctl
then i downgraded to

`yum install onlyoffice-documentserver-7.1.1-23`
```
Downgrading:
 onlyoffice-documentserver              x86_64              7.1.1-23                onlyoffice              516 M
```

solved the issue described above

**Comment by caniwi** [comment]
I have successfully upgraded to onlyoffice-documentserver 7.1.1-23 -> 7.2.2-56.  For working integration with Nextcloud 24.0.7.  you have to follow the integration steps as described https://helpcenter.onlyoffice.com/gettingstarted/integration/Nextcloud.aspx.

**Comment by Khasann94** [comment]
ee
