### ISSUE TITLE
Download failed on CentOS

### ISSUE THREAD

**Issue by CrotchBurnt** [ONLYOFFICE/DocumentServer#1957]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
it shows download failed on the page

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
docservice out.log shows following:
`[2022-10-26T19:19:07.661] [WARN] [localhost] [docId] [userId] nodeJS - Express server listening on port 20002 in production-linux mode. Version: 7.2.1. Build: 34
[2022-10-26T19:19:34.023] [WARN] [localhost] [-1144211476] [1] nodeJS - sqlQuery error sqlCommand: INSERT INTO task_result (tenant, id, status, statu: error: syntax error at or near "ON"
    at Parser.parseErrorMessage (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2022-10-26T19:19:34.023] [WARN] [localhost] [-1144211476] [1] nodeJS - checkIsSupportOnConflict false`

I just newly installed on CentOS 7.5.1804
Healthcheck returns true
Postgresql version is 9.2.24

**What is the expected behavior?**
showing content correctly

**Did this work in previous versions of DocumentServer?**
Not know

**DocumentServer version:**
7.2.1

**Operating System:**
CentOS 7.5.1804

**Browser version:**
Edge 106 stable

**Comment by ShockwaveNN** [comment]
I don't think this error is related to download file, SQL part at lest - it's shown because psql v9 do not support some features

Download failed usually happens then you're using localhost for opening DocumentServer or the some firewall or proxy blocking it

If non of this ring a bell - please try to setup it on new server with minimal modifications and check if same error happens

**Comment by ShockwaveNN** [comment]
Any comments on why it was closed? This may help other users

**Comment by ShockwaveNN** [comment]
@CrotchBurnt Maybe some limits by default by created user?
