### ISSUE TITLE
 window.Asc.asc_docs_api is not a constructor

### ISSUE THREAD

**Issue by 102010cncger** [ONLYOFFICE/DocumentServer#200]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

[2017-11-14 17:04:11.535] [ERROR] nodeJS - error spawnAsync(id=TR_TRAIN_88629)
Error: Process exited with non-zero code: 86
    at ChildProcess.child.on (C:\server\DocumentServer\server\FileConverter\node_modules\_@expo_spawn-async@1.3.0@@expo\spawn-async\build\spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\server\DocumentServer\server\FileConverter\node_modules\_cross-spawn@5.1.0@cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[2017-11-14 17:04:11.551] [ERROR] nodeJS - stdout (id=TR_TRAIN_88629_3819):
[2017-11-14 17:04:11.553] [ERROR] nodeJS - stderr (id=TR_TRAIN_88629_3819):open_code:           _api = new window["Asc"]["asc_docs_api"]({});
open: Uncaught TypeError: window.Asc.asc_docs_api is not a constructor
DoctRenderer:<result><error code="open" /></result>

[2017-11-14 17:04:11.560] [ERROR] nodeJS - ExitCode (code=86;signal=null;error:-86;id=TR_TRAIN_88629_3819)
[2017-11-14 17:05:33.189] [ERROR] nodeJS - error spawnAsync(id=TR_TRAIN_88639)
Error: Process exited with non-zero code: 89
    at ChildProcess.child.on (C:\server\DocumentServer\server\FileConverter\node_modules\_@expo_spawn-async@1.3.0@@expo\spawn-async\build\spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\server\DocumentServer\server\FileConverter\node_modules\_cross-spawn@5.1.0@cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[2017-11-14 17:06:15.813] [ERROR] nodeJS - error spawnAsync(id=TR_TRAIN_88640)
Error: Process exited with non-zero code: 89
    at ChildProcess.child.on (C:\server\DocumentServer\server\FileConverter\node_modules\_@expo_spawn-async@1.3.0@@expo\spawn-async\build\spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\server\DocumentServer\server\FileConverter\node_modules\_cross-spawn@5.1.0@cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[2017-11-14 17:06:48.089] [ERROR] nodeJS - error spawnAsync(id=TR_TRAIN_88633)
Error: Process exited with non-zero code: 89
    at ChildProcess.child.on (C:\server\DocumentServer\server\FileConverter\node_modules\_@expo_spawn-async@1.3.0@@expo\spawn-async\build\spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\server\DocumentServer\server\FileConverter\node_modules\_cross-spawn@5.1.0@cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[2017-11-14 17:06:48.423] [ERROR] nodeJS - error spawnAsync(id=TR_TRAIN_88631)
Error: Process exited with non-zero code: 86
    at ChildProcess.child.on (C:\server\DocumentServer\server\FileConverter\node_modules\_@expo_spawn-async@1.3.0@@expo\spawn-async\build\spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\server\DocumentServer\server\FileConverter\node_modules\_cross-spawn@5.1.0@cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[2017-11-14 17:06:48.434] [ERROR] nodeJS - stdout (id=TR_TRAIN_88631_660):
[2017-11-14 17:06:48.441] [ERROR] nodeJS - stderr (id=TR_TRAIN_88631_660):open_code:            _api = new window["Asc"]["spreadsheet_api"]({});
open: Uncaught TypeError: window.Asc.spreadsheet_api is not a constructor
DoctRenderer:<result><error code="open" /></result>

[2017-11-14 17:06:48.445] [ERROR] nodeJS - ExitCode (code=86;signal=null;error:-86;id=TR_TRAIN_88631_660)
[2017-11-14 17:30:41.766] [ERROR] nodeJS - error spawnAsync(id=TR_TRAIN_88643)
Error: Process exited with non-zero code: 86
    at ChildProcess.child.on (C:\server\DocumentServer\server\FileConverter\node_modules\_@expo_spawn-async@1.3.0@@expo\spawn-async\build\spawnAsync.js:39:21)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\server\DocumentServer\server\FileConverter\node_modules\_cross-spawn@5.1.0@cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[2017-11-14 17:30:41.769] [ERROR] nodeJS - stdout (id=TR_TRAIN_88643_193):
[2017-11-14 17:30:41.770] [ERROR] nodeJS - stderr (id=TR_TRAIN_88643_193):open_code:            _api = new window["Asc"]["spreadsheet_api"]({});
open: Uncaught TypeError: window.Asc.spreadsheet_api is not a constructor
DoctRenderer:<result><error code="open" /></result>

[2017-11-14 17:30:41.771] [ERROR] nodeJS - ExitCode (code=86;signal=null;error:-86;id=TR_TRAIN_88643_193)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

the file is from customer, i cannot upload,and if open with office and save  then  there is no error

**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**

current 

**Operating System:**

window10

**Browser version:**

all

**Comment by ShockwaveNN** [comment]
@102010cncger can you be more specific in version, than "current".

**Comment by agolybev** [comment]
@ShockwaveNN  I think, he download it by https://github.com/ONLYOFFICE/DocumentServer/releases/download/ONLYOFFICE-DocumentServer-5.0.3/onlyoffice-documentserver.exe

**Comment by 102010cncger** [comment]
i build flow this https://wiki.ling2.cn/index.php/Onlyoffice%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91

**Comment by ShockwaveNN** [comment]
@102010cncger This is not official instruction how to build our server, you should contact its author.
Currently we have no official instruction for Windows, but we planning to release it soon.

**Comment by agolybev** [comment]
@102010cncger, try installing Onlyoffice Document Server by following [this](http://helpcenter.onlyoffice.com/server/windows/document/install-office-apps.aspx) instruction.
