### ISSUE TITLE
docservice fails to start `tenants.baseDomain` error

### ISSUE THREAD

**Issue by MikeDacre** [ONLYOFFICE/DocumentServer#2049]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.2.1

### Expected Behavior

Server should start. Had been working fine until recently. I just realized it was offline and went to see why. No major server changes, just standard `apt` updates.

### Actual Behavior

`supervisorctl restart all`:

      ds:metrics: stopped
      ds:example: stopped
      ds:converter: ERROR (spawn error)
      ds:metrics: started
      ds:example: started
      ds:docservice: ERROR (spawn error)`

Repeated entry in both `/var/log/onlyoffice/documentserver/docservice/err.log` and `/var/log/onlyoffice/documentserver/converter/err.log`:

    Error: Configuration property "tenants.baseDomain" is not defined
        at Config.get (/snapshot/server/build/server/Common/node_modules/config/lib/config.js:203:11)
        at Object.<anonymous> (/snapshot/server/build/server/Common/sources/tenantManager.js)
        at Module._compile (pkg/prelude/bootstrap.js:1930:22)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
        at Module.load (internal/modules/cjs/loader.js:950:32)
        at Function.Module._load (internal/modules/cjs/loader.js:790:12)
        at Module.require (internal/modules/cjs/loader.js:974:19)
        at Module.require (pkg/prelude/bootstrap.js:1855:31)
        at require (internal/modules/cjs/helpers.js:101:18)
        at Object.<anonymous> (/snapshot/server/build/server/Common/sources/operationContext.js)
    pkg/prelude/bootstrap.js:1876
          throw error;
          ^

**Comment by igwyd** [comment]
Hello @MikeDacre, can you tell me server type and version? And attach local.json and default.json files without confidential information?

**Comment by MikeDacre** [comment]
Sure. ` Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-135-generic x86_64)`

[default_and_local_json.zip](https://github.com/ONLYOFFICE/DocumentServer/files/10270986/default_and_local_json.zip)

**Comment by igwyd** [comment]
These are the new parameters, for some reason default.json didn't get updated on your server. Is the problem solved now?

**Comment by MikeDacre** [comment]
Yes, thank you. My guess is that when it was updating I told it not to use the new file.
