### ISSUE TITLE
relation `task_result` does not exist

### ISSUE THREAD

**Issue by azmeuk** [ONLYOFFICE/DocumentServer#2072]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.2.2-56

### Expected Behavior

No error message in the logs.

### Actual Behavior

The following error message appears a lot of time in the documentserver stdout log:

```
[2023-01-12T20:00:12.241] [WARN] [localhost] [docId] [userId] nodeJS - sqlQuery error sqlCommand: SELECT * FROM task_result WHERE last_open_date <= : error: relation "task_result" does not exist
    at Parser.parseErrorMessage (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[2023-01-12T20:00:12.241] [ERROR] [localhost] [docId] [userId] nodeJS - checkFileExpire error: error: relation "task_result" does not exist
    at Parser.parseErrorMessage (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/snapshot/server/build/server/DocService/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

### Reproduction Steps

I suppose any action involving the `task_result` table would do?
I can reproduce this by trying to connect to the OO document server from the nextcloud administration panel.

**Comment by azmeuk** [comment]
I am not sure why the database was not initialized. I could solve the situation with `sudo -u postgres psql onlyoffice -h localhost -U onlyoffice -f /var/www/onlyoffice/documentserver/server/schema/postgresql/createdb.sql`

**Comment by hahaxd35** [comment]
for me this not helps, still getting the error

**Comment by hahaxd35** [comment]
dropping and reini helps.. damn this took hours....

**Comment by zyy1939** [comment]
psql -h localhost -U onlyoffice -d onlyoffice -f /var/www/onlyoffice/documentserver/server/schema/postgresql/createdb.sql
