### ISSUE TITLE
Spellcheker not working on node 8

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#209]
**What is the current behavior?**
1. Install nodejs 8 (current LTS)
2. Install latest stable `onlyoffice-documentserver`
3. `cat /var/log/onlyoffice/documentserver/spellchecker/err.log`
```
Error: The module '/var/www/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:664:18)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/SpellChecker/sources/spellCheck.js:13:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

```

**DocumentServer version:** 5.0.4.15

**Operating System:** debian 9.2

**Comment by trofim24** [comment]
Spell Checker needs to compile under node 8
