### ISSUE TITLE
missing config directories after install

### ISSUE THREAD

**Issue by KernelDeimos** [ONLYOFFICE/DocumentServer#2163]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

latest from installation instructions

### Expected Behavior

docservice, converter, and metrics all start up with post-install script

### Actual Behavior

Metrics server starts. The other two services fail to start with the following errors in `err.log`:

**docservice**

```
WARNING: No configurations found in configuration directory:/var/www/onlyoffice/documentserver/server/DocService/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "services.CoAuthoring" is not defined
    at Config.get (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/server.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at internal/main/run_main_module.js:17:47
```

**converter**

```
WARNING: No configurations found in configuration directory:/var/www/onlyoffice/documentserver/server/FileConverter/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Configuration property "log.filePath" is not defined
    at Config.get (/snapshot/server/build/server/Common/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/Common/sources/logger.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/snapshot/server/build/server/FileConverter/sources/convertermaster.js)
```

Within `/var/www/onlyoffice/documentserver/server`, `Metrics` subdirectory contains a config subdirectory. The other two services are missing this directory.

### Reproduction Steps

```
sudo apt update
sudo apt install curl
sudo apt install curl
sudo apt install curl
sudo apt install curl
```

**Comment by igwyd** [comment]
Hello @KernelDeimos, I have no errors starting services after installation in my Ubuntu 22.04 server. Which linux version do you use?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
