### ISSUE TITLE
missing config directories after install

### ISSUE THREAD

**Issue by KernelDeimos** [ONLYOFFICE/DocumentServer#2164]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

latest from installation instructions

### Expected Behavior

docservice, converter, and metrics all start up with post-install script

### Actual Behavior

Metrics server starts. The other two services fail to start with the following errors in `err.log`:

**docservice**

```
WARNING: No configurations found in configuration directory:/var/www/onlyoffice/documentserver/server/DocService/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "services.CoAuthoring" is not defined
    at Config.get (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/server.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at internal/main/run_main_module.js:17:47
```

**converter**

```
WARNING: No configurations found in configuration directory:/var/www/onlyoffice/documentserver/server/FileConverter/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Configuration property "log.filePath" is not defined
    at Config.get (/snapshot/server/build/server/Common/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/Common/sources/logger.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/snapshot/server/build/server/FileConverter/sources/convertermaster.js)
```

Within `/var/www/onlyoffice/documentserver/server`, `Metrics` subdirectory contains a config subdirectory. The other two services are missing this directory.

### Reproduction Steps

```
sudo apt update
sudo apt install curl
sudo apt install build-essential
sudo apt install git
sudo apt install pkg-config
sudo apt install postgresql
sudo apt install redis-server
sudo apt install rabbitmq-server
sudo apt install nginx
sudo apt install nginx-extras
sudo apt install npm
npm install -g json

mkdir -p -m 700 ~/.gnupg
curl -fsSL https://download.onlyoffice.com/GPG-KEY-ONLYOFFICE | gpg --no-default-keyring --keyring gnupg-ring:/tmp/onlyoffice.gpg --import
chmod 644 /tmp/onlyoffice.gpg
chown root:root /tmp/onlyoffice.gpg
mv /tmp/onlyoffice.gpg /usr/share/keyrings/onlyoffice.gpg
sh -c 'echo "deb [signed-by=/usr/share/keyrings/onlyoffice.gpg] https://download.onlyoffice.com/repo/debian squeeze main" | tee /etc/apt/sources.list.d/onlyoffice.list'

sudo apt-get update
sudo apt-get install ttf-mscorefonts-installer

service postgresql start
sudo -i -u postgres psql -c "CREATE USER onlyoffice WITH PASSWORD 'onlyoffice';"
sudo -i -u postgres psql -c "CREATE DATABASE onlyoffice OWNER onlyoffice;"
service nginx start
service rabbitmq-server start
service redis-server start

sudo apt install onlyoffice-documentserver-de
```

**Comment by KernelDeimos** [comment]
Closing this - I finally found [this similar issue](https://github.com/ONLYOFFICE/build_tools/issues/97) and realized it's the environment variables not making it to the service
