### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by zzzzlllzzz** [ONLYOFFICE/DocumentServer#2257]
[ERROR] [localhost] [cda3b920-7a06-4cf8-a2c5-e6d685b0f436] [uid-1685583284463] nodeJS - error downloadFile:url=http://xxx.xxx.xxxx:9005/test/%E7%A7%91%E5%AD%A6%E6%95%B0%E6%8D%AE%E4%B8%AD%E5%BF%83/workplan.docx?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230601T031454Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1800&X-Amz-Credential=root%2F20230601%2Fminio%2Fs3%2Faws4_request&X-Amz-Signature=111a07a33d2d873e9736a4d70c63280dd47e5ee3501235b0b79daf81f50ea9b8;attempt=3;code:undefined;connect:undefined Error: Error response: statusCode:400; headers:{"accept-ranges":"bytes","content-length":"274","content-type":"application/xml","server":"MinIO","vary":"Origin","date":"Thu, 01 Jun 2023 03:14:58 GMT"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by igwyd** [comment]
Hello @zzzzlllzzz, please correctly fill the issue template, provide more information about your installation so we can help you.
