### ISSUE TITLE
[Solved] Configuration property "server.isAnonymousSupport" is not defined

### ISSUE THREAD

**Issue by smguenther** [ONLYOFFICE/DocumentServer#2294]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.4.0-163

### Expected Behavior

Documentserver doesn't start at all anymore,it  only creates messages in /var/log/onlyoffice/documentserver/docservice/err.log
I'm not sure, whether this is related to an update.

### Actual Behavior

When starting the documentserver, it only creates the following error messages in /var/log/onlyoffice/documentserver/docservice/err.log:

```
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Configuration property "server.isAnonymousSupport" is not defined
    at Object.<anonymous> (/snapshot/server/build/server/DocService/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/DocsCoServer.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/snapshot/server/build/server/DocService/sources/server.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at internal/main/run_main_module.js:17:47
```

The message is repeated again and again.

### Additional information

Ubuntu 22.04

**Comment by smguenther** [comment]
Solved. Had to enter 

`"isAnonymousSupport": true`

in  section
```

"services": {
                "CoAuthoring": {
                        "server": {

```
of file /etc/onlyoffice/documentserver/default.json

**Comment by igwyd** [comment]
Hello @smguenther i think it's the update, in 7.4.0 we added the parameter. Default.json with standart server parameters not updated during updgrade on your server. I'm glad you solved the problem yourself, can we close this issue?

**Comment by trofim24** [comment]
I think, we can close. If you have any questions, please open new issue.
