### ISSUE TITLE
NextCloud and OnlyOffice Behind Apache Reverse Proxy Receiving 302 Found Nginx

### ISSUE THREAD

**Issue by calvinlevy** [ONLYOFFICE/DocumentServer#235]
**Dear OnlyOffice**:

After exhausting all attempts with online documentation, I now enlist your help.  After several different and complete installs, I have seemingly one final issue to work out.  I think so anyway...

**Configuration**:  
**PROXY(x.x.x.100)**:  CentOS 7.4.1708; Apache/2.4.6; SELinux = Enforcing
**NEXTCLOUD (x.x.x.134)**:  CentOS 7.4.1708; Apache/2.4.6; SELinux = Disabled (Tried Enforcing & Permissive); PHP 7.1.11; MariaDB 5.5.56-2
**ONLYOFFICE DOCUMENT SERVER (x.x.x.142)**:  CentOS 7.4.1708; Nginx/1.12.2; SELinux = Permissive (Tried Enforcing); Nodejs-6.12.2; PostgreSQL 9.2.23; Redis server 3.2.10; RabbitMQ 3.3.5; Microsoft Core Fonts 2.6.1 (I DID NOT use the install.sh script for this server.  I manually installed all components.)  Browsing to the Document Server, I receive a green/white check and "Document Server is running".

**Output from Document Server** /web-apps/apps/api/documents/api.js [api-js.txt](https://github.com/ONLYOFFICE/DocumentServer/files/1672071/api-js.txt)

SSL:  Both NEXTCLOUD and ONLYOFFICE servers can be reached externally using https://nextcloud.xxx.com/nextcloud and https://ds.xxx.com respectfully.  Both are qualified using https://ssllabs.com.  The actual servers themselves DO NOT have ssl installed.  I did add SSL to Nginx on the Document Server during one set of tests but it did not work...at least for me.  I have opened the recommended firewall ports on the Document Server also: 80, 443, 5432, 5672, 6379, 8000 & 8080/tcp.

I have great success with NEXTCLOUD http to ONLYOFFICE DS http.  My difficulty is when using https in the ONLYOFFICE configuration in NEXTCLOUD.  When I key in the qualified HTTPS server addresses and click save, I receive "Settings Have Been Successfully Updated".  Makes me really happy to see.  For some time I struggled with this part.  When clicking to view files and available resources, I am able to see OnlyOffice's Document, Spreadsheet and Presentation links.  When I click an existing document or create a new one using OnlyOffice, I then receive the disappointing "302 Found nginx" error.

I have used the GitHub recommended vHost configurations with no good results.  Would you take a look a my Apache Reverse Proxy vHost configuration and advise?  I hope it's a simple fix... :-)

**Copy of Apache Reverse Proxy vHost Configuration** [apache-reverse-proxy-vhost.txt](https://github.com/ONLYOFFICE/DocumentServer/files/1672108/apache-reverse-proxy-vhost.txt)

Thank you in advance for your response.

================================================================================
Additional testing information since first post:

**office-ds:** The original server in post installed and running SELinux = permissive.  Receive 302 error. Now saying blocked by an extension.
**office-ds2:** New test server installed and running SELinux = disabled.  No error, just blank page.

**office-ds: Output from /var/log/onlyoffice/docuserver/out.log:**
[2018-01-27 14:53:36.258] [WARN] nodeJS - **Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability)**.
[2018-01-27 14:53:36.281] [WARN] nodeJS - update cluster with 1 workers
[2018-01-27 14:53:36.294] [WARN] nodeJS - worker 2918 started.
[2018-01-27 14:53:36.294] [WARN] nodeJS - update cluster with 1 workers
[2018-01-27 14:53:36.819] [WARN] nodeJS - Express server starting...
[2018-01-27 14:53:37.438] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-01-27 14:54:49.880] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-01-27 14:54:49.890] [WARN] nodeJS - update cluster with 1 workers
[2018-01-27 14:54:49.904] [WARN] nodeJS - worker 3503 started.
[2018-01-27 14:54:49.904] [WARN] nodeJS - update cluster with 1 workers
[2018-01-27 14:54:50.224] [WARN] nodeJS - Express server starting...
[2018-01-27 14:54:50.682] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-01-28 14:28:25.096] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-01-28 14:28:25.117] [WARN] nodeJS - update cluster with 1 workers
[2018-01-28 14:28:25.136] [WARN] nodeJS - worker 1226 started.
[2018-01-28 14:28:25.136] [WARN] nodeJS - update cluster with 1 workers
[2018-01-28 14:28:25.567] [WARN] nodeJS - Express server starting...
[2018-01-28 14:28:26.434] [ERROR] n**odeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672**
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
[2018-01-28 14:28:27.608] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-01-29 14:28:26.364] [WARN] nodeJS - update cluster with 1 workers

**office-ds2: Output from /var/log/onlyoffice/docuserver/out.log:**
[2018-01-29 16:00:10.075] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-01-29 16:00:10.090] [WARN] nodeJS - update cluster with 1 workers
[2018-01-29 16:00:10.115] [WARN] nodeJS - worker 2603 started.
[2018-01-29 16:00:10.115] [WARN] nodeJS - update cluster with 1 workers
[2018-01-29 16:00:10.434] [WARN] nodeJS - Express server starting...
[2018-01-29 16:00:10.704] [ERROR] nodeJS - checkIsSupportOnConflict unexpected error code:
error: Ident authentication failed for user "onlyoffice"
    at Connection.parseE (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
[2018-01-29 16:00:10.851] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-01-29 16:02:57.440] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-01-29 16:02:57.449] [WARN] nodeJS - update cluster with 1 workers
[2018-01-29 16:02:57.464] [WARN] nodeJS - worker 3620 started.
[2018-01-29 16:02:57.464] [WARN] nodeJS - update cluster with 1 workers
[2018-01-29 16:02:58.096] [WARN] nodeJS - Express server starting...
[2018-01-29 16:02:58.514] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[root@wingu-office-ds2 docservice]# cat out.log
[2018-01-29 16:00:10.075] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-01-29 16:00:10.090] [WARN] nodeJS - update cluster with 1 workers
[2018-01-29 16:00:10.115] [WARN] nodeJS - worker 2603 started.
[2018-01-29 16:00:10.115] [WARN] nodeJS - update cluster with 1 workers
[2018-01-29 16:00:10.434] [WARN] nodeJS - Express server starting...
[2018-01-29 16:00:10.704] [ERROR] nodeJS - checkIsSupportOnConflict unexpected error code:
error: Ident authentication failed for user "onlyoffice"
    at Connection.parseE (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
[2018-01-29 16:00:10.851] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2018-01-29 16:02:57.440] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2018-01-29 16:02:57.449] [WARN] nodeJS - update cluster with 1 workers
[2018-01-29 16:02:57.464] [WARN] nodeJS - worker 3620 started.
[2018-01-29 16:02:57.464] [WARN] nodeJS - update cluster with 1 workers
[2018-01-29 16:02:58.096] [WARN] nodeJS - Express server starting...
[2018-01-29 16:02:58.514] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

**Comment by agolybev** [comment]
Hi @calvinlevy, I've found just one:
In [apache-reverse-proxy-vhost.txt](https://github.com/ONLYOFFICE/DocumentServer/files/1672108/apache-reverse-proxy-vhost.txt)
The statement `RequestHeader set X-Forwarded-Host x.x.x.142` is wrong. It should be `RequestHeader set X-Forwarded-Host ds.xxx.com`

**Comment by calvinlevy** [comment]
Thank you @agolybev.  Unfortunately, the issue still exists after testing the modification.  I confirmed DNS is resolving okay.  Disabled/reenabled the OnlyOffice plugin.  Verified settings.  Settings accepted successfully.  Oddly, using ds.xxx.com rendered a strange DNS loopback.  It caused the URL test to ds.xxx.com to report https://ds.xxx.com,%20ds.xxx.com/welcome/.  I went back to %{THE_HOST}e.

Additionally, when testing a document, Firefox reports **302 Found nginx**.  And at the same moment, the same file in Chrome reports **Requests to the server have been blocked by an extension**.

**Comment by agolybev** [comment]
Calvin, cloud you provide url to ds when 302 error occur?

**Comment by calvinlevy** [comment]
https://nextcloud.xxx.com/nextcloud/index.php/apps/onlyoffice/105

**Comment by agolybev** [comment]
Hmm.. actualy I mean url to documents server, you can find it in console inside debug mode(F12).

**Comment by calvinlevy** [comment]
https;//ds.wingutechnology.com
   api.js
https://nextcloud.wingutechnology.com
   editor.js
   client.js
   contactsmenu.js
   core.js
   merged-template-prepend.js
   fileinfo.js
   jquery-ui-fixes.js
   merged-share-backend.js
   merged.js
   serach.js
   previewplugin.js
   viewer.js

**Comment by agolybev** [comment]
There are any errors in the debug console?

**Comment by calvinlevy** [comment]
I do not recognize any errors.  If you're willing to email me, I will reply with credentials for you to review directly.  This is a test/dev server to prep future roll-outs.  calvin.levy@wingutechnology.com

**Comment by agolybev** [comment]
Hi Clavin, now I see the mixed content issue. Document Server doesn't know the real protocol and redirects requests using `http` protocol. I think proxy server doesn't set up `X-Forwarded-Proto `, on the other hand I don't undestand why it happend because I've saw `RequestHeader set X-Forwarded-Proto https` statment in the appache config.

**Comment by calvinlevy** [comment]
Resolved.  Thanks @agolybev!  The working configuration is below.  (Yes, you are seeing correct.  Removing the **RequestHeader set X-Forwarded-Host** line resolved my issues.)  And...changing X-Forwarded-Proto to "set".

    SetEnvIf Host "^(.*)$" THE_HOST=$1
    RequestHeader set X-Forwarded-Proto https
    ProxyAddHeaders Off

Using Apache/2.4.6.
