### ISSUE TITLE
On a CentOS 9 server, I'm unable to successfully save Excel files while editing, and the error log in the background is as follows. Word files are working fine.

### ISSUE THREAD

**Issue by PlatonaBoy** [ONLYOFFICE/DocumentServer#2381]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

7.4.1

### Expected Behavior

Can open, edit, and save both.

### Actual Behavior

error spawnAsync Error: ../FileConverter/bin/x2t /tmp/ASC_CONVERT123810-bn99v.yfa9wd/params.xml exited with non-zero code: 86
    at ChildProcess.completionListener (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
    ...
    at spawnAsync (/snapshot/server/build/server/FileConverter/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnProcess (/snapshot/server/build/server/FileConverter/sources/converter.js)
    at spawnProcess.next (<anonymous>)
    at ExecuteTask (/snapshot/server/build/server/FileConverter/sources/converter.js)
    at ExecuteTask.next (<anonymous>)
    at /snapshot/server/build/server/FileConverter/sources/converter.js
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/FileConverter/node_modules/co/index.js:65:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2023-09-10T11:38:12.898] [ERROR] [localhost] [2029891466] [11] nodeJS - stdout:
[2023-09-10T11:38:12.898] [ERROR] [localhost] [2029891466] [11] nodeJS - stderr:TypeError: Cannot read property 'length' of null
    at e.jye (<anonymous>:16241:64)
    at d.wV (<anonymous>:16249:322)
    at Object.wV (<anonymous>:12486:191)
    at q.aM (<anonymous>:17079:274)
    at <anonymous>:20040:41
    at g.u9g (<anonymous>:20040:405)
    at g.ksg (<anonymous>:20040:11)
    at g.RN (<anonymous>:19948:486)
    at new g (<anonymous>:19943:480)
    at e.PRg (<anonymous>:11399:298)
TypeError: Cannot read property 'length' of null
    at e.jye (<anonymous>:16241:64)
    at d.wV (<anonymous>:16249:322)
    at Object.wV (<anonymous>:12486:191)
    at q.aM (<anonymous>:17079:274)
    at <anonymous>:20040:41
    at g.u9g (<anonymous>:20040:405)
    at g.ksg (<anonymous>:20040:11)
    at g.RN (<anonymous>:19948:486)
    at new g (<anonymous>:19943:480)
    at e.PRg (<anonymous>:11399:298)
DoctRenderer:<result><error code="open" /></result>

[2023-09-10T11:38:12.898] [ERROR] [localhost] [2029891466] [11] nodeJS - ExitCode (code=86;signal=null;error:-86)

**Comment by igwyd** [comment]
Hello @PlatonaBoy, I checked onlyoffice documentserver v 7.4.1 rpm on the Centos 9 with internal test example, no errors with saving any files. Which the integration do you use the document server with? PLease provide the steps to reproduce.

**Comment by PlatonaBoy** [comment]
I compiled it in the Ubuntu 18.04 environment without packaging it into an RPM file for installation. After the compilation was completed, I copied the compiled files to a CentOS 9 system and followed the instructions in the official website's compilation tutorial to run the program. The program runs without any errors, and the Word files work fine, but there is an issue with saving Excel files. The backend logs indicate an exception.

**Comment by igwyd** [comment]
I compiled like you did, transferred it to Centos 9 and installed it according to the guide from https://github.com/ONLYOFFICE/build_tools#document-server, didn't receive any errors when editing and savind DOCX, XSLX and PPTX files. Maybe your issue is in integration? Try our test-example https://api.onlyoffice.com/editors/example/nodejs#Linux

**Comment by PlatonaBoy** [comment]
The problem has been solved. After changing the program directory, the fonts need to be regenerated.

**Comment by china-lai** [comment]
> The problem has been solved. After changing the program directory, the fonts need to be regenerated.

What would happen if fonts weren't generated?
