### ISSUE TITLE
Only Office disable this test example

### ISSUE THREAD

**Issue by sasori0623** [ONLYOFFICE/DocumentServer#2419]
I have finished testing and would like to move on to the real thing.

Is the URL, etc. different in the production environment?

If there is a way to set this up, I would appreciate it if you could tell me how to do it.

Thank you in advance.

**DocumentServer version:**
lasted
**Operating System:**
Docker  For Ubuntu
**Browser version:**
chorome

**Comment by igwyd** [comment]
Hello @sasori0623, the URL is the same. You can stop integrated test example in docker with this command ```sudo docker exec <container> sudo supervisorctl stop ds:example```.

**Comment by sasori0623** [comment]
> Hello @sasori0623, the URL is the same. You can stop integrated test example in docker with this command `sudo docker exec <container> sudo supervisorctl stop ds:example`.


Thank you very much for your reply.

We apologize for any inconvenience.

When I disable the service, I get the TEST page at the bottom of the page when I open it on localhost.

Does the URL change when the service goes live?

How do I change the URL for production?　Or is there a link to it?

Thank you in advance.

**Comment by sasori0623** [comment]
![1697293580828@2x](https://github.com/ONLYOFFICE/DocumentServer/assets/43268295/b69ae40c-1eaa-4a33-a006-3c94a5a80cc3)

Thank you, friend.

When I change the PORT on the Document Server from the default of 80, I get this error and cannot open WORD files, etc.

Also, the window looks like the attached image when it is normal, but for some reason, it redirects to the Welcome page and opens.

Please tell me how to solve this problem.

Thank you in advance
(The following screen redirects to Welcome and does not open.)




![Server](https://github.com/ONLYOFFICE/DocumentServer/assets/43268295/e3a8d1c9-6889-47a5-8aba-909f51f05a0e)

```
==> /var/log/onlyoffice/documentserver/docservice/out.log <==
2023-10-14 23:16:53 [2023-10-14T14:16:53.358] [ERROR] [localhost] [172.17.0.1new.docx1697293012970] [uid-1] nodeJS - postData error: url = http://localhost:8080/example/track?filename=new.docx&useraddress=172.17.0.1;data = {"key":"172.17.0.1new.docx1697293012970","status":1,"users":["uid-1"],"actions":[{"type":1,"userid":"uid-1"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxNzIuMTcuMC4xbmV3LmRvY3gxNjk3MjkzMDEyOTcwIiwic3RhdHVzIjoxLCJ1c2VycyI6WyJ1aWQtMSJdLCJhY3Rpb25zIjpbeyJ0eXBlIjoxLCJ1c2VyaWQiOiJ1aWQtMSJ9XSwiaWF0IjoxNjk3MjkzMDEzLCJleHAiOjE2OTcyOTMzMTN9.r_HGhxgWMc9KScTbgjFWzRrMuof2_VH8QvRGs8oydF0"} Error: connect ECONNREFUSED 127.0.0.1:8080
2023-10-14 23:16:53     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
2023-10-14 23:16:53 
2023-10-14 23:16:53 ==> /var/log/onlyoffice/documentserver/converter/out.log <==
2023-10-14 23:16:53 [2023-10-14T14:16:53.387] [ERROR] [localhost] [172.17.0.1new.docx1697293012970] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=172.17.0.1;attempt=1;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
2023-10-14 23:16:53     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
2023-10-14 23:16:54 [2023-10-14T14:16:54.391] [ERROR] [localhost] [172.17.0.1new.docx1697293012970] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=172.17.0.1;attempt=2;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
2023-10-14 23:16:54     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
2023-10-14 23:16:55 [2023-10-14T14:16:55.394] [ERROR] [localhost] [172.17.0.1new.docx1697293012970] [uid-1] nodeJS - error downloadFile:url=http://localhost:8080/example/download?fileName=new.docx&useraddress=172.17.0.1;attempt=3;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:8080
2023-10-14 23:16:55     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
```

**Comment by igwyd** [comment]
This is just a welcome page. The document server address is the same as the welcome page. If you don’t like the welcome page, you can disable it in the nginx config https://github.com/ONLYOFFICE/document-server-package/blob/master/common/documentserver/nginx/includes/ds-docservice.conf.m4#L2.
To change the documentserver address, you can use a reverse proxy, we have example configs for this https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx

**Comment by sasori0623** [comment]
Very  Very Thank　YOU！！
It is done! Thank you very much!


Can I make one more point? I'm sorry.

Do you know why I can connect with localhost, but not with a direct IP DDNS server?

By the way, I am able to open PORT and resolve names at HOST.

Thank you in advance.

**Comment by igwyd** [comment]
_Do you know why I can connect with localhost, but not with a direct IP DDNS server?_
There could be many reasons - your firewall, external proxy, dns server, network settings etc.

**Comment by sasori0623** [comment]
Thank you for your help.

I am able to access the only office globally from an external device.

However, when I enter the only office url in the filerun, it whiteouts and I cannot access the site.

However, if I specify the onlyoffice uri in the filerun at http://localhostと on localhost pc, I can access it.

But in that state, both global and local are whiteed out, and I cannot access onlyoffice from filerun.

It is quite a mysterious phenomenon.

Sorry.

Thank you in advance for your help

**Comment by igwyd** [comment]
I havn't expirience with the firerun, can you show the logs of the onlyoffice-documentserver when you try to connect it to the firerun?

**Comment by sasori0623** [comment]
Thank you very much for contacting us.

I was not sure where the log file was located, so I would like to report the current status.
I am sorry.

I am able to access this page from Windows 11 and from outside.

http://kytvservice.aa0.netvolante.jp:14591/welcome/

The page is above.

However, when I use a PHP application called FileRun and enter the URL of OnlyOffice (http://kytvservice.aa0.netvolante.jp:14591/) to complete the setup, and then try to open the Office file, I get the error in the attached image.

Then, when I try to open the Office file from Chrome on the PC running the LocalHost server with the address of OnlyOffice as "http://localhost", it succeeds.

By the way, I am using Docker installed on WSL2 Ubuntu.

I'm really having trouble understanding the meaning of the above, because I can access the file from the outside, but it fails.

I can access it on localhost, so why is it not working when I can open the port globally 💦.

Sorry for the inconvenience. Thank you very much for your help.

**Comment by sasori0623** [comment]
Thanks for your help.

I have just tried this on another PC and the same symptoms are occurring.

Also, when I use http://localhost, only the local host PC can access the site.

However, when I set http://DDNS.com, Filerun does not access.

Also, if I specify the IP address directly, the same situation occurs.

I can't access Document Server by port forwarding, only localhost can access. Is there any configuration that allows access to the Document Server only on localhost?

If so, there is a possibility that it is interfering with the access.

Thank you very much for all your help.

Thank you again for your help.



> I havn't expirience with the firerun, can you show the logs of the onlyoffice-documentserver when you try to connect it to the firerun?

**Comment by igwyd** [comment]
_Is there any configuration that allows access to the Document Server only on localhost?_
Yes, we have the [ipfilter](https://github.com/ONLYOFFICE/server/blob/14c99c97edcf3f741ae9518b7643e5c993a8386d/Common/config/default.json#L220) for this in the our config ```/etc/onlyoffice/documentserver/default.json```, but it's disabled by deafult.
Could you show your docker run command?
In docker you can view the logs ```docker logs -f <container>```, i guess we see the problem.

**Comment by igwyd** [comment]
I don’t see connection attempts, try connecting to the filerun and watch logs at the time.

**Comment by sasori0623** [comment]
FileRun logs are not generated, so I feel stuck there as well.

Also, we are using the latest version of OnlyOffice.

However, the official Filerun website says it is now compatible with 7.1. I was wondering if I could just match the versions.


Also, I wondered if it is possible to do this on Windows. I installed the Windows version of Document Server, but I get a Nginx error.

I will post the details of the error so that we can solve the problem if we use the Windows version.

Also, I can go to the top page of OnlyOffice, but when I open a Word file, the page is whiteed out.

Thank you in advance for your help.



```
2023/10/17 20:28:31 [error] 16968#8780: *5 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /example/ HTTP/1.1", upstream: "http://127.0.0.1:9999/", host: "127.0.0.1:8021", referrer: "http://127.0.0.1:8021/welcome/"
2023/10/17 20:28:33 [error] 16968#8780: *5 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /example/ HTTP/1.1", upstream: "http://[::1]:9999/", host: "127.0.0.1:8021", referrer: "http://127.0.0.1:8021/welcome/"
2023/10/17 20:28:35 [error] 16968#8780: *5 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8888/favicon.ico", host: "127.0.0.1:8021", referrer: "http://127.0.0.1:8021/example/"
2023/10/17 20:28:37 [error] 16968#8780: *10 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /example/ HTTP/1.1", upstream: "http://example/", host: "127.0.0.1:8021", referrer: "http://127.0.0.1:8021/welcome/"
2023/10/17 20:28:39 [error] 16968#8780: *17 no live upstreams while connecting to upstream, client: 127.0.0.1, server: , request: "GET /example/ HTTP/1.1", upstream: "http://example/", host: "127.0.0.1:8021", referrer: "http://127.0.0.1:8021/welcome/"
```

**Comment by igwyd** [comment]
As far as I can see, your server is up and running http://kytvservice.aa0.netvolante.jp:14591/, also work the integration test example ```/exapmle``` and http://kytvservice.aa0.netvolante.jp:14591/healthcheck shows true. 
These errors in the nginx log show interrupted connections, [as I said earlier](https://github.com/ONLYOFFICE/DocumentServer/issues/2419#issuecomment-1765652502), this usually happens due to network settings when connecting or issue in filerun. Unfortunately, I can't check the filerun yet. Recently it stopped providing free access, I requested a trial. This is probably the problem, now they are need to pay for FQDN https://filerun.com/client-area/?module=website&section=default&page=buy&license_id=H.

**Comment by igwyd** [comment]
As far as I can see, your server is up and running http://kytvservice.aa0.netvolante.jp:14591/, also work the integration test example ```/exapmle``` and http://kytvservice.aa0.netvolante.jp:14591/healthcheck shows true. 
These errors in the nginx log show interrupted connections, [as I said earlier](https://github.com/ONLYOFFICE/DocumentServer/issues/2419#issuecomment-1765652502), this usually happens due to network settings when connecting or issue in filerun. Unfortunately, I can't check the filerun yet. Recently it stopped providing free access, I requested a trial. Now they are need to[ pay for FQDN](https://filerun.com/client-area/?module=website&section=default&page=buy&license_id=H)  this is probably the problem, n.

**Comment by sasori0623** [comment]
I charged and tried Filerun. I tried to use the Windows version of OnlyOffice, but it didn't work.

When I opened the document in OnlyOffice, the UI became a buggy window and an error occurred. I was troubled for several days, but could not solve the problem.

I'm really sorry, but I would like to ask for your help again. I am attaching the error log and the screen with the whiteout bug.
[Log.zip](https://github.com/ONLYOFFICE/DocumentServer/files/13060419/Log.zip)
![error onlyoffice](https://github.com/ONLYOFFICE/DocumentServer/assets/43268295/32b24100-fc04-4c40-aedb-aef1afb7ad56)

**Comment by igwyd** [comment]
@sasori0623 Filerun didn't provide me a test version, so I couldn't test it. But I found out that fileran team are developing integration with onlyoffice-documentserver themself, try contacting them about connection

**Comment by AverTry** [comment]
> This is just a welcome page. The document server address is the same as the welcome page. If you don’t like the welcome page, you can disable it in the nginx config https://github.com/ONLYOFFICE/document-server-package/blob/master/common/documentserver/nginx/includes/ds-docservice.conf.m4#L2. To change the documentserver address, you can use a reverse proxy, we have example configs for this https://helpcenter.onlyoffice.com/installation/docs-community-proxy.aspx

---
I've stopped to example, but I cannot stop the welcome page, is this a security risk?
the link you gave goes to your code, not details on preventing the welcome page?
Please help, I'm running docker with community server.

**Comment by igwyd** [comment]
@AverTry it's not security risk, but as I already said you can disable the welcome page - comment out this [line](https://github.com/ONLYOFFICE/document-server-package/blob/master/common/documentserver/nginx/includes/ds-docservice.conf.m4#L2 ) into onlyoffice docker container ```/etc/nginx/includes/ds-docservice.conf``` and then restart nginx ```service nginx restart```.

**Comment by AverTry** [comment]
> service nginx restart

Thank you igwyd
