### ISSUE TITLE
Compilation instructions do not work!

### ISSUE THREAD

**Issue by jlaguma** [ONLYOFFICE/DocumentServer#2443]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.5.0

### Expected Behavior

I’m busy building OO Groups from source following this instrcutions:

https://helpcenter.onlyoffice.com/installation/groups-compile-windows.aspx

When everything is compiled and built files are moved to C:\ONLYOFFICE folder,
The ManageServices.bat script is expected to execute cleanly.

### Actual Behavior

When everything is compiled and built files are moved to C:\ONLYOFFICE folder,
The script that starts everything up (ManageServices.bat) has the following lines in it:

`call %basepath%\WinSW3.0.0.exe install %grandparent%\run\Radicale.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\SsoAuth.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\SocketIO.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\WebDav.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\UrlShortener.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\Thumb.xml`

All of those .xml files are missing. So not everything starts up properly.

Where do I find those missing .xml files?

Thanks.

### Reproduction Steps

Following exact instructions on https://helpcenter.onlyoffice.com/installation/groups-compile-windows.aspx

**Comment by jlaguma** [comment]
I modified the ASC.Web.Studio\web.connections.config file and mysql password field was empty, so I put in the password. That made a small progress.
http://127.0.0.1/Wizard.aspx now opens up.

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/20492291/16ed16e7-8ffa-4e2e-bf1c-9b06e1e46882)

But if I click Continue" or “Change it”, I get those errors:

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/20492291/d720088a-b20c-473e-b6d2-31baf640f46a)

**Comment by jlaguma** [comment]
Log file is also showing the following errors:

`I got this errors in log file:

2023-10-23 14:14:41,799 ERROR [40] localhost - ASC.Web - Warmup error StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: PUBLISH asc:channel:insertorupdate:system.collections.generic.keyvaluepair`2[[system.string, mscorlib, version=[4.0.0.0](http://4.0.0.0/), culture=neutral, publickeytoken=b77a5c561934e089],[asc.web.studio.core.startupprogress, [asc.web.studio](http://asc.web.studio/), version=[1.0.0.0](http://1.0.0.0/), culture=neutral, publickeytoken=null]]; UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325, mc: 1/1/0, mgr: 10 of 10 available, clientName: WIN-RMP5NHARU43, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=3,Free=32764,Min=8,Max=32767), v: 2.2.88.56325 ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325
--- Конец трассировки внутреннего стека исключений ---
в StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
в ASC.Common.Caching.RedisCache.Publish[T](T obj, CacheNotifyAction cacheNotifyAction)
в ASC.Web.Studio.Core.WarmUp.Publish()
в ASC.Web.Studio.Core.WarmUp..ctor()
2023-10-23 14:14:41,938 ERROR [40] localhost - ASC - StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: PUBLISH asc:channel:remove:asc.core.data.settingscacheitem; UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325, mc: 1/1/0, mgr: 10 of 10 available, clientName: WIN-RMP5NHARU43, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=3,Free=32764,Min=8,Max=32767), v: 2.2.88.56325 ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325
--- Конец трассировки внутреннего стека исключений ---
в StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
в ASC.Common.Caching.RedisCache.Publish[T](T obj, CacheNotifyAction cacheNotifyAction)
в ASC.Core.Data.DbSettingsManager.SaveSettingsFor[T](T settings, Int32 tenantId, Guid userId)
2023-10-23 14:14:44,683 ERROR [65] localhost - ASC - StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: PUBLISH asc:channel:remove:asc.core.data.settingscacheitem; UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325, mc: 1/1/0, mgr: 10 of 10 available, clientName: WIN-RMP5NHARU43, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=3,Free=32764,Min=8,Max=32767), v: 2.2.88.56325 ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325
--- End of inner exception stack trace ---
at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at ASC.Common.Caching.RedisCache.Publish[T](T obj, CacheNotifyAction cacheNotifyAction)
at ASC.Core.Data.DbSettingsManager.SaveSettingsFor[T](T settings, Int32 tenantId, Guid userId)
2023-10-23 14:27:04,726 ERROR [67] localhost - ASC - StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: PUBLISH asc:channel:remove:asc.core.data.settingscacheitem; UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325, mc: 1/1/0, mgr: 10 of 10 available, clientName: WIN-RMP5NHARU43, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=3,Free=32764,Min=8,Max=32767), v: 2.2.88.56325 ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325
--- End of inner exception stack trace ---
at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at ASC.Common.Caching.RedisCache.Publish[T](T obj, CacheNotifyAction cacheNotifyAction)
at ASC.Core.Data.DbSettingsManager.SaveSettingsFor[T](T settings, Int32 tenantId, Guid userId)
2023-10-23 14:35:53,659 ERROR [49] localhost - ASC - StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: PUBLISH asc:channel:remove:asc.core.data.settingscacheitem; UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325, mc: 1/1/0, mgr: 10 of 10 available, clientName: WIN-RMP5NHARU43, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=3,Free=32764,Min=8,Max=32767), v: 2.2.88.56325 ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on [127.0.0.1:6379/Interactive](http://127.0.0.1:6379/Interactive), Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 1s ago, v: 2.2.88.56325
--- End of inner exception stack trace ---
at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at ASC.Common.Caching.RedisCache.Publish[T](T obj, CacheNotifyAction cacheNotifyAction)
at ASC.Core.Data.DbSettingsManager.SaveSettingsFor[T](T settings, Int32 tenantId, Guid userId)`

**Comment by jlaguma** [comment]
Can somebody help? Where do I find the missing .xml files to start up the following:

`	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\Radicale.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\SsoAuth.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\SocketIO.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\WebDav.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\UrlShortener.xml
	call %basepath%\WinSW3.0.0.exe install %grandparent%\run\Thumb.xml`

**Comment by AntonKashichkin** [comment]
Hello jlaguma, could you please confirm whether your issue is still relevant or has been resolved?

**Comment by Rita-Bubnova** [comment]
This issue was closed due to no response.
