### ISSUE TITLE
Onlyoffice Docment Server installed in Docker, SSL with Cloudflare Tunnel, and unable to edit.

### ISSUE THREAD

**Issue by yasikitakajin** [ONLYOFFICE/DocumentServer#2449]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I installed Onlyoffice Docment Server with Docker and SSL using Cloudflare Tunnel, but the document says "Could not save the text. Please check your connection settings." and then "Download failed. I am having trouble editing the document.

I found the error log in Docker, so I am attaching it as well.

Also, the error log shows "TLS". If I use an external service such as Cloudflare Tunnel to convert to SSL, will it be considered that OnlyOffice is not able to convert to SSL and access will be disabled?

If so, I would appreciate it if you could tell me how to disable TLS and other settings for the SSL-enabled external service.

Thank you in help

`/var/log/onlyoffice/documentserver/docservice/out.log <==
2023-10-29 21:26:07 [2023-10-29T12:26:07.345] [ERROR] nodeJS - postData error: docId = 30--1696671927;url = https://yasikitakajin.click.jp/FileRun/wl/?id=H4rZJ0s1QsIjhCpdzqrA0JkhHCX5xrag&action=onlyoffice&save=1;data = {"key":"30--1696671927","status":1,"users":["1"],"actions":[{"type":1,"userid":"1"}]}
2023-10-29 21:26:07 Error: Client network socket disconnected before secure TLS connection was established
2023-10-29 21:26:07     at connResetException (internal/errors.js:628:14)
2023-10-29 21:26:07     at TLSSocket.onConnectEnd (_tls_wrap.js:1569:19)
2023-10-29 21:26:07     at TLSSocket.emit (events.js:412:35)
2023-10-29 21:26:07     at endReadableNT (internal/streams/readable.js:1317:12)
2023-10-29 21:26:07     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2023-10-29 21:26:09 
2023-10-29 21:26:09 ==> /var/log/onlyoffice/documentserver/converter/out.log <==
2023-10-29 21:26:09 [2023-10-29T12:26:09.424] [ERROR] nodeJS - error downloadFile:url=https://yasikitakajin.click.jp/FileRun/wl/?id=H4rZJ0s1QsIjhCpdzqrA0JkhHCX5xrag&download=1;attempt=1;code:ECONNRESET;connect:undefined;(id=30--1696671927)
2023-10-29 21:26:09 Error: Client network socket disconnected before secure TLS connection was established
2023-10-29 21:26:09     at connResetException (internal/errors.js:628:14)
2023-10-29 21:26:09     at TLSSocket.onConnectEnd (_tls_wrap.js:1569:19)
2023-10-29 21:26:09     at TLSSocket.emit (events.js:412:35)
2023-10-29 21:26:09     at endReadableNT (internal/streams/readable.js:1317:12)
2023-10-29 21:26:09     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2023-10-29 21:26:12 [2023-10-29T12:26:12.474] [ERROR] nodeJS - error downloadFile:url=https://yasikitakajin.click.jp/FileRun/wl/?id=H4rZJ0s1QsIjhCpdzqrA0JkhHCX5xrag&download=1;attempt=2;code:ECONNRESET;connect:undefined;(id=30--1696671927)
2023-10-29 21:26:12 Error: Client network socket disconnected before secure TLS connection was established
2023-10-29 21:26:12     at connResetException (internal/errors.js:628:14)
2023-10-29 21:26:12     at TLSSocket.onConnectEnd (_tls_wrap.js:1569:19)
2023-10-29 21:26:12     at TLSSocket.emit (events.js:412:35)
2023-10-29 21:26:12     at endReadableNT (internal/streams/readable.js:1317:12)
2023-10-29 21:26:12     at processTicksAndRejections (internal/process/task_queues.js:82:21)
2023-10-29 21:26:15 [2023-10-29T12:26:15.517] [ERROR] nodeJS - error downloadFile:url=https://yasikitakajin.click.jp/FileRun/wl/?id=H4rZJ0s1QsIjhCpdzqrA0JkhHCX5xrag&download=1;attempt=3;code:ECONNRESET;connect:undefined;(id=30--1696671927)
2023-10-29 21:26:15 Error: Client network socket disconnected before secure TLS connection was established
2023-10-29 21:26:15     at connResetException (internal/errors.js:628:14)
2023-10-29 21:26:15     at TLSSocket.onConnectEnd (_tls_wrap.js:1569:19)
2023-10-29 21:26:15     at TLSSocket.emit (events.js:412:35)
2023-10-29 21:26:15     at endReadableNT (internal/streams/readable.js:1317:12)
2023-10-29 21:26:15     at processTicksAndRejections (internal/process/task_queues.js:82:21)`

**Comment by igwyd** [comment]
Hello @yasikitakajin, sorry for the late reply. What integration are you using, i mean nextcloud maybe or something else?

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
