### ISSUE TITLE
Configuration property "wopi.dummy.sampleFilePath" is not defined

### ISSUE THREAD

**Issue by mageunic** [ONLYOFFICE/DocumentServer#2571]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

latest release (8.0.0-99)

### Expected Behavior

ds-Docservice started and activated

### Actual Behavior

ds-docservice currently deactivated : 
logs from : **onlyoffice/documentserver/docservice/out.log**
```
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Configuration property "wopi.dummy.sampleFilePath" is not defined
    at Config.get (/snapshot/server/DocService/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/snapshot/server/DocService/sources/wopiClient.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/server/DocService/sources/canvasservice.js)
```

### Reproduction Steps

Update onlyoffice-documentserver 7.5 to 8.0

### Additional information

Onlyoffice is installed by following this guide : 
https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx

System informations :
KDE neon 5.27 (based on Ubuntu 22.04) x64
8 Gb of RAM
i5-4460 CPU

**Comment by mageunic** [comment]
Issue solved by uninstalling the server and reinstalling it
