### ISSUE TITLE
after upgrade to 13.0.1 no documents load (converter errors)

### ISSUE THREAD

**Issue by seelaman** [ONLYOFFICE/DocumentServer#266]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Unable to open any documents

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Opening an existing docx, xlsx or pptx file
Onlyoffice loading animation comes on
Then "Loading presentation"
This spins for a long time
Eventually error message "This file cannot be opened"

Errors in /var/log/onlyoffice/documentserver/converter/err.log

Error: Configuration property "filePath" is not defined
    at Object.Config.get (/var/www/onlyoffice/documentserver/server/FileConverter/node_modules/config/lib/config.js:181:11)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/FileConverter/sources/converter.js:35:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/FileConverter/sources/convertermaster.js:68:21)
/var/www/onlyoffice/documentserver/server/FileConverter/node_modules/config/lib/config.js:181
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**
Yes

**DocumentServer version:**
13.0.1

**Operating System:**
Ubuntu 16.04.2 LTS

**Browser version:**
Any Browser I tried, latest chrome, firefox

**Comment by ShockwaveNN** [comment]
seems this is config conflict after upgrading DocumentServer from some pretty old (4.x) version to 5.x
Try to backup your config, remove documentserver config from `/etc/onlyoffice/documentserver` and reinstall DocumentServer
(BTW 13.0.1 is not version of DocumentServer`

**Comment by ShockwaveNN** [comment]
This ticket is being closed due to no response
