### ISSUE TITLE
performance.memory: {"totalJSHeapSize":263134872,"usedJSHeapSize":242268232,"jsHeapSizeLimit":4294705152}

### ISSUE THREAD

**Issue by tuguoqiang** [ONLYOFFICE/DocumentServer#2677]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.0.1

### Expected Behavior

Hello, when I go to preview a 36M file, the error is displayed as follows:
2024-03-27 16:02:14  performance.memory: {"totalJSHeapSize":263134872,"usedJSHeapSize":242268232,"jsHeapSizeLimit":4294705152}
2024-03-27 16:02:14  StackTrace: RuntimeError: memory access out of bounds
2024-03-27 16:02:14     at http://192.168.1.107:19080/8.0.1-31/sdkjs/pdf/src/engine/drawingfile.wasm:wasm-function[4959]:0x34dbd7
2024-03-27 16:02:14     at http://192.168.1.107:19080/8.0.1-31/sdkjs/pdf/src/engine/drawingfile.wasm:wasm-function[7165]:0x471e01
2024-03-27 16:02:14     at CFile.getLinks (http://192.168.1.107:19080/8.0.1-31/sdkjs/pdf/src/engine/drawingfile.js:112:293)
2024-03-27 16:02:14     at f.KVg (http://192.168.1.107:19080/8.0.1-31/sdkjs/word/sdk-all.js:11451:488)
2024-03-27 16:02:14     at e.gMg (http://192.168.1.107:19080/8.0.1-31/sdkjs/word/sdk-all.js:11413:219)
2024-03-27 16:02:14     at e.M_c (http://192.168.1.107:19080/8.0.1-31/sdkjs/word/sdk-all.js:11365:494)
2024-03-27 16:02:14     at zhf (http://192.168.1.107:19080/8.0.1-31/sdkjs/word/sdk-all.js:11365:397)

### Actual Behavior

Hello, when I go to preview a 36M file, the error is displayed as follows:
2024-03-27 16:02:14  performance.memory: {"totalJSHeapSize":263134872,"usedJSHeapSize":242268232,"jsHeapSizeLimit":4294705152}
2024-03-27 16:02:14  StackTrace: RuntimeError: memory access out of bounds
2024-03-27 16:02:14     at http://192.168.1.107:19080/8.0.1-31/sdkjs/pdf/src/engine/drawingfile.wasm:wasm-function[4959]:0x34dbd7
2024-03-27 16:02:14     at http://192.168.1.107:19080/8.0.1-31/sdkjs/pdf/src/engine/drawingfile.wasm:wasm-function[7165]:0x471e01
2024-03-27 16:02:14     at CFile.getLinks (http://192.168.1.107:19080/8.0.1-31/sdkjs/pdf/src/engine/drawingfile.js:112:293)
2024-03-27 16:02:14     at f.KVg (http://192.168.1.107:19080/8.0.1-31/sdkjs/word/sdk-all.js:11451:488)
2024-03-27 16:02:14     at e.gMg (http://192.168.1.107:19080/8.0.1-31/sdkjs/word/sdk-all.js:11413:219)
2024-03-27 16:02:14     at e.M_c (http://192.168.1.107:19080/8.0.1-31/sdkjs/word/sdk-all.js:11365:494)
2024-03-27 16:02:14     at zhf (http://192.168.1.107:19080/8.0.1-31/sdkjs/word/sdk-all.js:11365:397)

### Additional information

![image](https://github.com/ONLYOFFICE/DocumentServer/assets/26316252/83ffc880-08cf-4a91-82b0-82c71b6a0432)

**Comment by avdddd1111** [comment]
Hello @tuguoqiang ! Sorry for the late reply!

Could you please let me know if you encounter this error with all documents?

Can you attach your 36MB document to this issue?

If the file is confidential, could you send it to: files@onlyoffice.com? (If yes, please specify the version: DocumentServer#[issue-number]).
