### ISSUE TITLE
Services fail to start after installation

### ISSUE THREAD

**Issue by toreonify** [ONLYOFFICE/DocumentServer#2712]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

8.0.1

### Expected Behavior

After following installation guide services start normally.

### Actual Behavior

Services fail to start because environment variables are not passed from service description files. Service is launched in a subshell, environment shouldn't be passed. It must be explicitly set through `export` or by prepending a command. Launching `converter` directly without `/bin/sh` still doesn't pass environment variables and it fails.

Output example of a failed service:

```
апр 25 15:08:13 nextcloud systemd[1]: Started Docs Converter.
апр 25 15:08:13 nextcloud converter[816668]: WARNING: NODE_ENV value of 'production-linux' did not match any deployment config file names.
апр 25 15:08:13 nextcloud converter[816668]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
апр 25 15:08:13 nextcloud converter[816668]: pkg/prelude/bootstrap.js:1876
апр 25 15:08:13 nextcloud converter[816668]:       throw error;
апр 25 15:08:13 nextcloud converter[816668]:       ^
апр 25 15:08:13 nextcloud converter[816668]: Error: Configuration property "log.filePath" is not defined
апр 25 15:08:13 nextcloud converter[816668]:     at Config.get (/snapshot/server/Common/node_modules/config/lib/config.js:203:11)
апр 25 15:08:13 nextcloud converter[816668]:     at Object.<anonymous> (/snapshot/server/Common/sources/logger.js)
апр 25 15:08:13 nextcloud converter[816668]:     at Module._compile (pkg/prelude/bootstrap.js:1930:22)
апр 25 15:08:13 nextcloud converter[816668]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
апр 25 15:08:13 nextcloud converter[816668]:     at Module.load (node:internal/modules/cjs/loader:981:32)
апр 25 15:08:13 nextcloud converter[816668]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
апр 25 15:08:13 nextcloud converter[816668]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
апр 25 15:08:13 nextcloud converter[816668]:     at Module.require (pkg/prelude/bootstrap.js:1855:31)
апр 25 15:08:13 nextcloud converter[816668]:     at require (node:internal/modules/cjs/helpers:102:18)
апр 25 15:08:13 nextcloud converter[816668]:     at Object.<anonymous> (/snapshot/server/FileConverter/sources/convertermaster.js)
апр 25 15:08:13 nextcloud systemd[1]: ds-converter.service: Main process exited, code=exited, status=1/FAILURE
апр 25 15:08:13 nextcloud systemd[1]: ds-converter.service: Failed with result 'exit-code'.
```

Moving variables from `Environment` to `ExecStart` fixes this issue. For example, `ds-converter` service:

```
ExecStart=/bin/sh -c 'NODE_ENV=production-linux NODE_CONFIG_DIR=/etc/onlyoffice/documentserver NODE_DISABLE_COLORS=1 APPLICATION_NAME=ONLYOFFICE /var/www/onlyoffice/documentserver/server/FileConverter/converter'
```

### Additional information

For some reason, earlier test of R7-Office didn't had this issue and started normally, though it contains almost identical service description files.

Software verions:
ALT Server 10.2 (Mendelevium)
Linux nextcloud 5.10.166-std-def-alt1 #1 SMP Thu Feb 9 11:47:41 UTC 2023 x86_64 GNU/Linux
onlyoffice-documentserver-8.0.1-31.el7.x86_64
systemd-249.17-alt1.x86_64

**Comment by avdddd1111** [comment]
Hello @toreonify 

We haven't checked the installation of the document server on Alt Linux, and as we can see, there is an issue with installing dependencies. This problem has been reported to the developers. Ticket 67882.

**Comment by toreonify** [comment]
> there is an issue with installing dependencies.

Yep, I've manually created fake packages with correct dependencies for xorg-x11-server-Xvfb (xorg-xvfb in ALT) and liberation-mono-fonts (liberation-fonts in ALT) to complete installation.
