### ISSUE TITLE
PDF editing in Nextcloud crashes

### ISSUE THREAD

**Issue by osscombat** [ONLYOFFICE/DocumentServer#2803]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.1.26

### Expected Behavior

Editing PDF text the same way as in the Desktop Editor.

### Actual Behavior

Docker image from onlyoffice/documentserver:latest
OnlyOffice connector 9.3.0
Nextcloud 29.0.3

![image](https://github.com/user-attachments/assets/5d5643e8-61df-4d08-bffb-c29482e1b708)
and this errors in the log:

```
[2024-07-17T07:15:58.602] [ERROR] [localhost] [162643124] [oc747wap60ez_admin1] nodeJS - clientLog: changesError: Error: Uncaught TypeError: Cannot read properties of null (reading 're')
 Script: https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js
 Line: 2879:65
 userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
 platform: Win32
 isLoadFullApi: true
 isDocumentLoadComplete: true
 DocumentInfo:
 Selection: false
 performance.memory: {"totalJSHeapSize":266942195,"usedJSHeapSize":248730875,"jsHeapSizeLimit":4294705152}
 StackTrace: TypeError: Cannot read properties of null (reading 're')
    at e.px (https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js:2879:65)
    at a.<anonymous> (https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js:6720:247)
    at Object.U [as ug] (https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js:1661:175)
    at y.Wg (https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js:6720:36)
    at a.tc (https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js:11992:311)
    at a.oh (https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js:11983:452)
    at https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js:11719:403
    at Array.forEach (<anonymous>)
    at e.ktd (https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js:11719:381)
    at e.CDa (https://office.domain.com/8.1.1-26/sdkjs/word/sdk-all.js:11697:402)
```

### Reproduction Steps

Just try to edit the text in the PDF file.

**Comment by RSerejo** [comment]
same here

**Comment by porly1985** [comment]
exact same behaviour and error messages in my case. 

When I use Demo ONLYOFFICE Docs Server for testing it works like it should. 

Owncloud 10.15.
OnlyOffice 8.1.1-26 on Debian (without Docker).

**Comment by STREKOZZEL** [comment]
Same problem with Docker DocumentServer version 8.1.3.
`onlyoffice-documentserver  | [2024-10-14T08:12:31.891] [ERROR] [localhost] [192.168.0.62_________________________Soft_Nano1__1_.pdf1728893545537] [uid-11] nodeJS - clientLog: changesError: Error: Uncaught TypeError: Cannot read properties of null (reading 're')
onlyoffice-documentserver  |  Script: https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js
onlyoffice-documentserver  |  Line: 2879:65
onlyoffice-documentserver  |  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 YaBrowser/24.7.0.0 Safari/537.36
onlyoffice-documentserver  |  platform: Win32
onlyoffice-documentserver  |  isLoadFullApi: true
onlyoffice-documentserver  |  isDocumentLoadComplete: true
onlyoffice-documentserver  |  DocumentInfo:
onlyoffice-documentserver  |  Selection: false
onlyoffice-documentserver  |  performance.memory: {"totalJSHeapSize":125993382,"usedJSHeapSize":104240954,"jsHeapSizeLimit":4294705152}
onlyoffice-documentserver  |  StackTrace: TypeError: Cannot read properties of null (reading 're')
onlyoffice-documentserver  |     at e.px (https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js:2879:65)
onlyoffice-documentserver  |     at a.<anonymous> (https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js:6720:247)
onlyoffice-documentserver  |     at Object.U [as ug] (https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js:1661:175)
onlyoffice-documentserver  |     at y.Wg (https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js:6720:36)
onlyoffice-documentserver  |     at a.tc (https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js:11993:311)
onlyoffice-documentserver  |     at a.oh (https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js:11984:452)
onlyoffice-documentserver  |     at https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js:11720:403
onlyoffice-documentserver  |     at Array.forEach (<anonymous>)
onlyoffice-documentserver  |     at e.mtd (https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js:11720:381)
onlyoffice-documentserver  |     at e.DDa (https://office.domain.com:9443/8.1.3-1~oou/sdkjs/word/sdk-all.js:11698:402)`

**Comment by FedorLap2006** [comment]
Oh, this also happens if you select the text and click "Edit text" in the .
