### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'offsetHeight')

### ISSUE THREAD

**Issue by shoyu666** [ONLYOFFICE/DocumentServer#2880]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

8.1.0.169

### Expected Behavior

Cannot read properties of null (reading 'offsetHeight')

### Actual Behavior

Cannot read properties of null (reading 'offsetHeight')

### Reproduction Steps

Cannot read properties of null (reading 'offsetHeight')

### Additional information

onlyOffice-281031d3.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'offsetHeight')
    at Proxy.renderComment (onlyOffice-281031d3.js:1:6332)
    at Proxy.<anonymous> (onlyOffice-281031d3.js:1:5850)
<img width="1461" alt="image" src="https://github.com/user-attachments/assets/25c525e9-6e9a-4058-bbb6-0f0f9bb76281">

**Comment by shoyu666** [comment]
<img width="571" alt="image" src="https://github.com/user-attachments/assets/c04c6d05-d576-4309-ab6d-9aff3640d075">

**Comment by shoyu666** [comment]
- [ ]
