### ISSUE TITLE
Document Server Connection Issue

### ISSUE THREAD

**Issue by hamslicejumbomice** [ONLYOFFICE/DocumentServer#295]
Hi guys I'm looking for some feedback on why this isn't working. 

Currently I have my ONLYOFFICE document server running on a Windows 10 build.  I followed these exact instructions for my installation: https://helpcenter.onlyoffice.com/server/windows/document/install-office-apps.aspx
I have an Owncloud server running on an Ubuntu 18.04 build, newest version, everything up to date. The server is being powered by XAMPP. 

My issue is that when I type in the ip address of my Document Server on Owncloud it cannot find it. I know that my Owncloud server can see my Document server because when I open firefox on my Owncloud server and type in the ip address of the Document Server I get the green check mark saying "Document Server is running." I also added the address of the Doc Server to my trusted domain list in the Owncloud configuration file. 

Now I noticed that whenever I try to connect the two the same way I described above it produces more errors in the DocumentServer log file. I will attach the file to the post. 
[DocServerLog.log](https://github.com/ONLYOFFICE/DocumentServer/files/1995716/DocServerLog.log)

![image](https://user-images.githubusercontent.com/39136684/39931078-fdecc208-5501-11e8-9905-4bb53abc8982.png)

![image](https://user-images.githubusercontent.com/39136684/39931766-0150c2a8-5504-11e8-8e88-5e5f609e6284.png)

**Comment by ShockwaveNN** [comment]
@hamslicejumbomice In your logs you have 
```
[2018-05-10 11:31:53.955] [ERROR] nodeJS - healthCheck error
error: password authentication failed for user "onlyoffice"
    at Connection.parseE (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```
Seems you entered incorrect password for postgres server

**Comment by hamslicejumbomice** [comment]
Yes, that was a an issue that I had solved earlier but I was wanting you to look at the more recent logs

These are the error messages I get from trying to connect the two servers

[2018-05-10 13:05:31.638] [ERROR] nodeJS - sqlQuery error sqlCommand: SELECT * FROM merge_db('conv_check_1458766670_docx:
error: function merge_db(unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown) does not exist
    at Connection.parseE (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
[2018-05-10 13:05:31.638] [ERROR] nodeJS - Error convert: docId = conv_check_1458766670_docx
error: function merge_db(unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown) does not exist
    at Connection.parseE (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

**Comment by hamslicejumbomice** [comment]
It seems to be trying to run the "SELECT * FROM merge_db" sql command but its failing. I looked at my database and there isn't even a merge_db table so of course it's going to error out

**Comment by ShockwaveNN** [comment]
@hamslicejumbomice I'm not good at Windows servers, maybe your version of postres server is too old? Or try to drop DB for onlyoffice and reinit it

**Comment by hamslicejumbomice** [comment]
I am running 9.6 the next and newest version would be 10

**Comment by hamslicejumbomice** [comment]
Hi, I updated my postgresql to 10 and now i get the following errors in my log file:

[2018-05-14 09:26:21.893] [ERROR] nodeJS - sqlQuery error sqlCommand: INSERT INTO task_result (id, status, status_info, :
error: relation "task_result" does not exist
    at Connection.parseE (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
[2018-05-14 09:26:21.893] [ERROR] nodeJS - Error convert: docId = conv_check_1806320351_docx
error: relation "task_result" does not exist
    at Connection.parseE (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:567:11)
    at Connection.parseMessage (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:391:17)
    at Socket.<anonymous> (C:\Program Files\ONLYOFFICE\DocumentServer\server\docservice\node_modules\pg\lib\connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

**Comment by ShockwaveNN** [comment]
@hamslicejumbomice did you drop table and reinstall documentserver?

**Comment by ShockwaveNN** [comment]
@hamslicejumbomice yeah, try to remove onlyoffice-documentserver, drop base and install it again

**Comment by hamslicejumbomice** [comment]
I uninstalled the document server from my computer, dropped the database, then I reinstalled document server and created the database again. I got the same error listed above

**Comment by ShockwaveNN** [comment]
@hamslicejumbomice sad to hear, I contacted develop team, maybe they have some ideas

**Comment by hamslicejumbomice** [comment]
Thank you! I appreciate your willingness to help. I am just clueless what could be going wrong, these log files don't give me much information it seems

**Comment by hamslicejumbomice** [comment]
Hi @agolybev, So I uninstalled documentserver again and I'm sitting here with the setup program waiting for it to run again. I'm just confused on where I type those parameters in at?

**Comment by hamslicejumbomice** [comment]
Okay so I reinstalled the document server again and it worked!! It must've been a bad install after all but that was like the sixth time I installed it! 

However I'm going to be doing this again so before I close this ticket I still want to know how I can get that install file @agolybev !!

**Comment by MrMoronIV** [comment]
I'm getting the same error as you described here: 
https://github.com/ONLYOFFICE/DocumentServer/issues/354

How did you reinstall the server? Cause I tried yum reinstall but that changed nothing...

**Comment by ShockwaveNN** [comment]
I'm closing this issue. If problem still actual - please create new issue
