### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'IY')

### ISSUE THREAD

**Issue by AmilKey** [ONLYOFFICE/DocumentServer#2985]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

8.2

### Expected Behavior

document version file should load without error

### Actual Behavior

When I try to load the version history, error occurs and it keeps showing loading changes loader
In my docker logs

```
sdk-all-min.js:1489 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'IY')
    at bl.t7b (sdk-all-min.js:1489:310)
    at e.Bzh (sdk-all-min.js:220:48)
    at im.t7b (sdk-all-min.js:212:368)
    at f.FLd (sdk-all-min.js:237:488)
    at f.Aah (sdk-all-min.js:244:138)
    at f.I9g (sdk-all-min.js:243:404)
    at f.Y9g (sdk-all-min.js:251:222)
    at i.<anonymous> (sdk-all-min.js:251:89)
    at L.emit (socket.io.min.js:6:7123)
    at i.value (socket.io.min.js:6:34755)   
```

**Comment by TatianaKirillova** [comment]
@AmilKey Thank you for your request! What changes did you make to the file? And if possible, attach the file itself, please!

**Comment by AmilKey** [comment]
@TatianaKirillova open for editing, save changes and open again
[Dibbert, Sipes and Dare.docx](https://github.com/user-attachments/files/17720284/Dibbert.Sipes.and.Dare.docx)

**Comment by AmilKey** [comment]
@TatianaKirillova with each file, old file

**Comment by trofim24** [comment]
@AmilKey please, add the object that you send to [setHistoryData](https://api.onlyoffice.com/docs/docs-api/usage-api/methods/#sethistorydata) and attach the changesUrl zip-file.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
