### ISSUE TITLE
Timeout when using plugins

### ISSUE THREAD

**Issue by loicBillon** [ONLYOFFICE/DocumentServer#306]
Hello,

I have troubles with plugins like Youtube or cliparts, When I insert a youtube video, the spinner is still a long time on the screen, then I get a timeout on the documentserver out.log file.

Exemple with youtube, and with the photo editor :

```
[2018-05-22 11:36:41.762] [ERROR] nodeJS - error commandImgurls download: url = http://img.youtube.com/vi/j59tmHTiUJo/0.jpg; docId = ed42fe23-1a4f-4556-bbc4-ecaa34482078.1526979951280
Error: ETIMEDOUT
    at Timeout._onTimeout (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:846:19)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)




[2018-05-22 11:46:57.160] [ERROR] nodeJS - error commandImgurls download: url = https://s3.amazonaws.com/feather-client-files-aviary-prod-us-east-1/2018-05-22/845dad99-be04-4899-af06-37ee7430f08f.png; docId = ed42fe23-1a4f-4556-bbc4-ecaa34482078.1526979951280
Error: ETIMEDOUT
    at Timeout._onTimeout (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:846:19)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
```

I'm behind a corporate proxy and I'm not sure how it should be parametrized. I tried the following :
- set http_proxy and https_proxy environment variables (but which unix users should see this vars ? Global configuration or local ?)
- set a nodejs configuration with "npm config set proxy http://theproxy:3128" and npm config set https-proxy http://theproxy:3128" (but which unix users should see this vars ? I setted it to onlyoffice user and root user)

To reproduce, simply create a new document, insert a youtube video. The expected behavior is the display of the thumbnail.

I have not been able to use the plugins in Docserver 5.0.x and 5.1.3

I run documentserver on RedHat 7, my browser is firefox but this behavior seems to be the same with Edge or other browsers.

Thanks a lot for your response.
Regards,

**Comment by ShockwaveNN** [comment]
Hi, seems this is a really-really old issue and we've missed it, sorry

Could you clarify if you still using our system and if this issue is still actual on latest stable v7.1.1?

If so I think it's more a problem in corporate proxy than in our application
