### ISSUE TITLE
error: function merge_db(unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown) does not exist

### ISSUE THREAD

**Issue by MrMoronIV** [ONLYOFFICE/DocumentServer#354]
Trying to open a file from Seafile, I get "Loading document" all the time,

I found an error in the out.log file:
```
[2018-07-25 15:14:58.349] [ERROR] nodeJS - sqlQuery error sqlCommand: SELECT * FROM merge_db('a9864f6f52a960be0f4c', '0':
error: function merge_db(unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown) does not exist
    at Connection.parseE (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
[2018-07-25 15:14:58.350] [ERROR] nodeJS - error receiving response: docId = undefined type = auth
error: function merge_db(unknown, unknown, unknown, unknown, unknown, unknown, unknown, unknown) does not exist
    at Connection.parseE (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
```
The same error is shown twice for one doc opening attempt.
Any idea how to fix this?

Centos 7, pure install, no docker, nodejs 6.14 (default yum install)

version 5.1.5-59

**Comment by ShockwaveNN** [comment]
What is postgresql version and try to rerun `bash documentserver-configure.sh` again

**Comment by MrMoronIV** [comment]
`bash documentserver-configure.sh` fixed it.... thank you
