### ISSUE TITLE
SpellChecker change service port

### ISSUE THREAD

**Issue by supercompman** [ONLYOFFICE/DocumentServer#400]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The SpellChecker server consumes a substantial amount of CPU resources at all times. When using Document Server 5.1.5, this is not the behaviour I observed.

![image](https://user-images.githubusercontent.com/7391395/46589946-080f3980-ca75-11e8-8024-e0b5e1e8c646.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Upgrade from Document Server 5.1.5 to 5.2.2

**What is the expected behavior?**
SpellChecker server should be consuming nearly no resources when not in use.

**Did this work in previous versions of DocumentServer?**
Yes.

**DocumentServer version:**
5.2.2

**Operating System:**
Ubuntu Server 18.04.1

**Browser version:**
Not browser related.

**Comment by ShockwaveNN** [comment]
Is there any strange activity in logs?
`/var/log/onlyoffice/documentserver/spellchecker/`

**Comment by supercompman** [comment]
I've looked at the out.log and I'm certainly seeing issues:
[2018-10-08 13:49:58.599] [WARN] nodeJS - start cluster with 1 workers
[2018-10-08 13:49:58.609] [WARN] nodeJS - worker 19444 started.
[2018-10-08 13:49:59.706] [WARN] nodeJS - Express server starting...
[2018-10-08 13:49:59.781] [ERROR] nodeJS - Mon, 08 Oct 2018 13:49:59 GMT uncaughtException: bind EADDRINUSE null:8080
[2018-10-08 13:49:59.782] [ERROR] nodeJS - Error: bind EADDRINUSE null:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at listenOnMasterHandle (net.js:1427:16)
    at rr (internal/cluster/child.js:121:12)
    at Worker.send (internal/cluster/child.js:88:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
[2018-10-08 13:49:59.788] [WARN] nodeJS - worker 19444 died (code = 1; signal = null). restart...
[2018-10-08 13:50:00.864] [WARN] nodeJS - Express server starting...
[2018-10-08 13:50:00.933] [ERROR] nodeJS - Mon, 08 Oct 2018 13:50:00 GMT uncaughtException: bind EADDRINUSE null:8080
[2018-10-08 13:50:00.934] [ERROR] nodeJS - Error: bind EADDRINUSE null:8080
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at listenOnMasterHandle (net.js:1427:16)
    at rr (internal/cluster/child.js:121:12)
    at Worker.send (internal/cluster/child.js:88:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)

Then the log just begins repeating itself saying that the worker died and "Express server starting...".

I have nginx configured to use port 8080 for regular HTTP requests and port 8443 for HTTPS requests. This server also has an apache instance already using ports 80 and 443, so those can't be used for onlyoffice.

**Comment by ShockwaveNN** [comment]
You can try to change spellchecker port in `/etc/onlyoffice/documentserver/default.json` but we never test this

**Comment by supercompman** [comment]
I just changed which port nginx is using for HTTP requests. Everything seems to be working fine now. Thanks for your help.
