### ISSUE TITLE
5.2.4 fails to start ("log.options.replaceConsole" is not defined)

### ISSUE THREAD

**Issue by himpierre** [ONLYOFFICE/DocumentServer#453]
Hello Devs.

After updating to 5.2.4 the document server does not start anymore. Error message:

`
Error: Configuration property "log.options.replaceConsole" is not defined
    at Config.get (/var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/sources/logger.js:19:12)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/sources/server.js:14:16)
/var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:203
    throw new Error('Configuration property "' + property + '" is not defined');
    ^
`

**Did this work in previous versions of DocumentServer?**

Yes.

**DocumentServer version:** 5.2.4

**Operating System:** Ubuntu 18.04

**Browser version:** Firefox 60

thanks and cheers

**Comment by himpierre** [comment]
ok. i had to add:

`
              "options": {
                       "replaceConsole": true
               }
`

to default.json. Sorry for the noise.
