### ISSUE TITLE
Opera browser cannot open documents

### ISSUE THREAD

**Issue by zkryakgul** [ONLYOFFICE/DocumentServer#458]
When we updated to latest version of document server then this error occurred. Same document is successfully opening on chrome and chromium but on opera which is build on chrome, following errors occurred.

Document Server Log
```
documentserver_1       | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
documentserver_1       | [2018-12-19T06:49:40.685] [ERROR] nodeJS - changesError: docId = e5079b575170fe6b6510 Error: Uncaught TypeError: Cannot read property 'tua' of undefined Script: https://demo.test.io/office/v5.2.3-64/sdkjs/word/sdk-all.js Line: 1255:508 userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.102 platform: Linux x86_64 isLoadFullApi: false isDocumentLoadComplete: false StackTrace: TypeError: Cannot read property 'tua' of undefined
documentserver_1       |     at https://demo.test.io/office/v5.2.3-64/sdkjs/word/sdk-all.js:1255:508
documentserver_1       |     at https://demo.test.io/office/v5.2.3-64/sdkjs/word/sdk-all.js:1826:502
documentserver_1       |     at https://demo.test.io/office/v5.2.3-64/sdkjs/word/sdk-all.js:10063:448
documentserver_1       | [2018-12-19T06:50:49.463] [ERROR] nodeJS - changesError: docId = e5079b575170fe6b6510 Error: Uncaught TypeError: Cannot read property 'tua' of undefined Script: https://demo.test.io/office/v5.2.3-64/sdkjs/word/sdk-all.js Line: 1255:508 userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 OPR/57.0.3098.102 platform: Linux x86_64 isLoadFullApi: false isDocumentLoadComplete: false StackTrace: TypeError: Cannot read property 'tua' of undefined
documentserver_1       |     at https://demo.test.io/office/v5.2.3-64/sdkjs/word/sdk-all.js:1255:508
documentserver_1       |     at https://demo.test.io/office/v5.2.3-64/sdkjs/word/sdk-all.js:1826:502
documentserver_1       |     at https://demo.test.io/office/v5.2.3-64/sdkjs/word/sdk-all.js:10063:448
documentserver_1       | 
documentserver_1       | ==> /var/log/onlyoffice/documentserver/metrics/out.log <==
documentserver_1       | Flushing stats at  Wed Dec 19 2018 06:50:54 GMT+0000 (UTC)
documentserver_1       | { counters: 
documentserver_1       |    { 'statsd.bad_lines_seen': 0,
documentserver_1       |      'statsd.packets_received': 0,
documentserver_1       |      'statsd.metrics_received': 0 },
documentserver_1       |   timers: {},
documentserver_1       |   gauges: { 'statsd.timestamp_lag': 0 },
documentserver_1       |   timer_data: {},
documentserver_1       |   counter_rates: 
documentserver_1       |    { 'statsd.bad_lines_seen': 0,
documentserver_1       |      'statsd.packets_received': 0,
documentserver_1       |      'statsd.metrics_received': 0 },
documentserver_1       |   sets: {},
documentserver_1       |   pctThreshold: [ 90 ] }
```

Browser Console Error
![image](https://user-images.githubusercontent.com/16170648/50204284-4d08f380-0375-11e9-90b0-db79a069a512.png)

Opera Version
![image](https://user-images.githubusercontent.com/16170648/50204202-0f0bcf80-0375-11e9-81fb-8a08139742f9.png)

**Comment by Rita-Bubnova** [comment]
Hello, @zkryakgul.
Can you attach a file that leads to an error?

**Comment by zkryakgul** [comment]
Here it is:
[test_document.docx](https://github.com/ONLYOFFICE/DocumentServer/files/2693921/test_document.docx)

**Comment by ShockwaveNN** [comment]
@zkryakgul Hi, we were not able to reproduce your problem on latest opera with latest DocumentServer. Are you sure you send correct file? Also you do not fill out issue template correclty, but from errors i see you're using DocumentServer 5.2.3 which is not the latest DocumentServer. Please upgrade and try again.

**Comment by zkryakgul** [comment]
![image](https://user-images.githubusercontent.com/16170648/50267448-5018e800-0438-11e9-877d-d64f2334d682.png)

Hi, today an upgrade is released on opera and after last update, issue is fixed.
