### ISSUE TITLE
Callback url not called to storage service with signed jwt token

### ISSUE THREAD

**Issue by falling-star** [ONLYOFFICE/DocumentServer#472]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
In DocumentServer Develoer Edition release - 5.2.6, we see error attached below while signing jwt token **(Note: jwt token inBody for outbox is enabled).**
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

<img width="641" alt="screenshot 2019-01-11 at 6 16 06 pm" src="https://user-images.githubusercontent.com/3634908/51034844-1027c980-15ce-11e9-94ce-c12de026c85b.png">

<img width="1438" alt="screenshot 2019-01-11 at 6 15 29 pm" src="https://user-images.githubusercontent.com/3634908/51034845-1027c980-15ce-11e9-8069-803360077bad.png">

**What is the expected behavior?**
Callback url should be able to send request to storage service with signed jwt token.
**Did this work in previous versions of DocumentServer?**
Earlier we had version 5.1.2
**DocumentServer version:**
5.2.6
**Operating System:**
CentOS 7
**Browser version:**
Chrome latest

node --version -> v8.15.0
npm --version -> 6.4.1

**Comment by falling-star** [comment]
Please see attached error logs -

`[2019-01-11T12:47:29.740] [ERROR] nodeJS - postData error: docId = 8c5b6f93-3294-450d-989f-ffd3657010f5;url = https://local.veraeng.com/api/doc/edit/internal/upload?docEditId=93b94ffc-e5a3-3ac8-88a1-59a8fe2b798d;data = {"key":"8c5b6f93-3294-450d-989f-ffd3657010f5","status":4,"actions":[{"type":0,"userid":"mkyadav@vera.com"}]}^M
Error: Expected "payload" to be a plain object.
    at validate (/var/www/onlyoffice/documentserver/server/Common/node_modules/jsonwebtoken/sign.js:34:11)
    at validatePayload (/var/www/onlyoffice/documentserver/server/Common/node_modules/jsonwebtoken/sign.js:56:10)
    at Object.module.exports [as sign] (/var/www/onlyoffice/documentserver/server/Common/node_modules/jsonwebtoken/sign.js:108:7)
    at Object.fillJwtForRequest (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:728:14)
    at sendServerRequest (/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:540:18)
    at sendServerRequest.next (<anonymous>)
    at sendStatusDocument (/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:787:24)
    at sendStatusDocument.next (<anonymous>)
    at cleanDocumentOnExitNoChanges (/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:892:10)
    at cleanDocumentOnExitNoChanges.next (<anonymous>)
    at closeDocument (/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:1256:20)
    at closeDocument.next (<anonymous>)
    at /var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:1163:18
    at Generator.next (<anonymous>)
    at onFulfilled (/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:65:19)
    at <anonymous>`

**Comment by falling-star** [comment]
@konovalovsergey @alexanderonlyoffice  If we replace opt_payload -> JSON.parse(JSON.stringify(opt_payload) in fillJwtForRequest function (in server/Common/sources/utils.js), it fixes the issue. Please see attached image below for reference -

<img width="1148" alt="screenshot 2019-01-11 at 8 38 08 pm" src="https://user-images.githubusercontent.com/3634908/51041916-f5ab1b80-15e0-11e9-8475-0a33e7753588.png">


Please let us know if this is the case and what is the plan to release this fix quickly as it breaks the editing flow completely.

**Comment by falling-star** [comment]
Seems like the issue is caused by upgrading jsonwebtoken from V7 to V8. More at - https://github.com/auth0/node-jsonwebtoken/issues/403
