### ISSUE TITLE
Integration with Seafile: could not save a file after editing

### ISSUE THREAD

**Issue by dbet1** [ONLYOFFICE/DocumentServer#486]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If I click the save button I receive error -331

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the document, make a change and save it

**What is the expected behavior?**
Saving without an error

**Did this work in previous versions of DocumentServer?**
I don't know, I am trying the first time

**DocumentServer version:**
5.2.6

**Operating System:**
Ubuntu 16.04.5

**Browser version:**
Firefox 64.0.2 (64-Bit)

**Comment by dbet1** [comment]
In docservice/out.log I found the following:

[2019-01-25T08:29:12.766] [ERROR] nodeJS - sendServerRequest error: docId = 7b3ba124b8460f868889;url = https://seafile.example.com/onlyoffice/editor-callback/;data = {"key":"7b3ba124b8460f868889","status":6,"url":"https://seafile.example.com/onlyofficeds/cache/files/7b3ba124b8460f868889_5685/output.xlsx/output.xlsx?md5=UQ3LuXXUELdiWAythBSI-Q==&expires=1548405853&disposition=attachment&ooname=output.xlsx","changesurl":"https://seafile.example.com/onlyofficeds/cache/files/7b3ba124b8460f868889_5685/changes.zip/changes.zip?md5=OcWStRB6vMC1vPfbBZ5fyw==&expires=1548405853&disposition=attachment&ooname=output.zip","history":{"serverVersion":"5.2.6","changes":[{"created":"2019-01-25 08:25:42","user":{"id":"uid-1548404649378","name":"user"}}]},"users":["uid-1548404649378"],"lastsave":"2019-01-25T08:28:41.425Z","forcesavetype":1}
Error: Error response: statusCode:500 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Page unavailable</title>
</head>
<body>
    <h1>Page unavailable</h1>

    <p>Sorry, but the requested page is unavailable due to a server hiccup.</p>

    <p>Our engineers have been notified, so check back later.</p>
</body>
</html>

    at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:283:18)
    at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
![fehler -331](https://user-images.githubusercontent.com/25152031/51739696-6434b280-2092-11e9-800c-1261e60ad25d.png)

**Comment by dbet1** [comment]
I didn't find any useful information in the internet. Could you help me?

**Comment by ShockwaveNN** [comment]
```
statusCode:500 ;body:

<title>Page unavailable</title>
```
Seems this is a answer from `Seafile` if I understand correctly. Did you write connect for Seafile by yourself? Seems issue not on our side

**Comment by dbet1** [comment]
No I don't write a connector for Seafile. I am using only its integration. From Seafile I have no answer until today.
I do not understand which page is requested at this moment.

**Comment by ShockwaveNN** [comment]
@dbet1 We think problem on Seafile side and we have no experience with it and do not support it officially. So I think you should contact their support
