### ISSUE TITLE
Upragde onlyoffice too 5.3.0

### ISSUE THREAD

**Issue by tanguy-opendsi** [ONLYOFFICE/DocumentServer#585]
Hi 
I have a onlyoffice cluster with external redis, rabbitmq and postgresql
when i upgrade onlyoffice. i got this error inside  /var/log/onlyoffice/documentserver/docservice/err.log

Error: Configuration property "services.CoAuthoring.callbackBackoffOptions" is not defined
    at Config.get (/var/www/onlyoffice/documentserver/server/DocService/node_modules/config/lib/config.js:203:11)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/sources/canvasservice.js:44:42)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:32:23)

My node js version
nodejs -v
v11.15.0

best regards

**Comment by ShockwaveNN** [comment]
Seems some config is incorrectly updated.
Please add section about `callbackBackoffOptions` in your config like this
https://github.com/ONLYOFFICE/server/blob/master/Common/config/default.json#L203

**Comment by tanguy-opendsi** [comment]
Thx for reply ofc i use the new default template and it's work 
but i have another log :
Error: The module '/var/www/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/SpellChecker/sources/spellCheck.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by ShockwaveNN** [comment]
Second one is unrelated to your first issue. See https://github.com/ONLYOFFICE/DocumentServer/issues/312#issuecomment-392479211
