### ISSUE TITLE
Question about Onlyoffice as cluster with external ressources

### ISSUE THREAD

**Issue by tanguy-opendsi** [ONLYOFFICE/DocumentServer#598]
Hi we actualy have 3 onlyoffice document server on debian9 system. 
In front to onlyoffice we have haproxy configured with load balancing mode (roundrobin)

We want use onlyoffice with redis cluster and rabbitmq cluster.

My question is : 
How can i configure onlyoffice with rabbitmq cluster, and redis 
Actualy we just have only one server target.

For exemple in onlyoffice configuration we have
 "rabbitmq": {
    "url": "amqp://onlyoffice:onlyoffice@192.168.0.81/onlyoffice"
  },

      "redis": {
        "host": "192.168.0.21"
      },
Best regards

**Comment by ShockwaveNN** [comment]
@tanguy-opendsi Hi, to be clear, you want to be able to setup several `rabbitmq` or several `redis` servers in ONLYOFFICE DocumentServer config?

**Comment by tanguy-opendsi** [comment]
@ShockwaveNN 
yes sorry if i'm not clear.

**Comment by ShockwaveNN** [comment]
@tanguy-opendsi We use `node_redis` library for redis and it's currently not support clustering, see https://github.com/NodeRedis/node_redis/issues/574

About rabbitmq - you can try to figure it out by yourself via https://www.rabbitmq.com/clustering.html#clustering-and-clients, but we got no working instruction for this

**Comment by tanguy-opendsi** [comment]
@ShockwaveNN 
Thx for reply.
I think the best way to do a real load balancing HA onlyoffice app is to provide a floating ip directly on our servers using peacemaker or something else.

**Comment by bozicm** [comment]
> @tanguy-opendsi We use `node_redis` library for redis and it's currently not support clustering, see [NodeRedis/node-redis#574](https://github.com/NodeRedis/node-redis/issues/574)
> 

Have you thought about replacing it with [ioredis](https://github.com/luin/ioredis)?

**Comment by CallumDowling** [comment]
Any update on this ?

**Comment by ShockwaveNN** [comment]
Sorry no news about the original issue

But now we provide [k8s](https://github.com/ONLYOFFICE/Kubernetes-Docs) version of DocumentServer, maybe this may help

**Comment by grischdian** [comment]
since a few months have passed by - any news on this?

**Comment by DodoLeDev** [comment]
The [blocking issue](https://github.com/redis/node-redis/issues/574) has been solved. Any update on this?

I've tried to deploy it with a redis cluster, and I faced the following error:
`[ERROR] [docId] [userId] nodeJS - License: MOVED 12345 1.2.3.4:6379`

What I see is that when requested, the redis node replies to OO by saying that _"this data is in another castle"_, and giving the IP of the new location of that data.
OnlyOffice then considers it as an error, while it should instead retry to request that data against the provided node IP.

If you consider implementing this feature, take a look at [this little wrapper](https://github.com/gosquared/redis-clustr), that just tries to [transparently apply that task (among others)](https://github.com/gosquared/redis-clustr#supported-functionality)

**Comment by Rita-Bubnova** [comment]
@igwyd, take a look, please.

**Comment by igwyd** [comment]
Hello @DodoLeDev, we support connection to the redis cluster via the redis or ioredis connector, config examples:
redis:
```
{
  "services": {
    "CoAuthoring": {
      "redis": {
        "name": "redis",
        "optionsCluster": {
          "rootNodes": [
            {"url": "redis://192.168.0.150:7000"},
            {"url": "redis://192.168.0.150:7001"},
            {"url": "redis://192.168.0.150:7002"}
          ],
          "defaults": {
            "username": "default",
            "password": "TEst123"
          }
        }
      }
    }
  }
}
```
ioredis
```
{
  "services": {
    "CoAuthoring": {
      "redis": {
        "name": "ioredis",
        "iooptionsClusterNodes": [
          { "host": "192.168.0.150", "port": 7000 },
          { "host": "192.168.0.150", "port": 7001 },
          { "host": "192.168.0.150", "port": 7002 }
        ],
        "iooptionsClusterOptions": {
          "redisOptions": {
            "password": "TEst123"
          }
        }
      }
    }
  }
}
```

**Comment by DodoLeDev** [comment]
Thanks @igwyd for your reply, it seems to work when leader nodes are behind a single DNS resolution, but I am now facing this error:

```
[ERROR] [docId] [userId] nodeJS - License: TypeError: Cannot read properties of undefined (reading 'master')                                                                             
    at RedisClusterSlots.getClient (/snapshot/server/DocService/node_modules/@redis/client/dist/lib/cluster/cluster-slots.js:108:59)                                                                               
    at Commander._RedisCluster_execute (/snapshot/server/DocService/node_modules/@redis/client/dist/lib/cluster/index.js:217:79)                                                                                   
    at Commander.sendCommand (/snapshot/server/DocService/node_modules/@redis/client/dist/lib/cluster/index.js:129:98)                                                                                             
    at Commander.commandsExecutor (/snapshot/server/DocService/node_modules/@redis/client/dist/lib/cluster/index.js:126:75)                                                                                        
    at Commander.HSET (/snapshot/server/DocService/node_modules/@redis/client/dist/lib/commander.js:8:29)                                                                                                          
    at polyfillHset (/snapshot/server/DocService/sources/editorDataRedis.js)                                                                                                                                       
    at EditorStat.<anonymous> (/snapshot/server/DocService/sources/editorDataRedis.js)                                                                                                                             
    at EditorStat.setLicense (/snapshot/server/DocService/sources/editorDataRedis.js)                                                                                                                              
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                                                  
    at async _updateFileState (/snapshot/server/Common/sources/license.js)    
```

Don't know if it's related or if it should belong to another issue...

**Comment by igwyd** [comment]
Hello @DodoLeDev looks like there's a issue with reading the license. I think it's a different, but it might be related to this one. Please contact our support team so we can check it https://www.onlyoffice.com/support-contact-form.
