### ISSUE TITLE
can not connect owncloud and DocumnetServer

### ISSUE THREAD

**Issue by xlangyun** [ONLYOFFICE/DocumentServer#626]
Do you want to request a feature or report a bug?

What is the current behavior?
/var/log/onlyoffice/documentserver/converter/out.log
[2019-08-12T21:48:03.765] [ERROR] nodeJS - error downloadFile:url=http://10.10.10.223/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.FZwXATHSHK9nqy8GCbVmXkTA8QkkvZ7Mvn89diwM_Hk;attempt=3;code:null;connect:null;(id=conv_check_284448135_docx)^M
Error: Error response: statusCode:403 ;body:^M
{"message":"Access denied"}
at Request._callback (/var/www/onlyoffice/documentserver/server/Common/sources/utils.js:256:18)
at Request.self.callback (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:185:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request. (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1161:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage. (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1083:12)
at IncomingMessage.g (events.js:292:16)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:185:7)
at endReadableNT (_stream_readable.js:978:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)

[2019-08-12T22:03:47.609] [WARN] nodeJS - worker 66528 died (code = 1; signal = null). restart...
[2019-08-12T22:03:48.047] [WARN] nodeJS - worker 66536 died (code = 1; signal = null). restart...
[2019-08-12T22:03:48.805] [WARN] nodeJS - worker 66542 died (code = 1; signal = null). restart...
[2019-08-12T22:03:49.622] [WARN] nodeJS - worker 66549 died (code = 1; signal = null). restart...
[2019-08-12T22:03:50.250] [WARN] nodeJS - worker 66555 died (code = 1; signal = null). restart...
[2019-08-12T22:03:50.974] [WARN] nodeJS - worker 66561 died (code = 1; signal = null). restart...
[2019-08-12T22:03:51.395] [WARN] nodeJS - worker 66567 died (code = 1; signal = null). restart...
[2019-08-12T22:03:51.874] [WARN] nodeJS - worker 66573 died (code = 1; signal = null). restart...
[2019-08-12T22:03:52.292] [WARN] nodeJS - worker 66579 died (code = 1; signal = null). restart...
[2019-08-12T22:03:52.815] [WARN] nodeJS - worker 66585 died (code = 1; signal = null). restart...
[2019-08-12T22:03:53.272] [WARN] nodeJS - worker 66591 died (code = 1; signal = null). restart...
[2019-08-12T22:03:53.798] [WARN] nodeJS - worker 66597 died (code = 1; signal = null). restart...
[2019-08-12T22:03:54.374] [WARN] nodeJS - worker 66603 died (code = 1; signal = null). restart...
[2019-08-12T22:03:54.905] [WARN] nodeJS - worker 66610 died (code = 1; signal = null). restart...
[2019-08-12T22:03:55.364] [WARN] nodeJS - worker 66616 died (code = 1; signal = null). restart...
[2019-08-12T22:03:55.783] [WARN] nodeJS - worker 66622 died (code = 1; signal = null). restart...
[2019-08-12T22:03:56.210] [WARN] nodeJS - worker 66628 died (code = 1; signal = null). restart...
[2019-08-12T22:03:56.715] [WARN] nodeJS - worker 66634 died (code = 1; signal = null). restart...
[2019-08-12T22:03:57.162] [WARN] nodeJS - worker 66640 died (code = 1; signal = null). restart...
[2019-08-12T22:03:57.639] [WARN] nodeJS - worker 66646 died (code = 1; signal = null). restart...
[2019-08-12T22:03:58.043] [WARN] nodeJS - worker 66654 died (code = 1; signal = null). restart...
[2019-08-12T22:03:58.458] [WARN] nodeJS - worker 66660 died (code = 1; signal = null). restart...
[2019-08-12T22:03:58.908] [WARN] nodeJS - worker 66666 died (code = 1; signal = null). restart...
[2019-08-12T22:03:59.327] [WARN] nodeJS - worker 66672 died (code = 1; signal = null). restart..

Error: Module version mismatch. Expected 48, got 57.
at Error (native)
at Object.Module._extensions..node (module.js:604:18)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object. (/var/www/onlyoffice/documentserver/server/SpellChecker/sources/spellCheck.js:13:17)
at Module._compile (module.js:577:32)
at Object.Module._extensions..js (module.js:586:10)
module.js:604
return process.dlopen(module, path._makeLong(filename));

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

What is the expected behavior?

Did this work in previous versions of DocumentServer?

DocumentServer version:
My owncloud version is 10.0.0
I used this cmd to install DS yestoday(sudo yum install onlyoffice-documentserver).
Operating System:
Centos 7
Browser version:

**Comment by ShockwaveNN** [comment]
I moved your previous issue to https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/278
Please do not pos duplicates
