### ISSUE TITLE
Error Node.js Onlyoffice Document Server 

### ISSUE THREAD

**Issue by Zaimatunn31** [ONLYOFFICE/DocumentServer#672]
```
[2019-10-23T11:21:48.198] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2019-10-23T11:21:48.240] [WARN] nodeJS - update cluster with 1 workers
[2019-10-23T11:21:48.280] [WARN] nodeJS - worker 16053 started.
[2019-10-23T11:21:48.280] [WARN] nodeJS - update cluster with 1 workers
[2019-10-23T11:21:49.178] [WARN] nodeJS - Express server starting...
[2019-10-23T11:21:51.725] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2019-10-23T11:30:03.724] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2019-10-23T11:30:03.772] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-10-23T11:30:03.976] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-10-23T11:30:04.318] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-10-23T11:30:04.898] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-10-23T11:30:05.882] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-10-23T11:30:07.655] [WARN] nodeJS - update cluster with 1 workers
[2019-10-23T11:30:07.669] [WARN] nodeJS - worker 1572 started.
[2019-10-23T11:30:07.672] [WARN] nodeJS - update cluster with 1 workers
[2019-10-23T11:30:08.812] [WARN] nodeJS - Express server starting...
[2019-10-23T11:30:12.882] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-23T11:30:13.884] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-23T11:30:14.886] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-23T11:30:15.888] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-23T11:30:17.019] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2019-10-23T12:11:19.502] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2019-10-23T12:11:19.580] [WARN] nodeJS - update cluster with 1 workers
[2019-10-23T12:11:19.628] [WARN] nodeJS - worker 4343 started.
[2019-10-23T12:11:19.628] [WARN] nodeJS - update cluster with 1 workers
[2019-10-23T12:11:21.744] [WARN] nodeJS - Express server starting...
[2019-10-23T12:11:22.719] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2019-10-23T12:12:24.604] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2019-10-23T12:12:24.693] [WARN] nodeJS - update cluster with 1 workers
[2019-10-23T12:12:24.747] [WARN] nodeJS - worker 4458 started.
[2019-10-23T12:12:24.747] [WARN] nodeJS - update cluster with 1 workers
[2019-10-23T12:12:26.986] [WARN] nodeJS - Express server starting...
[2019-10-23T12:12:28.311] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2019-10-23T12:17:45.388] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2019-10-23T12:17:45.448] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-10-23T12:17:45.657] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-10-23T12:17:45.999] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2019-10-23T12:17:46.578] [ERROR] nodeJS - redisClient error Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
```

**Comment by ShockwaveNN** [comment]
Something wrong with your Redis connection. Please fill issue template correctly

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
