### ISSUE TITLE
nodeJS - [AMQP] Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by alex9434** [ONLYOFFICE/DocumentServer#674]
**report a *bug*?**

**What is the current behavior?**
Fresh onlyoffice installation only starts with white screen with message "Document Server is running". No access to document server possible.

Installation according to the following instructions:
https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx

/mnt/container/lxc/onlyoffice/rootfs/var/log/onlyoffice/documentserver/docservice/out.log shows the following error:
```
[2019-10-27T03:19:22.980] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2019-10-27T03:19:23.033] [WARN] nodeJS - update cluster with 1 workers
[2019-10-27T03:19:23.063] [WARN] nodeJS - worker 1042 started.
[2019-10-27T03:19:23.064] [WARN] nodeJS - update cluster with 1 workers
[2019-10-27T03:19:25.252] [WARN] nodeJS - Express server starting...
[2019-10-27T03:19:27.247] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-27T03:19:28.254] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-27T03:19:29.257] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-27T03:19:30.260] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-27T03:19:31.263] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-27T03:19:32.266] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2019-10-27T03:19:33.483] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode

```
RabbitMQ is installed and seems to be working:
```
nc -v localhost 5672
localhost [127.0.0.1] 5672 (amqp) open
```
rabbit@onlyoffice.log
```

=INFO REPORT==== 27-Oct-2019::03:19:29 ===
Starting RabbitMQ 3.6.6 on Erlang 19.2.1
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 27-Oct-2019::03:19:29 ===
node           : rabbit@onlyoffice
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config (not found)
cookie hash    : 7lw0oMkbF4WI1RHDLiSfiQ==
log            : /var/log/rabbitmq/rabbit@onlyoffice.log
sasl log       : /var/log/rabbitmq/rabbit@onlyoffice-sasl.log
database dir   : /var/lib/rabbitmq/mnesia/rabbit@onlyoffice

=INFO REPORT==== 27-Oct-2019::03:19:31 ===
Memory limit set to 3144MB of 7862MB total.

=INFO REPORT==== 27-Oct-2019::03:19:31 ===
Disk free limit set to 50MB

=INFO REPORT==== 27-Oct-2019::03:19:31 ===
Limiting to approx 924 file handles (829 sockets)

=INFO REPORT==== 27-Oct-2019::03:19:31 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 27-Oct-2019::03:19:32 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 27-Oct-2019::03:19:32 ===
Starting rabbit_node_monitor

=INFO REPORT==== 27-Oct-2019::03:19:32 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 27-Oct-2019::03:19:32 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 27-Oct-2019::03:19:32 ===
started TCP Listener on 127.0.0.1:5672

=INFO REPORT==== 27-Oct-2019::03:19:32 ===
Server startup complete; 0 plugins started.

=INFO REPORT==== 27-Oct-2019::03:19:32 ===
accepting AMQP connection <0.291.0> (127.0.0.1:35480 -> 127.0.0.1:5672)

=INFO REPORT==== 27-Oct-2019::03:19:33 ===
accepting AMQP connection <0.312.0> (127.0.0.1:35486 -> 127.0.0.1:5672)

=INFO REPORT==== 27-Oct-2019::03:19:33 ===
accepting AMQP connection <0.332.0> (127.0.0.1:35488 -> 127.0.0.1:5672)

=INFO REPORT==== 27-Oct-2019::03:27:58 ===
accepting AMQP connection <0.368.0> (127.0.0.1:35692 -> 127.0.0.1:5672)

=INFO REPORT==== 27-Oct-2019::03:27:58 ===
closing AMQP connection <0.368.0> (127.0.0.1:35692 -> 127.0.0.1:5672)

=INFO REPORT==== 27-Oct-2019::03:34:24 ===
accepting AMQP connection <0.377.0> (127.0.0.1:35868 -> 127.0.0.1:5672)
```

**DocumentServer version:**
5.4
**Operating System:**
Debian Stretch
**Browser version:**
Firefox 70.0

**Comment by ShockwaveNN** [comment]
Hi, i checked installation on Debian 9 using this Docker Image
https://github.com/onlyoffice-testing-robot/documentserver-install-from-manual/blob/master/Debian-9/Dockerfile
And everything seems fine for me, RabbitMQ logs looks same, `docservice` log have no error.
Maybe it some permission or firewall issue?

**Comment by alex9434** [comment]
Probably it was. I managed to get it working after some try and error. Unfortunately I cannot replicate the error. I will therefore close this. Thank you for getting back.

**Comment by Celestialdeath99** [comment]
I am having the same issue. I have disabled all firewalls and permissions for the networks and have verified the port it open and RabbitMQ is listening same as above. I am running this is a Debian 9 container LXC container on a Proxmox VE server. I am able to access the web page and it shows a green check saying that the service is running. Running `supervisorctl status all` produces the following, and nothing else is in the logs besides the error `Error: connect ECONNREFUSED 127.0.0.1:5672 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)`
```
root@docs:~# supervisorctl status all
ds:converter                     RUNNING   pid 911, uptime 0:24:04
ds:docservice                    RUNNING   pid 910, uptime 0:24:04
ds:gc                            RUNNING   pid 909, uptime 0:24:05
ds:metrics                       RUNNING   pid 907, uptime 0:24:05
ds:spellchecker                  RUNNING   pid 908, uptime 0:24:05

At this point I have been trying and failing to get it to work. @alex9434 Do you know what you did that got it to work?

**Comment by alex9434** [comment]
Hi @Celestialdeath99, I also run this in an LXC container. I was orginally on Debian 10 when I had the error. I then re-installed on Debian 9 (or in my case Devuan 9) and everything is OK now. It might be the version of RabbitMQ, that is causing the issue.

**Comment by voicenoise** [comment]
have a similar thing on ubuntu 18.04 by updating the system..

```
Preparing for shutdown, it can take a lot of time, please wait...[2020-03-09T12:30:15.690] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```
and now a endless loop since hours:
```
[2020-03-09T12:30:16.700] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
[2020-03-09T12:30:17.704] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```

**Comment by CAMR0** [comment]
@voicenoise same here

**Comment by ShockwaveNN** [comment]
@voicenoise  @CAMR0 Please create a new issue for your problem
