### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by VivienZhai** [ONLYOFFICE/DocumentServer#687]
I have deployed DocumentServer in my Centos virtual machine, then I deploy a java example which is shown in the official website. But I find when I try to create sample spreadsheet, an error occured. How can I fix it?

**Comment by VivienZhai** [comment]
nodeJS - sqlQuery error sqlCommand: INSERT INTO task_result (id, status, status_info, :^M
error: syntax error at or near "ON"
    at Connection.parseE (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:121:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)

**Comment by ShockwaveNN** [comment]
@VivienZhai Does this error happens with other test example, for example NodeJS (our most feature full example). What restult show `http://localhost/healthcheck` of DocumentServer?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by ltdaydo** [comment]
hi @ShockwaveNN  i have the same problem
I check https://localhost/healthcheck result  return that "true"
you have any suggestion for me :(

**Comment by ShockwaveNN** [comment]
@ltdaydo Hi, please create new issue and describe your problem with more details, note OS, documentserver version and other stuff in issue template
