### ISSUE TITLE
Error when trying to connect (Error occurred in the document service: Invalid token)

### ISSUE THREAD

**Issue by ltdaydo** [ONLYOFFICE/DocumentServer#738]
Hi everyone
I'm install nextCloud (ver 17.0.2) and Document Server (Onlyoffice ver 5.4.2.46) on 2 servers different (CentOS 8 and 7)
Both of them using LetsEncrypt ssl certificate.
I'm check Document Server by link "https://localhost/healthcheck/", it's return result is "true".
When i'm connect to ONLYOFFICE from nextCloud to be faul: "Error when trying to connect (Error occurred in the document service: Invalid token)"

**
Below the log of Document Server:
[root@onlyoffice ~]# tail -f /var/log/onlyoffice/documentserver/docservice/out.log 
[2020-01-08T09:48:47.943] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2020-01-08T09:48:47.966] [WARN] nodeJS - update cluster with 1 workers
[2020-01-08T09:48:47.981] [WARN] nodeJS - worker 1316 started.
[2020-01-08T09:48:47.982] [WARN] nodeJS - update cluster with 1 workers
[2020-01-08T09:48:48.797] [WARN] nodeJS - Express server starting...
[2020-01-08T09:48:50.360] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2020-01-08T09:48:51.369] [ERROR] nodeJS - [AMQP] Error: connect ECONNREFUSED 127.0.0.1:5672
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
[2020-01-08T09:48:52.530] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
***
I'm check RabbitMQ on Document server, it;s still running. 
________
Anyone have suggestion for me
Thanks so much

**Comment by ToBigToSmall** [comment]
I does't know surely, but try to use 192.168.xx.xx instead 127.0.0.1:xxx

**Comment by ltdaydo** [comment]
> I does't know surely, but try to use 192.168.xx.xx instead 127.0.0.1:xxx

Your mean is edit file /etc/hosts on Document Server ?

**Comment by ToBigToSmall** [comment]
I found a problem like this but not next-cloud. 
![image](https://user-images.githubusercontent.com/33725817/72036858-17fc7580-32d7-11ea-90af-1410caed37e6.png)

if i use 127.0.0.1:80/ConvertService.ashx it will occur the problem like this. If i use http://192.168.1.137:80/ConvertService.ashx it will work fine

**Comment by ltdaydo** [comment]
> I found a problem like this but not next-cloud.
> ![image](https://user-images.githubusercontent.com/33725817/72036858-17fc7580-32d7-11ea-90af-1410caed37e6.png)
> 
> if i use 127.0.0.1:80/ConvertService.ashx it will occur the problem like this. If i use http://192.168.1.137:80/ConvertService.ashx it will work fine

can you show the name and location of this file, please

**Comment by ToBigToSmall** [comment]
this is a service for document server. it different from your service. I just mean you should make your every service contact by LAN（局域网） but not ip is localhost

**Comment by jasgggit** [comment]
Hi, I'm trying to integrate Onlyoffice with my Nextcloud 19 but I'm also getting this message, and since I'm new to Docker I cannot figure out what is wrong.

These are 2 separate servers. one has the Nextcloud parked on a Virtualmin Web Server and the OnlyOffice Workspace version is on a Ubuntu 20.04 server.
I've installed the ONO using the provided script, witwout the mail service.
I can find the 'local.json' file on the Docker containers, using 'find' command, and tried the 'secret' that is mentioned on them, but without any success.
The Docker is starting automatically but I'm not finding the starting service for it, yet.

Can you help figuring this out?
Thanks in advance.
JG

**Comment by ShockwaveNN** [comment]
@jasgggit I don't think your problem is related to this issue, could you create a completly new issue

**Comment by jasgggit** [comment]
Sure, thanks.

**Comment by igwyd** [comment]
Hello @ltdaydo, sorry for the late reply. Is your issue still relevant? I see the versions of the application are out of date, could you install new versions and check the connection?
