### ISSUE TITLE
Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)

### ISSUE THREAD

**Issue by Sagittarius-B** [ONLYOFFICE/DocumentServer#753]
Hi guys,
I'm having troubles connecting the onlyoffice document server to nextcloud on centos 7
I have a functionnal https nextcloud v.17 + onlyoffice 5.4.2 running on the same server, with CA signed certificates.
I looked online, applied some fixes such as rejectUnauthorized to false but the problem persists.

It appears to be a problem with the version of nodejs but upgrading to v10+ doesn't resolve the issue

Here's the onlyoffice/docservice/out.log : 
```
 [ERROR] nodeJS - sqlQuery error sqlCommand: INSERT INTO task_result (id, status, status_info, :
error: syntax error at or near "ON"
    at Connection.parseE (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:606:11)
    at Connection.parseMessage (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/var/www/onlyoffice/documentserver/server/DocService/node_modules/pg/lib/connection.js:123:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:559:20)
```
And the converter/out.log: 
```
[ERROR] nodeJS - error downloadFile:url=https://SERVERNAME/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.a2kHYzhPEIU9P2gh3NHYLyfR5M42aUyjVW3Z6H_vIvE;attempt=1;code:null;connect:null;(id=conv_check_1890143143_docx)
TypeError: First argument should be a valid curve name
    at TypeError (native)
    at Object.createSecureContext (_tls_common.js:95:15)
    at Object.exports.connect (_tls_wrap.js:1032:48)
    at Agent.createConnection (https.js:84:22)
    at Agent.createSocket (_http_agent.js:185:26)
    at Agent.addRequest (_http_agent.js:152:10)
    at new ClientRequest (_http_client.js:174:16)
    at Object.exports.request (http.js:33:10)
    at Object.exports.request (https.js:208:15)
    at Request.start (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:751:32)
    at Request.end (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:1511:10)
    at end (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:564:14)
    at Immediate.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/request/request.js:578:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
I checked the certificates on ssl shopper an it seems to be fine, as I included the whole chain of certtificates in the .pem file.

Any suggestions ?

**Comment by ShockwaveNN** [comment]
Seems there is two errors, and I'm not sure that they related

1. We got report about `sqlQuery error sqlCommand: INSERT INTO task_result` earlier, but user never answerd (https://github.com/ONLYOFFICE/DocumentServer/issues/687)
This is interesting error, did you install DocumentServer first time or upgraded it from earlier version?

2. `error downloadFile:url=https://SERVERNAME/index.php/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.a2kHYzhPEIU9P2gh3NHYLyfR5M42aUyjVW3Z6H_vIvE` - is this file accesable from url?

**Comment by Sagittarius-B** [comment]
Thanks four your answer

1.I installed it a couple days ago, so I got the latest version. 
2.The url does download a blank docx file

I tried with different versions of nodejs but it only rose a bunch of new issues

**Comment by ShockwaveNN** [comment]
Which database are you using and which instruction did you use to install DocumentServer?

**Comment by Sagittarius-B** [comment]
Nextcloud is installed with mariadb v5.5.64 and onlyoffice runs with postgresql v9.2.24

I followed the procedure on onlyoffice's website 

https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx then switched to 

https://helpcenter.onlyoffice.com/server/linux/document/switch-to-https.aspx
for the https part

**Comment by ShockwaveNN** [comment]
Could you check that `http://documentserver-url/healthcheck` return true?

Also please check that you can connect to database from terminal using credentials saved in 
`/etc/onlyoffice/documentserver/default.json` - `services:CoAuthoring:sql` and they are correct

**Comment by Sagittarius-B** [comment]
Before upgrading postgresql-server to v.12, the healtcheck returned true.
Currently, after postgresql upgrade, the nginx starts but I got a 502 bad gateway error.
When I run supervisorctl restart all :

ds:metrics: stopped
ds:spellchecker: ERROR (abnormal termination)
ds:gc: ERROR (abnormal termination)
ds:docservice: ERROR (abnormal termination)
ds:converter: ERROR (abnormal termination)
ds:metrics: started

In the err.log (spellchecker +gc +docservice + converter) : 

Error: Config file /etc/onlyoffice/documentserver/default.json cannot be read
    at Config.util.parseFile (/var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:752:11)
    at /var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:595:28
    at Array.forEach (native)
    at /var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:591:14
    at Array.forEach (native)
    at Config.util.loadFileConfigs (/var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:590:13)
    at new Config (/var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:136:27)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Common/node_modules/config/lib/config.js:1638:31)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)

I am able to connect to the database with the credentials set in default.json.

**Comment by ShockwaveNN** [comment]
So you got postgresql v12, not v9.2.4?
Is theere `/etc/onlyoffice/documentserver/default.json`? Why it cannot be read? This is not right

**Comment by Sagittarius-B** [comment]
Yes, server is v12
The file does exist, i have no clue why it can't be accessed.
It's owned by root while local.json is owned by ds.
Could that be it?

**Comment by ShockwaveNN** [comment]
Seems some permissions errors, I think it's better to use Docker version of Documentserver, or clean reinstall, since seems there is several unrelated error with your setup and I don't know how you got there if you just use our instruction

**Comment by Sagittarius-B** [comment]
solved! 
I added read permission to 'production-linux.json' and read+write to 'default.json'. then upgraded nodejs to v.12
Thanks for your help!
