### ISSUE TITLE
SpellChecker nodehun.node version error 

### ISSUE THREAD

**Issue by elkekou** [ONLYOFFICE/DocumentServer#754]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Spellchecker unable to start

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Fresh install on Centos 8 following tutorial on onlyoffice website + trick of this issue to bypass dep error https://github.com/ONLYOFFICE/DocumentServer/issues/670

**What is the expected behavior?**
Spellechecker running 

**DocumentServer version:**
onlyoffice-documentserver.x86_64            5.4.2-46                                        @onlyoffice

**Operating System:**
Centos 8 (selinux disable)
nodejs.x86_64                               1:10.16.3-2.module_el8.0.0+186+542b25fc         @AppStream

Log error : 
Error: The module '/var/www/onlyoffice/documentserver/server/SpellChecker/node_modules/nodehun/build/Release/nodehun.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/SpellChecker/sources/spellCheck.js:13:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));

Sorry i'm not familiar with nodejs/npm so don't know which info to give.

Thanks for help.

**Comment by ShockwaveNN** [comment]
Duplicate https://github.com/ONLYOFFICE/DocumentServer/issues/312
Possible solution at https://github.com/ONLYOFFICE/DocumentServer/issues/312#issuecomment-392479211

**Comment by elkekou** [comment]
Thanks for you help
