### ISSUE TITLE
Please update compilation instructions for Document Server 5.5

### ISSUE THREAD

**Issue by drebs** [ONLYOFFICE/DocumentServer#824]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

I'm hitting several different problems when trying to adapt [the outdated documentation](https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx) to compile Document Server `5.5`.

The documentation now explicitelly mentions that it doesn't work for Document Server `5.5`, so the main request in this issue is for you to please update the documentation accordingly.

I'm sorry for the mixed nature of this issue where I ask for doc and also report a compilation failure, but I thought that only doing one of them would lead to an incomplete report. From my side, you can safely ignore the compilation problem I'm reporting if you can/want to put energy in updating the compilation documentation. :-) Just so you know, if I circumvent this problem (as I documented further down), I still find other issues when installing the server where files are not found in the expected places.

**Note 1:** Ubuntu 14.04 [has reached end of standard support in 2019](https://help.ubuntu.com/community/EOL#Ubuntu_14.04_Trusty_Tahr), and I had success using Ubuntu 18.04 to build Document Server up to `5.4.1`. I had to stick to `gcc-4.8` because of #377, but it was working fine. I had issues and couldn't build `5.4.2`, but now with `5.5` it looks like there are several parts that break during the compilation process. Do you have plans for using a newer Ubuntu to compile Document Server?

**Note 2:** Node.js 8 [has reached end-of-life](https://nodejs.org/en/about/releases/), and it'd be great to be able to use a newer version. Do you have plans for using a newer Node.js to compile and run Document Server?

I will report here the first problem I hit just so you can have an idea what I'm talking about. Thanks a lot for your attention!

In my case, compilation of `core` fails with:

```
make[2]: Entering directory '/srv/onlyoffice/DocumentServer/core/X2tConverter/Common/DocxFormat/DocxFormatLib'
g++ -c -pipe -Wall -Wno-ignored-qualifiers -O2 -fPIC -std=gnu++11 -Wall -W -D_REENTRANT -DINTVER=5.5.0.1 -DLINUX -D_LINUX -DCRYPTOPP_DISABLE_ASM -DUNICODE -D_UNICODE -DDONT_WRITE_EMBEDDED_FONTS -DQT_NO_DEBUG -I../../../../Common/DocxFormat/DocxFormatLib -I. -I/srv/onlyoffice/DocumentServer/core/Common/3dParty/boost/build/linux_64/include -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o ../../../../Common/DocxFormat/DocxFormatLib/core_build/linux_64/release/obj/docxformatlib_logic.o ../../../../Common/DocxFormat/DocxFormatLib/docxformatlib_logic.cpp
In file included from ../../../../Common/DocxFormat/DocxFormatLib/../Source/Common/SimpleTypes_Base.h:38:0,
                 from ../../../../Common/DocxFormat/DocxFormatLib/../Source/Common/SimpleTypes_Word.h:34,
                 from ../../../../Common/DocxFormat/DocxFormatLib/../Source/Common/SimpleTypes_Word.cpp:32,
                 from ../../../../Common/DocxFormat/DocxFormatLib/common_formatlib.cpp:40,
                 from ../../../../Common/DocxFormat/DocxFormatLib/docxformatlib_logic.cpp:32:
../../../../Common/DocxFormat/DocxFormatLib/../Source/Common/../XML/Utils.h:46:34: fatal error: boost/lexical_cast.hpp: No such file or directory
 #include <boost/lexical_cast.hpp>
                                  ^
compilation terminated.
Makefile:974: recipe for target '../../../../Common/DocxFormat/DocxFormatLib/core_build/linux_64/release/obj/docxformatlib_logic.o' failed
make[2]: Leaving directory '/srv/onlyoffice/DocumentServer/core/X2tConverter/Common/DocxFormat/DocxFormatLib'
make[2]: *** [../../../../Common/DocxFormat/DocxFormatLib/core_build/linux_64/release/obj/docxformatlib_logic.o] Error 1
Makefile:54: recipe for target 'sub----------Common-DocxFormat-DocxFormatLib-DocxFormatLib-pro-make_first-ordered' failed
make[1]: *** [sub----------Common-DocxFormat-DocxFormatLib-DocxFormatLib-pro-make_first-ordered] Error 2
make[1]: Leaving directory '/srv/onlyoffice/DocumentServer/core/X2tConverter/build/Qt/X2tSLN.build'
Makefile:288: recipe for target 'build/bin/linux_64/x2t' failed
make: *** [build/bin/linux_64/x2t] Error 2
The command '/bin/sh -c cd /srv/onlyoffice/DocumentServer/core && make' returned a non-zero code: 2
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

It can be reproduced using the following `Dockerfile`:

```
# instructions from:
# https://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx

FROM ubuntu:18.04

ENV PRODUCT_VERSION 5.5.0

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get -y dist-upgrade
RUN apt-get install -yq \
  curl \
  apt-transport-https \
  ca-certificates \
  gnupg
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g npm grunt-cli json
RUN apt-get install -yq \
    wget \
    build-essential \
    libcurl4-gnutls-dev \
    libglib2.0-dev \
    libgdk-pixbuf2.0-dev \
    libgtkglext1-dev \
    libatk1.0-dev \
    libcairo2-dev \
    libxml2-dev \
    libxss-dev \
    libgconf2-dev \
    default-jre \
    qt5-qmake \
    qt5-default  \
    p7zip-full \
    git \
    subversion \
    autoconf \
    libtool

# use gcc 4.8 to build
RUN apt-get -y purge gcc-7 g++-7 debhelper && apt-get install -y gcc-4.8 g++-4.8
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8

# get the code
RUN mkdir -p /srv/onlyoffice
RUN git clone \
    --recursive \
    --branch ONLYOFFICE-DocumentServer-${PRODUCT_VERSION} \
    https://github.com/ONLYOFFICE/DocumentServer.git \
    /srv/onlyoffice/DocumentServer

RUN apt install -y libtool
RUN cd /srv/onlyoffice/DocumentServer/core/Common/3dParty && ./make.sh
RUN cd /srv/onlyoffice/DocumentServer/core && make
RUN cd /srv/onlyoffice/DocumentServer/sdkjs && make
RUN cd /srv/onlyoffice/DocumentServer/server && make
```
The failure happens in the `core` compilation step.

**What is the expected behavior?**

The compiler should find `boost/lexical_cast.hpp` and compilation should continue.

If I add the following before the `core` compilation step, compilation works:

```
RUN mkdir -p /srv/onlyoffice/DocumentServer/core/Common/3dParty/boost/build/linux_64 \
    && ln -sf /srv/onlyoffice/DocumentServer/core/Common/3dParty/boost/boost_1_58_0/boost /srv/onlyoffice/DocumentServer/core/Common/3dParty/boost/build/linux_64/include \
    && ln -sf /srv/onlyoffice/DocumentServer/core/Common/3dParty/boost/boost_1_58_0/build/linux_64/shared /srv/onlyoffice/DocumentServer/core/Common/3dParty/boost/build/linux_64/lib
```

(Even though compilation then finishes, I then find other problems when installing where files are not found in the expected places. This seems to indicate that there's something wrong with the process as a whole, maybe.)

**Did this work in previous versions of DocumentServer?**

Yes, I had `5.4.1` working fine with the same commands.

**DocumentServer version:**

`5.5.0`.

**Operating System:**

I'm using Docker CE version `18.06.1~ce~3-0~debian` running in a Debian Stretch `9.12` system to compile using Ubuntu 18.04, as per the Dockerfile above.

**Browser version:**

Does not apply.

**Comment by ShockwaveNN** [comment]
@drebs Hi. Yes we understand that this is a huge problem and working on it right now.
From v5.5.0 we will use our custom written [build_tools](https://github.com/ONLYOFFICE/build_tools) to compile all our product 
And now we working on that in v5.5.1 we release with completly working instruction how to build (you can see progress at [hotfix/v5.5.1 branch](https://github.com/ONLYOFFICE/build_tools/tree/hotfix/v5.5.1)

But also please note that currently this solution only work on Ubuntu 14.04 and we hope we'll add new version to support in future, but main problem is changes in comilation of our 3dparty dependencies, such `v8` and `cef`

**Comment by Genesis0x1b** [comment]
I also faced issues described above. After that I started using instructions https://helpcenter.onlyoffice.com/server/linux/document/docker-compile.aspx 

However, build fails with "closure-compiler" task. After spending about one hour investigating this issue, I revealed java jre version incompatibility (java 8 is necessary). I overcame it with extending Dockerfile image:

```
FROM onlyoffice/documentserver-builder

RUN apt-get -y update && \
    apt-get install --force-yes -yq software-properties-common && \
        add-apt-repository -y ppa:openjdk-r/ppa && \
    apt-get -y update && \
    apt-get install -yq openjdk-8-jdk && \
		update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java && \
        update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
```

And "closure-compiler" task passed.

Unfortunately, right now I am stuck with the following error:

```
cd ../web-apps/build  && \                                                                                                                             
                PRODUCT_VERSION=0.0.0 BUILD_NUMBER=0 APP_COPYRIGHT="Copyri                                                                             ght (C) Ascensio System SIA 2012-2020. All rights reserved" PUBLISHER_URL=                                                                             "https://www.onlyoffice.com/" grunt deploy-documents-component --no-color                                                                              -v                                                                                      
/var/lib/onlyoffice/web-apps/build/node_modules/mkdirp/lib/opts-arg.js:7                                                                               
    opts = { mode: 0o777 & (~process.umask()), fs, ...opts }                                                                                           
                                                   ^^^                                                                                                 
SyntaxError: Unexpected token ...                                                                                                                      
  at Object.exports.runInThisContext (vm.js:76:16)                                                                                                     
  at Module._compile (module.js:542:28)                                                                                                                
  at Object.Module._extensions..js (module.js:579:10)                                                                                                  
  at Module.load (/var/lib/onlyoffice/web-apps/build/node_modules/coffeesc                                                                             ript/lib/coffee-script/register.js:45:36)                                                                                                              
  at tryModuleLoad (module.js:446:12)                                                                                                                  
  at Function.Module._load (module.js:438:3)                                                                                                           
  at Module.require (module.js:497:17)                                                                                                                 
  at require (internal/module.js:20:19)                                                                                                                
  at Object.<anonymous> (/var/lib/onlyoffice/web-apps/build/node_modules/m                                                                             kdirp/index.js:1:79)                                                                                                                                   
  at Module._compile (module.js:570:32)                                                                                                                
  at Object.Module._extensions..js (module.js:579:10)                          
  at Module.load (/var/lib/onlyoffice/web-apps/build/node_modules/coffeesc                                                                             ript/lib/coffee-script/register.js:45:36)                                                                                                              
  at tryModuleLoad (module.js:446:12)                                                                                                                  
  at Function.Module._load (module.js:438:3)                                                                                                           
  at Module.require (module.js:497:17)                                                                                                                 
  at require (internal/module.js:20:19)                                                                                                                
  at Object.<anonymous> (/var/lib/onlyoffice/web-apps/build/node_modules/g                                                                             runt/lib/grunt/file.js:20:31)                                                                                                                          
  at Module._compile (module.js:570:32)                                                                                                                
  at Object.Module._extensions..js (module.js:579:10)                                                                                                  
  at Module.load (/var/lib/onlyoffice/web-apps/build/node_modules/coffeesc                                                                             ript/lib/coffee-script/register.js:45:36)                                                                                                              
  at tryModuleLoad (module.js:446:12)                                                                                                                  
  at Function.Module._load (module.js:438:3)                                                                                                           
  at Module.require (module.js:497:17)                                                                                                                 
  at require (internal/module.js:20:19)                                                                                                                
  at gRequire (/var/lib/onlyoffice/web-apps/build/node_modules/grunt/lib/grunt.js:14:24)
  at Object.<anonymous> (/var/lib/onlyoffice/web-apps/build/node_modules/grunt/lib/grunt.js:28:1)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:44:1)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

make: *** [../web-apps/deploy/web-apps/apps/api/documents/api.js] Error 1
mkdir -p ../build_tools/out/linux_64/onlyoffice/documentserver/server/SpellChecker/dictionaries && \
                cp -r -t ../build_tools/out/linux_64/onlyoffice/documentserver/server/SpellChecker/dictionaries ../dictionaries/*_*
mkdir -p ../build_tools/out/linux_64/onlyoffice/documentserver/server && \
                cp -r -t ../build_tools/out/linux_64/onlyoffice/documentserver/server LICENSE.txt 3rd-Party.txt license/
sed "s|\(const buildVersion = \).*|\1'0.0.0';|" -i ../build_tools/out/linux_64/onlyoffice/documentserver/server/Common/sources/commondefines.js
sed "s|\(const buildNumber = \).*|\10;|" -i ../build_tools/out/linux_64/onlyoffice/documentserver/server/Common/sources/commondefines.js
sed "s|\(const buildDate = \).*|\1'$(date +%F)';|" -i ../build_tools/out/linux_64/onlyoffice/documentserver/server/Common/sources/license.js
test -e ./branding/licenseKey.pem && \
        cp ./branding/licenseKey.pem ../build_tools/out/linux_64/onlyoffice/documentserver/server/Common/sources || true
```

Could you please help me?

**Comment by ShockwaveNN** [comment]
@Genesis0x1b Seems that your problem is different from topic started, so please create new issue

**Comment by ShockwaveNN** [comment]
DocumentServer can be compiled since v5.5.1 using `onlyoffice/build_tools` repo, closing this issue
