### ISSUE TITLE
Docker builder for Document Server 5.5 fails

### ISSUE THREAD

**Issue by Genesis0x1b** [ONLYOFFICE/DocumentServer#825]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Docker build fails using instructions https://helpcenter.onlyoffice.com/server/linux/document/docker-compile.aspx

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Build fails with "closure-compiler" task. After spending about one hour investigating this issue, I revealed java jre version incompatibility (java 8 is necessary). I overcame it with extending Dockerfile image:

```
FROM onlyoffice/documentserver-builder

RUN apt-get -y update && \
    apt-get install --force-yes -yq software-properties-common && \
        add-apt-repository -y ppa:openjdk-r/ppa && \
    apt-get -y update && \
    apt-get install -yq openjdk-8-jdk && \
		update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java && \
        update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
```

And "closure-compiler" task passed.

Unfortunately, right now I am stuck with the following error:

```
cd ../web-apps/build  && \                                                                                                                             
                PRODUCT_VERSION=0.0.0 BUILD_NUMBER=0 APP_COPYRIGHT="Copyri                                                                             ght (C) Ascensio System SIA 2012-2020. All rights reserved" PUBLISHER_URL=                                                                             "https://www.onlyoffice.com/" grunt deploy-documents-component --no-color                                                                              -v                                                                                      
/var/lib/onlyoffice/web-apps/build/node_modules/mkdirp/lib/opts-arg.js:7                                                                               
    opts = { mode: 0o777 & (~process.umask()), fs, ...opts }                                                                                           
                                                   ^^^                                                                                                 
SyntaxError: Unexpected token ...                                                                                                                      
  at Object.exports.runInThisContext (vm.js:76:16)                                                                                                     
  at Module._compile (module.js:542:28)                                                                                                                
  at Object.Module._extensions..js (module.js:579:10)                                                                                                  
  at Module.load (/var/lib/onlyoffice/web-apps/build/node_modules/coffeesc                                                                             ript/lib/coffee-script/register.js:45:36)                                                                                                              
  at tryModuleLoad (module.js:446:12)                                                                                                                  
  at Function.Module._load (module.js:438:3)                                                                                                           
  at Module.require (module.js:497:17)                                                                                                                 
  at require (internal/module.js:20:19)                                                                                                                
  at Object.<anonymous> (/var/lib/onlyoffice/web-apps/build/node_modules/m                                                                             kdirp/index.js:1:79)                                                                                                                                   
  at Module._compile (module.js:570:32)                                                                                                                
  at Object.Module._extensions..js (module.js:579:10)                          
  at Module.load (/var/lib/onlyoffice/web-apps/build/node_modules/coffeesc                                                                             ript/lib/coffee-script/register.js:45:36)                                                                                                              
  at tryModuleLoad (module.js:446:12)                                                                                                                  
  at Function.Module._load (module.js:438:3)                                                                                                           
  at Module.require (module.js:497:17)                                                                                                                 
  at require (internal/module.js:20:19)                                                                                                                
  at Object.<anonymous> (/var/lib/onlyoffice/web-apps/build/node_modules/g                                                                             runt/lib/grunt/file.js:20:31)                                                                                                                          
  at Module._compile (module.js:570:32)                                                                                                                
  at Object.Module._extensions..js (module.js:579:10)                                                                                                  
  at Module.load (/var/lib/onlyoffice/web-apps/build/node_modules/coffeesc                                                                             ript/lib/coffee-script/register.js:45:36)                                                                                                              
  at tryModuleLoad (module.js:446:12)                                                                                                                  
  at Function.Module._load (module.js:438:3)                                                                                                           
  at Module.require (module.js:497:17)                                                                                                                 
  at require (internal/module.js:20:19)                                                                                                                
  at gRequire (/var/lib/onlyoffice/web-apps/build/node_modules/grunt/lib/grunt.js:14:24)
  at Object.<anonymous> (/var/lib/onlyoffice/web-apps/build/node_modules/grunt/lib/grunt.js:28:1)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:44:1)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:394:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:509:3

make: *** [../web-apps/deploy/web-apps/apps/api/documents/api.js] Error 1
mkdir -p ../build_tools/out/linux_64/onlyoffice/documentserver/server/SpellChecker/dictionaries && \
                cp -r -t ../build_tools/out/linux_64/onlyoffice/documentserver/server/SpellChecker/dictionaries ../dictionaries/*_*
mkdir -p ../build_tools/out/linux_64/onlyoffice/documentserver/server && \
                cp -r -t ../build_tools/out/linux_64/onlyoffice/documentserver/server LICENSE.txt 3rd-Party.txt license/
sed "s|\(const buildVersion = \).*|\1'0.0.0';|" -i ../build_tools/out/linux_64/onlyoffice/documentserver/server/Common/sources/commondefines.js
sed "s|\(const buildNumber = \).*|\10;|" -i ../build_tools/out/linux_64/onlyoffice/documentserver/server/Common/sources/commondefines.js
sed "s|\(const buildDate = \).*|\1'$(date +%F)';|" -i ../build_tools/out/linux_64/onlyoffice/documentserver/server/Common/sources/license.js
test -e ./branding/licenseKey.pem && \
        cp ./branding/licenseKey.pem ../build_tools/out/linux_64/onlyoffice/documentserver/server/Common/sources || true
```

Could you please help me?

**What is the expected behavior?**

Successful build.

**Did this work in previous versions of DocumentServer?**

don't know

**DocumentServer version:**

5.5

**Operating System:**

Ubuntu 14.04

**Browser version:**

**Comment by ShockwaveNN** [comment]
@Genesis0x1b Hi, please look for logs above this error. I just tried to compile it and got error on x2t compilation:
```
g++ -c -m64 -pipe -Wall -Wno-ignored-qualifiers -O2 -fPIC -std=c++0x -Wall -W -D_REENTRANT -DINTVER=2.5.565.0 -DLINUX -D_LINUX -DCRYPTOPP_DISABLE_ASM -DUNICODE -D_UNICODE -DDONT_WRITE_EMBEDDED_FONTS -DQT_NO_DEBUG -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../../../../Common/DocxFormat/DocxFormatLib -I/var/lib/onlyoffice/core/Common/3dParty/boost/build/linux_64/include -I. -o ../../../../Common/DocxFormat/DocxFormatLib/core_build/linux_64/release/obj/docxformatlib_logic.o ../../../../Common/DocxFormat/DocxFormatLib/docxformatlib_logic.cpp
In file included from ../../../../Common/DocxFormat/DocxFormatLib/../Source/Common/SimpleTypes_Base.h:38:0,
                 from ../../../../Common/DocxFormat/DocxFormatLib/../Source/Common/SimpleTypes_Word.h:34,
                 from ../../../../Common/DocxFormat/DocxFormatLib/../Source/Common/SimpleTypes_Word.cpp:32,
                 from ../../../../Common/DocxFormat/DocxFormatLib/common_formatlib.cpp:40,
                 from ../../../../Common/DocxFormat/DocxFormatLib/docxformatlib_logic.cpp:32:
../../../../Common/DocxFormat/DocxFormatLib/../Source/Common/../XML/Utils.h:46:34: fatal error: boost/lexical_cast.hpp: No such file or directory
 #include <boost/lexical_cast.hpp>
                                  ^
compilation terminated.
make[2]: *** [../../../../Common/DocxFormat/DocxFormatLib/core_build/linux_64/release/obj/docxformatlib_logic.o] Error 1
make[2]: Leaving directory `/var/lib/onlyoffice/core/X2tConverter/Common/DocxFormat/DocxFormatLib'
make[1]: *** [sub----------Common-DocxFormat-DocxFormatLib-DocxFormatLib-pro-make_first-ordered] Error 2
make[1]: Leaving directory `/var/lib/onlyoffice/core/X2tConverter/build/Qt/X2tSLN.build'
make: *** [build/bin/linux_64/x2t] Error 2
```

Seems I was wrong and you have same issue as #824, sorry.
We are working now on new instruction, how to build documentserver-related products and hope it will be ready with 5.5.1 release

**Comment by Genesis0x1b** [comment]
Yes, I I've also come across this mistake before. But somehow I was able to solve this problem. However, thank you for your help. I will wait for up-to-date instructions with 5.5.1 release.

**Comment by ShockwaveNN** [comment]
@Genesis0x1b You can try it here:
https://github.com/ONLYOFFICE/build_tools/tree/hotfix/v5.5.1
