### ISSUE TITLE
Cannot link document Server for Linux on CentOS7.5

### ISSUE THREAD

**Issue by zjs-apple** [ONLYOFFICE/DocumentServer#863]
When i Installing Document Server for Linux on CentOS7.5.
Reference:https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx
In the end,the document server is ok，
but When I test editing files，
ws://XXXX/5.5.1-76/doc/b81fdff747a247929253f4701a92bc521588227954180/c/208/zp1umjpc/websocket
This link has been pending.
Centos7.5：port all open，firewall is closed.
What do I need to do

**Comment by ShockwaveNN** [comment]
> firewall is closed.

Is that mean that firewall is running? Try to stop it and retry

**Comment by zjs-apple** [comment]
firewall is stop

**Comment by ShockwaveNN** [comment]
Which browser are you using?

If there any messages in `/var/log/onlyoffice`?

**Comment by zjs-apple** [comment]
> Which browser are you using?
> Chrome
> If there any messages in `/var/log/onlyoffice`?
in /var/log/onlyoffice/documentserver/docservice/out.log
[2020-04-30T14:42:23.182] [ERROR] nodeJS - Error conn close: docId = b81fdff747a247929253f4701a92bc521588227954180
TypeError: undefined is not a function
    at Object.exports.getIndexFromUserId (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at closeDocument (/snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0)
    at closeDocument.next (<anonymous>)
    at /snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/DocService/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-04-30T14:42:26.829] [ERROR] nodeJS - error receiving response: docId = undefined type = auth
TypeError: undefined is not a function
    at Object.exports.getIndexFromUserId (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at endAuth (/snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0)
    at endAuth.next (<anonymous>)
    at auth (/snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0)
    at auth.next (<anonymous>)
    at /snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0
    at Generator.next (<anonymous>)
    at onFulfilled (/snapshot/server/build/server/DocService/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ShockwaveNN** [comment]
Seems at least something wrong with your integration with Document Management System

Which integration are you using? nextcloud or some other?

**Comment by zjs-apple** [comment]
My own file server:fastdfs
When I copy the file path to be edited, this file can be downloaded.
so i think the fastdfs server is ok

**Comment by ShockwaveNN** [comment]
Seems you send incorrect `docId`
Did you implement all things described in https://api.onlyoffice.com/editors/basic

**Comment by zjs-apple** [comment]
> Seems you send incorrect `docId`
> Did you implement all things described in https://api.onlyoffice.com/editors/basic

I set up a document service running on docker on my computer. I can edit files

**Comment by ShockwaveNN** [comment]
Errors is log files is not normal, so you should figure out thy they happend. You can create some Dockerfile with your system and I have take a look.
Or some other way to give me access to your file system

But I don't think I'll be able to help you with current information

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
