### ISSUE TITLE
User can't edit document through the API

### ISSUE THREAD

**Issue by yonc** [ONLYOFFICE/DocumentServer#867]
I don't know why the below error occurred when I used the `onlyoffice/documentserver:latest` image.
```
[2020-05-05T03:23:34.652] [ERROR] nodeJS - error receiving response: docId = undefined type = auth
onlyoffice-document-server     | TypeError: undefined is not a function
onlyoffice-document-server     |     at Object.exports.getIndexFromUserId (/snapshot/server/build/server/Common/sources/utils.js:0:0)
onlyoffice-document-server     |     at endAuth (/snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0)
onlyoffice-document-server     |     at endAuth.next (<anonymous>)
onlyoffice-document-server     |     at auth (/snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0)
onlyoffice-document-server     |     at auth.next (<anonymous>)
onlyoffice-document-server     |     at /snapshot/server/build/server/DocService/sources/DocsCoServer.js:0:0
onlyoffice-document-server     |     at Generator.next (<anonymous>)
onlyoffice-document-server     |     at onFulfilled (/snapshot/server/build/server/DocService/node_modules/co/index.js:65:19)
onlyoffice-document-server     |     at process._tickCallback (internal/process/next_tick.js:68:7)
```
And when I use this instead `onlyoffice/documentserver:5.4.2.46` the error won't happen.

Please help me. I don't know what I missed on configuration.

**Environment**
- Ubuntu 18.04.4 LTS
- Docker Info  
```Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
- Data:
```
{
  "editorConfig": {
    "mode": "edit",
    "callbackUrl": "http://document-callback-url",
    "user": {
      "name": "a",
      "id": 14213433
    }
  },
  "documentType": "presentation",
  "document": {
    "permissions": {
      "edit": true
    },
    "title": "1431 (1).ppt",
    "fileType": "ppt",
    "key": "14231327",
    "url": "http://document-url"
  }
}
```

**Comment by ShockwaveNN** [comment]
Try to set user:id to string, not integer
According to docs:
https://api.onlyoffice.com/editors/config/editor#user

**Comment by abrantes01** [comment]
Had the same error. Convert user:id to string fixed it. Thanks @ShockwaveNN !

**Comment by daliandazi** [comment]
> Try to set `user:id` to string, not integer
> According to docs:
> https://api.onlyoffice.com/editors/config/editor#user

**GOOD!!!**

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by muzhix** [comment]
> Try to set `user:id` to string, not integer
> According to docs:
> https://api.onlyoffice.com/editors/config/editor#user

very helpful
