### ISSUE TITLE
connect from nextcloud to onlyoffice failed.

### ISSUE THREAD

**Issue by frocelu** [ONLYOFFICE/DocumentServer#895]
I try to connect to my onlyoffice server, but I got this problem.
`Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)✖`

in nextcloud log:
`{"reqId":"u2BDrNM4XHrayfG1kkZp","level":3,"time":"2020-05-29T15:35:51+08:00","remoteAddr":"10.172.21.31","user":"cpco","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"GetConvertedUri on check error: Error occurred in the document service: Error while downloading the document file to be converted.","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0","version":"17.0.0.9","id":"5ed0bc1e8416a"}`

onlyoffice log(converter/output.log):
`[2020-05-29 15:05:57.422] [WARN] nodeJS - update cluster with 1 workers
[2020-05-29 15:05:57.438] [WARN] nodeJS - worker 3672 started.
[2020-05-29 15:05:57.438] [WARN] nodeJS - update cluster with 1 workers
[2020-05-29 15:09:39.475] [ERROR] nodeJS - error downloadFile:url=http://10.172.20.6/apps/onlyoffice/empty?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY3Rpb24iOiJlbXB0eSJ9.PXoHkTDqxaMXT3b4oFHZrUhPFpYwW_uQkssd-kebm8U;attempt=1;code:undefined;connect:undefined;(id=conv_check_293413191_docx)
Error: Error response: statusCode:404 ;body:
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /apps/onlyoffice/empty</pre>
</body>
</html>

    at Request._callback (C:\Program Files\ONLYOFFICE\DocumentServer\server\Common\sources\utils.js:250:18)
    at Request.self.callback (C:\Program Files\ONLYOFFICE\DocumentServer\server\Common\node_modules\request\request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Program Files\ONLYOFFICE\DocumentServer\server\Common\node_modules\request\request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Program Files\ONLYOFFICE\DocumentServer\server\Common\node_modules\request\request.js:1079:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
`

nextcloud version: 17.0.0
app version: tested on 3.0.2 and 4.1.4
onlyoffice version: tested on 5.5.3, 5.4.2, 5.1.5

**Comment by ShockwaveNN** [comment]
Since convert service cannot download file seems this is not problem of DocumentServer, but problem of Integration with nextcloud, moving to another repo
