### ISSUE TITLE
Lost data after safe shutdown

### ISSUE THREAD

**Issue by ETararenko** [ONLYOFFICE/DocumentServer#924]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Some data are missing

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Faced endless loading in one xlsx file. We are restarted onlyoffice using the following procedure:

/usr/bin/documentserver-prepare4shutdown.sh
sudo supervisorctl restart onlyoffice-documentserver:docservice
sudo supervisorctl restart onlyoffice-documentserver:converter
sudo service nginx reload

After this file successfully opened, but data for 1 week has been lost.

**What is the expected behavior?**

**Did this work in previous versions of DocumentServer?**

**DocumentServer version:**
5.2.8

**Operating System:**
Ubuntu 16.04.5

**Browser version:**
Google Chrome 83.0.4103.116

**Comment by ShockwaveNN** [comment]
Sorry to hear, but 

> DocumentServer version:
5.2.8

You DocumentServer version majorly outdated (released more than year and half ago), current stable is 5.5.3
We fixed a lot of bugs during this timeline, so I hope your bug never repeat itself again after update

But maybe @DenisDeeSign know a way to recover broken file?

**Comment by ETararenko** [comment]
How can I be sure that the next time I stop, data will not be lost?

**Comment by DenisDeeSign** [comment]
Hi, @ETararenko. 
1. What Document Management System do you use for document storage?
2. Do you see any errors in docservice and converter logs within time interval when the changes were adding in xlsx file?

**Comment by ETararenko** [comment]
Hello,
1. We are using nextcloud 18.0.6.
2. It’s difficult for me to determine the exact time of the changes. But we have the following errors in logs:

docservice log:
[2020-07-08T09:45:32.734] [ERROR] nodeJS - changesError: docId = 1806743031 Error: Uncaught TypeError: Cannot read property 'Aa' of undefined Script: https://office.st.by/v5.2.8-24//sdkjs/word/sdk-all.js Line: 7793:249 userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 platform: Win32 isLoadFullApi: true isDocumentLoadComplete: true StackTrace: TypeError: Cannot read property 'Aa' of undefined
    at we.Aa (https://office.st.by/v5.2.8-24//sdkjs/word/sdk-all.js:7793:249)
    at Oa.cTd (https://office.st.by/v5.2.8-24//sdkjs/word/sdk-all.js:8154:6)
    at x.yfe (https://office.st.by/v5.2.8-24//sdkjs/word/sdk-all-min.js:775:232)
    at V.i.onStartNumbering (https://office.st.by/v5.2.8-24//web-apps/apps/documenteditor/main/app.js:30:7178)
    at M (https://office.st.by/v5.2.8-24//web-apps/apps/documenteditor/main/app.js:8:11039)
    at V.i.<anonymous> (https://office.st.by/v5.2.8-24//web-apps/apps/documenteditor/main/app.js:8:11241)
    at V.i.<anonymous> (https://office.st.by/v5.2.8-24//web-apps/apps/documenteditor/main/app.js:8:4442)
    at c (https://office.st.by/v5.2.8-24//web-apps/apps/documenteditor/main/app.js:11:13968)
    at V.i.trigger (https://office.st.by/v5.2.8-24//web-apps/apps/documenteditor/main/app.js:11:13228)
    at V.i.onItemClick (https://office.st.by/v5.2.8-24//web-apps/apps/documenteditor/main/app.js:19:25256)

[2020-07-09T04:37:13.436] [ERROR] nodeJS - changesError: docId = 27429114 Error: Uncaught TypeError: Cannot read property 'top' of undefined Script: https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all.js Line: 8071:383 userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 platform: Win32 isLoadFullApi: true isDocumentLoadComplete: false StackTrace: TypeError: Cannot read property 'top' of undefined
    at Fa.Le (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all.js:8071:383)
    at h.kPc (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all.js:7128:372)
    at h.lPc (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all.js:7127:496)
    at Ja (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all.js:8264:163)
    at Fa.d_ (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all.js:8273:449)
    at h.<anonymous> (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all.js:8007:30)
    at h.trigger (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all-min.js:647:271)
    at f.EIb (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all.js:1939:123)
    at Da.i8a (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all.js:7408:184)
    at Da.KQe (https://office.st.by/v5.2.8-24//sdkjs/cell/sdk-all-min.js:795:28)

converter logs:
[2020-07-09T05:52:54.232] [ERROR] nodeJS - stderr (id=27429114_8774):change_code: this.cols.length;return this.fk+(a<d?this.cols[a].left:(0===d?0:this.cols[d-1].left+this.cols[d-1].width)+!this.Va.ncb()*Asc.round(this.zha*this.Cu())*(a-d))};Fa.prototype.wAa=function(a){return this.Ee(a)*gb(0,3,this.Gla())};Fa.prototype.kKb=function(a){return a<this.rows.length?this.rows[a].Jr:this.orb};Fa.prototype.Le=function(a){var d=this.rows.length;return a<d?this.rows[a].top:(0===d?this.Ek:this.rows[d-1].top+this.rows[d-1].height)+!this.Va.mcb()*Asc.round(this.G9a*this.Cu())*(a-d)};Fa.prototype.xAa=
change: Uncaught TypeError: Cannot read property 'top' of undefined
DoctRenderer:<result><error index="15849" /></result>
change_code: this.cols.length;return this.fk+(a<d?this.cols[a].left:(0===d?0:this.cols[d-1].left+this.cols[d-1].width)+!this.Va.ncb()*Asc.round(this.zha*this.Cu())*(a-d))};Fa.prototype.wAa=function(a){return this.Ee(a)*gb(0,3,this.Gla())};Fa.prototype.kKb=function(a){return a<this.rows.length?this.rows[a].Jr:this.orb};Fa.prototype.Le=function(a){var d=this.rows.length;return a<d?this.rows[a].top:(0===d?this.Ek:this.rows[d-1].top+this.rows[d-1].height)+!this.Va.mcb()*Asc.round(this.G9a*this.Cu())*(a-d)};Fa.prototype.xAa=
change: Uncaught TypeError: Cannot read property 'top' of undefined
DoctRenderer:<result><error index="15848" /></result>
change_code: this.cols.length;return this.fk+(a<d?this.cols[a].left:(0===d?0:this.cols[d-1].left+this.cols[d-1].width)+!this.Va.ncb()*Asc.round(this.zha*this.Cu())*(a-d))};Fa.prototype.wAa=function(a){return this.Ee(a)*gb(0,3,this.Gla())};Fa.prototype.kKb=function(a){return a<this.rows.length?this.rows[a].Jr:this.orb};Fa.prototype.Le=function(a){var d=this.rows.length;return a<d?this.rows[a].top:(0===d?this.Ek:this.rows[d-1].top+this.rows[d-1].height)+!this.Va.mcb()*Asc.round(this.G9a*this.Cu())*(a-d)};Fa.prototype.xAa=
change: Uncaught TypeError: Cannot read property 'top' of undefined
DoctRenderer:<result><error index="15847" /></result>
change_code: this.cols.length;return this.fk+(a<d?this.cols[a].left:(0===d?0:this.cols[d-1].left+this.cols[d-1].width)+!this.Va.ncb()*Asc.round(this.zha*this.Cu())*(a-d))};Fa.prototype.wAa=function(a){return this.Ee(a)*gb(0,3,this.Gla())};Fa.prototype.kKb=function(a){return a<this.rows.length?this.rows[a].Jr:this.orb};Fa.prototype.Le=function(a){var d=this.rows.length;return a<d?this.rows[a].top:(0===d?this.Ek:this.rows[d-1].top+this.rows[d-1].height)+!this.Va.mcb()*Asc.round(this.G9a*this.Cu())*(a-d)};Fa.prototype.xAa=
...

**Comment by DenisDeeSign** [comment]
Seems you got some javascript error during work with the spreadsheet. In DocumentServer version before 5.3.0 there was no notifications about this type error, so you continued working with the document and all the changes related to this breaking change had been lost. 
We strongly recomend to update your server to latest version 5.5.3. The errors more likely had been fixed in one of next versions of the DocumentServer you have now.

**Comment by ETararenko** [comment]
Hello, once again.
I'm trying to update DocumentServer to latest version (on test server). And after update i'm found that nginx config files have been lost. There are only default files.
I'm using the following doc: https://helpcenter.onlyoffice.com/de/server/linux/document/upgrade-document.aspx

Can you please advice, what files should we back up before updating?

**Comment by ShockwaveNN** [comment]
This may related to this issue
https://github.com/ONLYOFFICE/DocumentServer/issues/892

You should backup all files to which you made changes

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
