### ISSUE TITLE
postData error after upgrade 5.5 > 5.6 (with 302 status code)

### ISSUE THREAD

**Issue by paulooliveira** [ONLYOFFICE/DocumentServer#940]
Hello, all, I'm submitting my bug report because I cannot fix my server after an upgrade

> [UPGRADE] nodejs:amd64 10.21.0-1nodesource1 -> 10.22.0-1nodesource1
> [UPGRADE] onlyoffice-documentserver:amd64 5.5.3-39 -> 5.6.0-17

Tnx in advance for any help

Bug report:

**What is the current behavior?**

302 error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Error while opening a document

**Did this work in previous versions of DocumentServer?**

Yes, 5.5 was ok

**DocumentServer version:**

5.6.0.17

**Operating System:**

Debian 10

**Browser version:**

Chrome

Error on out.log:

> [2020-08-03T12:36:04.419] [ERROR] nodeJS - postData error: docId = 58c6c1bd54f15c997ea0;url = https://pontolivre.partidolivre.pt/onlyoffice/backend/track?key=58c6c1bd54f15c997ea0;data = {"key":"58c6c1bd54f15c997ea0","status":4,"actions":[{"type":0,"userid":"aff636c0-68a4-4f4e-9dc5-89f8ba799462"}]}

Error: Error response: statusCode:302 ;body:

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js:0:0)
    at Request.init.self.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ShockwaveNN** [comment]
Could you log on your integration side why 302 redirect is returned?

We do not think we changed something in 5.5 -> 5.6 so 302 is error requrest for DocumentServer post request for quite some time

**Comment by paulooliveira** [comment]
Hi all,

Sorry for the miss reporting, I think it's not a bug on Onlyoffice side.
The integration I use just released a hotfix 3 hours ago: https://www.humhub.com/en/marketplace/onlyoffice/

> Change Log
2.1.2.2
Fixed
Hot fixed an authentication issue with HumHub 1.6+


I think you can close this issue or mark this as resolved to help other Humhub 1.6+ users with the same problem.


Thank you! 👍

**Comment by ShockwaveNN** [comment]
So if this is issue with humhum connector I moving this issue to according repo
