### ISSUE TITLE
Owncloud 10.5/php 7.4: can not create new files, exception in log

### ISSUE THREAD

**Issue by thommierother** [ONLYOFFICE/DocumentServer#945]
bug

can not create new files, exception in log

- docserver:
root@docs:~# apt-cache policy onlyoffice-documentserver
onlyoffice-documentserver:
  Installiert:           5.6.1-6
  Installationskandidat: 5.6.1-6
  Versionstabelle:
 *** 5.6.1-6 500
        500 https://download.onlyoffice.com/repo/debian squeeze/main amd64 Packages
        100 /var/lib/dpkg/status

This docserver runs fine against an owncloud instance with 10.4 on php 7.3. But against a current owncloud 10.5 with php 7.4 (same connector code) I see the following in the logs:

```
POST","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/new","message":"touch(): Unable to create file \/mnt\/data\/ocdata\/admin\/files\/test3.docx because No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#217"}
{"reqId":"GDbw6T8PxwOe9iZrgINc","level":3,"time":"2020-08-05T18:16:27+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"index","method":"POST","url":"\/owncloud\/index.php\/apps\/onlyoffice\/ajax\/new","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(66): OC\\\\Files\\\\Node\\\\Node->checkPermissions()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/onlyoffice\\\/controller\\\/editorcontroller.php(232): OC\\\\Files\\\\Node\\\\File->putContent()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Onlyoffice\\\\Controller\\\\EditorController->create()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(916): OC\\\\Route\\\\Router->match()\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}"}
{"reqId":"6bb5c85d-3a24-4ad9-8690-6a345496f4fd","level":0,"time":"2020-08-05T18:16:29+00:00","remoteAddr":"127.0.0.1","user":"test6","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/test6\/","message":"updating token 3321, last check is now 1596651180"}
```
new documents are not created from the oc 10.5 server but all works smooth from the 10.4.1 server

**Comment by ShockwaveNN** [comment]
If same DocumentServer works fine with owncloud 10.4 and have troubles with owncloud 10.5, this is problem with integration, moving to according repo
