### ISSUE TITLE
Compiling Document Server Error

### ISSUE THREAD

**Issue by pwxwabcd** [ONLYOFFICE/DocumentServer#99]
environment
```
npm -v
4.4.4

node -v
6.10.1

cat /etc/issue
Ubuntu 14.04.5 LTS
```
reference http://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx
Build server
cd ../server && make

**1.Error one**
```
Running "checkDependencies:./build/server/Metrics" (checkDependencies) task
Verifying property checkDependencies.\./build/server/Metrics exists in config...OK
File: [no files]
Options: install, continueAfterInstall, packageDir="./build/server/Metrics"
>> statsd: not installed!
Invoking npm install...

> node-syslog@1.1.7 install /home/wangxiaowei/DocumentServer/server/build/server/Metrics/node_modules/node-syslog
> node-gyp rebuild

make[1]: 正在进入目录 `/home/wangxiaowei/DocumentServer/server/build/server/Metrics/node_modules/node-syslog/build'
  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:1:0:
../node-syslog.h:22:45: error: ‘Arguments’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> init   (const v8::Arguments& args);
                                             ^
../node-syslog.h:22:60: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static v8::Handle<v8::Value> init   (const v8::Arguments& args);
                                                            ^
../node-syslog.h:23:42: error: ‘Arguments’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> log (const v8::Arguments& args);
                                          ^
../node-syslog.h:23:57: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static v8::Handle<v8::Value> log (const v8::Arguments& args);
                                                         ^
../node-syslog.h:24:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> setMask (const v8::Arguments& args);
                                              ^
../node-syslog.h:24:61: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static v8::Handle<v8::Value> setMask (const v8::Arguments& args);
                                                             ^
../node-syslog.h:25:46: error: ‘Arguments’ in namespace ‘v8’ does not name a type
  static v8::Handle<v8::Value> destroy (const v8::Arguments& args);
                                              ^
../node-syslog.h:25:61: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
  static v8::Handle<v8::Value> destroy (const v8::Arguments& args);
                                                             ^
../syslog.cc: In static member function ‘static void node::Syslog::Initialize(v8::Handle<v8::Object>)’:
../syslog.cc:13:52: error: no matching function for call to ‘v8::FunctionTemplate::New()’
  Local<FunctionTemplate> t = FunctionTemplate::New();
```

**2.Error two**
```
> hashring@1.0.1 install /home/wangxiaowei/DocumentServer/server/build/server/Metrics/node_modules/hashring
> node-gyp rebuild

make[1]: 正在进入目录 `/home/wangxiaowei/DocumentServer/server/build/server/Metrics/node_modules/hashring/build'
  CXX(target) Release/obj.target/hashvalue/src/hashvalue.o
../src/hashvalue.cc:6:28: error: ‘Arguments’ does not name a type
 Handle<Value> Hasher(const Arguments& args) {
                            ^
../src/hashvalue.cc:6:39: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
 Handle<Value> Hasher(const Arguments& args) {
                                       ^
In file included from ../src/hashvalue.cc:1:0:
/home/wangxiaowei/.node-gyp/6.10.1/include/node/v8.h: In function ‘v8::Handle<v8::Value> Hasher(const int&)’:
/home/wangxiaowei/.node-gyp/6.10.1/include/node/v8.h:915:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/hashvalue.cc:7:15: error: within this context
   HandleScope scope;
               ^
../src/hashvalue.cc:9:36: error: invalid types ‘const int[int]’ for array subscript
   unsigned int hash = ((int) args[0]->NumberValue() << 24)
                                    ^
../src/hashvalue.cc:10:20: error: invalid types ‘const int[int]’ for array subscript
     | ((int) args[1]->NumberValue() << 16)
                    ^
../src/hashvalue.cc:11:20: error: invalid types ‘const int[int]’ for array subscript
     | ((int) args[2]->NumberValue() << 8)
                    ^
../src/hashvalue.cc:12:19: error: invalid types ‘const int[int]’ for array subscript
     | (int) args[3]->NumberValue();
                   ^
../src/hashvalue.cc:14:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(Number::New(hash));
                ^
../src/hashvalue.cc:14:38: error: no matching function for call to ‘v8::Number::New(unsigned int&)’
   return scope.Close(Number::New(hash));
                                      ^
../src/hashvalue.cc:14:38: note: candidate is:
In file included from ../src/hashvalue.cc:1:0:
/home/wangxiaowei/.node-gyp/6.10.1/include/node/v8.h:2545:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/wangxiaowei/.node-gyp/6.10.1/include/node/v8.h:2545:24: note:   candidate expects 2 arguments, 1 provided
../src/hashvalue.cc: In function ‘void init(v8::Handle<v8::Object>)’:
../src/hashvalue.cc:19:7: error: ‘NewSymbol’ is not a member of ‘v8::String’
       String::NewSymbol("hash")
       ^
../src/hashvalue.cc:20:35: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
     , FunctionTemplate::New(Hasher)->GetFunction()
                                   ^
../src/hashvalue.cc:20:35: note: candidates are:
In file included from ../src/hashvalue.cc:1:0:
/home/wangxiaowei/.node-gyp/6.10.1/include/node/v8.h:4484:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/wangxiaowei/.node-gyp/6.10.1/include/node/v8.h:4484:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
/home/wangxiaowei/.node-gyp/6.10.1/include/node/v8.h:4488:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)
   static Local<FunctionTemplate> New(
                                  ^
/home/wangxiaowei/.node-gyp/6.10.1/include/node/v8.h:4488:34: note:   candidate expects 6 arguments, 1 provided
../src/hashvalue.cc: In function ‘v8::Handle<v8::Value> Hasher(const int&)’:
../src/hashvalue.cc:15:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [Release/obj.target/hashvalue/src/hashvalue.o] 错误 1
make[1]:正在离开目录 `/home/wangxiaowei/DocumentServer/server/build/server/Metrics/node_modules/hashring/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-31-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/wangxiaowei/DocumentServer/server/build/server/Metrics/node_modules/hashring
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
```

**Comment by ShockwaveNN** [comment]
@pwxwabcd Seems like this error: https://github.com/tblobaum/rconsole/issues/13
Think you need to update your gcc to version like [mine](https://github.com/ONLYOFFICE/DocumentServer/issues/93#issuecomment-291793069) in Ubuntu 14.04.

**Comment by pwxwabcd** [comment]
@ShockwaveNN 

gcc -v
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
```

error still exists

**Comment by ShockwaveNN** [comment]
@pwxwabcd 
Hm, exactly same version of gcc.
I want to reproduce the problem.
What was your steps so far?
Do you use clean install of ubuntu 14.04.3 and completed all the steps prior http://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx before
`cd ../server && make`?
I have a [Dockerfile](https://github.com/onlyoffice-testing-robot/documentserver-docker-from-manual/blob/master/Dockerfile) to compile using this instruction and all seems fine for me

**Comment by ShockwaveNN** [comment]
Closing due to lack of feedback
